$gwx21_XC_11 = (function (
  _,
  _v,
  _n,
  _p,
  _s,
  _wp,
  _wl,
  $gwn,
  $gwl,
  $gwh,
  wh,
  $gstack,
  $gwrt,
  gra,
  grb,
  TestTest,
  wfor,
  _ca,
  _da,
  _r,
  _rz,
  _o,
  _oz,
  _1,
  _1z,
  _2,
  _2z,
  _m,
  _mz,
  nv_getDate,
  nv_getRegExp,
  nv_console,
  nv_parseInt,
  nv_parseFloat,
  nv_isNaN,
  nv_isFinite,
  nv_decodeURI,
  nv_decodeURIComponent,
  nv_encodeURI,
  nv_encodeURIComponent,
  $gdc,
  nv_JSON,
  _af,
  _gv,
  _ai,
  _grp,
  _gd,
  _gapi,
  $ixc,
  _ic,
  _w,
  _ev,
  _tsd
) {
  return function (path, global) {
    if (typeof global === "undefined") {
      if (typeof __GWX_GLOBAL__ === "undefined") global = {};
      else global = __GWX_GLOBAL__;
    }
    if (typeof __WXML_GLOBAL__ === "undefined") {
      __WXML_GLOBAL__ = {};
    }
    __WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
    var e_ = {};
    if (typeof global.entrys === "undefined") global.entrys = {};
    e_ = global.entrys;
    var d_ = {};
    if (typeof global.defines === "undefined") global.defines = {};
    d_ = global.defines;
    var f_ = {};
    if (typeof global.modules === "undefined") global.modules = {};
    f_ = global.modules || {};
    var p_ = {};
    __WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {};
    __WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
    __WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
    var z = __WXML_GLOBAL__.ops_set.$gwx21_XC_11 || [];
    function gz$gwx21_XC_11_1() {
      if (__WXML_GLOBAL__.ops_cached.$gwx21_XC_11_1)
        return __WXML_GLOBAL__.ops_cached.$gwx21_XC_11_1;
      __WXML_GLOBAL__.ops_cached.$gwx21_XC_11_1 = [];
      (function (z) {
        var a = 11;
        function Z(ops) {
          z.push(ops);
        }
        Z([[7], [3, "w"]]);
        Z([
          [4],
          [
            [5],
            [[5], [[5], [1, "_span"]], [1, "data-v-7acbd3a7"]],
            [[7], [3, "x"]],
          ],
        ]);
        Z([3, "showContent"]);
        Z([[7], [3, "y"]]);
        Z([3, "_div mod-real-content data-v-7acbd3a7"]);
        Z([3, "start"]);
        Z([3, "pItem"]);
        Z([[7], [3, "a"]]);
        Z([3, "iContent"]);
        Z([[6], [[7], [3, "pItem"]], [3, "a"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "a"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "d"]]);
        Z([
          [4],
          [
            [5],
            [
              [5],
              [[5], [[5], [1, "_span"]], [1, "link"]],
              [1, "data-v-7acbd3a7"],
            ],
            [[6], [[7], [3, "iContent"]], [3, "e"]],
          ],
        ]);
        Z([[6], [[7], [3, "iContent"]], [3, "b"]]);
        Z([3, "_i sq-icon-gegu data-v-7acbd3a7"]);
        Z([a, [[6], [[7], [3, "iContent"]], [3, "c"]]]);
        Z([[6], [[7], [3, "iContent"]], [3, "f"]]);
        Z([
          [4],
          [
            [5],
            [[5], [[5], [1, "_span"]], [1, "data-v-7acbd3a7"]],
            [[6], [[7], [3, "iContent"]], [3, "g"]],
          ],
        ]);
        Z([[6], [[7], [3, "iContent"]], [3, "h"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "i"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "l"]]);
        Z([
          [4],
          [
            [5],
            [
              [5],
              [[5], [[5], [1, "_span"]], [1, "link"]],
              [1, "data-v-7acbd3a7"],
            ],
            [[6], [[7], [3, "iContent"]], [3, "k"]],
          ],
        ]);
        Z([3, "_i sq-icon-huati data-v-7acbd3a7"]);
        Z([a, [[6], [[7], [3, "iContent"]], [3, "j"]]]);
        Z([[6], [[7], [3, "iContent"]], [3, "m"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "p"]]);
        Z([
          [4],
          [
            [5],
            [
              [5],
              [[5], [[5], [1, "_span"]], [1, "link"]],
              [1, "data-v-7acbd3a7"],
            ],
            [[6], [[7], [3, "iContent"]], [3, "o"]],
          ],
        ]);
        Z([3, "_i sq-icon-xuangu data-v-7acbd3a7"]);
        Z([a, [[6], [[7], [3, "iContent"]], [3, "n"]]]);
        Z([[6], [[7], [3, "iContent"]], [3, "q"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "t"]]);
        Z([
          [4],
          [
            [5],
            [
              [5],
              [[5], [[5], [1, "_span"]], [1, "link"]],
              [1, "data-v-7acbd3a7"],
            ],
            [[6], [[7], [3, "iContent"]], [3, "s"]],
          ],
        ]);
        Z([3, "_i sq-icon-at data-v-7acbd3a7"]);
        Z([a, [[6], [[7], [3, "iContent"]], [3, "r"]]]);
        Z([[6], [[7], [3, "iContent"]], [3, "v"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "y"]]);
        Z([
          [4],
          [
            [5],
            [[5], [[5], [1, "_span"]], [1, "data-v-7acbd3a7"]],
            [[6], [[7], [3, "iContent"]], [3, "x"]],
          ],
        ]);
        Z([3, "_i sq-icon-zhibo data-v-7acbd3a7"]);
        Z([a, [[6], [[7], [3, "iContent"]], [3, "w"]]]);
        Z([[6], [[7], [3, "iContent"]], [3, "z"]]);
        Z([3, "__l"]);
        Z([[6], [[7], [3, "iContent"]], [3, "A"]]);
        Z([3, "link data-v-7acbd3a7"]);
        Z([[6], [[7], [3, "iContent"]], [3, "B"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "C"]]);
        Z([[6], [[7], [3, "iContent"]], [3, "D"]]);
        Z([3, "data-v-7acbd3a7"]);
        Z([[6], [[7], [3, "iContent"]], [3, "E"]]);
        Z([
          [4],
          [
            [5],
            [[5], [[5], [1, "_span"]], [1, "data-v-7acbd3a7"]],
            [[6], [[7], [3, "iContent"]], [3, "G"]],
          ],
        ]);
        Z([a, [[6], [[7], [3, "iContent"]], [3, "F"]]]);
        Z([[7], [3, "b"]]);
        Z(z[40]);
        Z([[7], [3, "d"]]);
        Z([[7], [3, "e"]]);
        Z([3, "r data-v-7acbd3a7"]);
        Z([3, "7acbd3a7-1"]);
        Z([[7], [3, "f"]]);
        Z([3, "showMore"]);
        Z([[7], [3, "g"]]);
        Z([
          [4],
          [
            [5],
            [
              [5],
              [
                [5],
                [[5], [[5], [1, "_div"]], [1, "data-v-7acbd3a7"]],
                [1, "show-more"],
              ],
              [[7], [3, "n"]],
            ],
            [[7], [3, "o"]],
          ],
        ]);
        Z([[7], [3, "h"]]);
        Z([3, "_i shadow-box data-v-7acbd3a7"]);
        Z([3, " "]);
        Z([[7], [3, "i"]]);
        Z([[7], [3, "k"]]);
        Z([3, "_span text data-v-7acbd3a7"]);
        Z([3, "_span dian data-v-7acbd3a7"]);
        Z([3, "..."]);
        Z([3, "_span fold-text data-v-7acbd3a7"]);
        Z([a, [[7], [3, "j"]]]);
        Z([[7], [3, "m"]]);
        Z(z[65]);
        Z([3, "_span data-v-7acbd3a7"]);
        Z([a, [[7], [3, "l"]]]);
        Z([[7], [3, "p"]]);
        Z([[7], [3, "v"]]);
        Z([
          [4],
          [
            [5],
            [[5], [[5], [1, "_span"]], [1, "data-v-7acbd3a7"]],
            [[7], [3, "r"]],
          ],
        ]);
        Z([[7], [3, "s"]]);
        Z([1, 0]);
        Z([[7], [3, "t"]]);
        Z([a, [[7], [3, "q"]]]);
      })(__WXML_GLOBAL__.ops_cached.$gwx21_XC_11_1);
      return __WXML_GLOBAL__.ops_cached.$gwx21_XC_11_1;
    }
    __WXML_GLOBAL__.ops_set.$gwx21_XC_11 = z;
    __WXML_GLOBAL__.ops_init.$gwx21_XC_11 = true;
    var x = [
      "./pages/newsSbg/@tencent/stock-sq/src/source/shortContent/index.wxml",
    ];
    d_[x[0]] = {};
    var m0 = function (e, s, r, gg) {
      var z = gz$gwx21_XC_11_1();
      var cDX = _mz(
        z,
        "label",
        ["catchtap", 0, "class", 1, "ref", 1, "style", 2],
        [],
        e,
        s,
        gg
      );
      var oHX = _n("view");
      _rz(z, oHX, "class", 4, e, s, gg);
      var lIX = _n("slot");
      _rz(z, lIX, "name", 5, e, s, gg);
      _(oHX, lIX);
      var aJX = _v();
      _(oHX, aJX);
      var tKX = function (bMX, eLX, oNX, gg) {
        var oPX = _v();
        _(oNX, oPX);
        var fQX = function (hSX, cRX, oTX, gg) {
          var oVX = _v();
          _(oTX, oVX);
          if (_oz(z, 10, hSX, cRX, gg)) {
            oVX.wxVkey = 1;
            var lWX = _mz(
              z,
              "label",
              ["catchtap", 11, "class", 1],
              [],
              hSX,
              cRX,
              gg
            );
            var aXX = _v();
            _(lWX, aXX);
            if (_oz(z, 13, hSX, cRX, gg)) {
              aXX.wxVkey = 1;
              var tYX = _n("view");
              _rz(z, tYX, "class", 14, hSX, cRX, gg);
              _(aXX, tYX);
            }
            var eZX = _oz(z, 15, hSX, cRX, gg);
            _(lWX, eZX);
            aXX.wxXCkey = 1;
            _(oVX, lWX);
          } else if (_oz(z, 16, hSX, cRX, gg)) {
            oVX.wxVkey = 2;
            var b1X = _mz(
              z,
              "label",
              ["class", 17, "data-name", 1],
              [],
              hSX,
              cRX,
              gg
            );
            _(oVX, b1X);
          } else if (_oz(z, 19, hSX, cRX, gg)) {
            oVX.wxVkey = 3;
            var o2X = _mz(
              z,
              "label",
              ["catchtap", 20, "class", 1],
              [],
              hSX,
              cRX,
              gg
            );
            var x3X = _n("view");
            _rz(z, x3X, "class", 22, hSX, cRX, gg);
            _(o2X, x3X);
            var o4X = _oz(z, 23, hSX, cRX, gg);
            _(o2X, o4X);
            _(oVX, o2X);
          } else if (_oz(z, 24, hSX, cRX, gg)) {
            oVX.wxVkey = 4;
            var f5X = _mz(
              z,
              "label",
              ["catchtap", 25, "class", 1],
              [],
              hSX,
              cRX,
              gg
            );
            var c6X = _n("view");
            _rz(z, c6X, "class", 27, hSX, cRX, gg);
            _(f5X, c6X);
            var h7X = _oz(z, 28, hSX, cRX, gg);
            _(f5X, h7X);
            _(oVX, f5X);
          } else if (_oz(z, 29, hSX, cRX, gg)) {
            oVX.wxVkey = 5;
            var o8X = _mz(
              z,
              "label",
              ["catchtap", 30, "class", 1],
              [],
              hSX,
              cRX,
              gg
            );
            var c9X = _n("view");
            _rz(z, c9X, "class", 32, hSX, cRX, gg);
            _(o8X, c9X);
            var o0X = _oz(z, 33, hSX, cRX, gg);
            _(o8X, o0X);
            _(oVX, o8X);
          } else if (_oz(z, 34, hSX, cRX, gg)) {
            oVX.wxVkey = 6;
            var lAY = _mz(
              z,
              "label",
              ["catchtap", 35, "class", 1],
              [],
              hSX,
              cRX,
              gg
            );
            var aBY = _n("view");
            _rz(z, aBY, "class", 37, hSX, cRX, gg);
            _(lAY, aBY);
            var tCY = _oz(z, 38, hSX, cRX, gg);
            _(lAY, tCY);
            _(oVX, lAY);
          } else if (_oz(z, 39, hSX, cRX, gg)) {
            oVX.wxVkey = 7;
            var eDY = _mz(
              z,
              "item-cmp",
              ["bind:__l", 40, "bindtapHyper", 1, "class", 2, "uI", 3, "uP", 4],
              [],
              hSX,
              cRX,
              gg
            );
            _(oVX, eDY);
          } else if (_oz(z, 45, hSX, cRX, gg)) {
            oVX.wxVkey = 8;
            var bEY = _n("view");
            _rz(z, bEY, "class", 46, hSX, cRX, gg);
            _(oVX, bEY);
          } else if (_oz(z, 47, hSX, cRX, gg)) {
            oVX.wxVkey = 9;
            var oFY = _n("label");
            _rz(z, oFY, "class", 48, hSX, cRX, gg);
            var xGY = _oz(z, 49, hSX, cRX, gg);
            _(oFY, xGY);
            _(oVX, oFY);
          }
          oVX.wxXCkey = 1;
          oVX.wxXCkey = 3;
          return oTX;
        };
        oPX.wxXCkey = 4;
        _2z(z, 9, fQX, bMX, eLX, gg, oPX, "iContent", "index", "");
        return oNX;
      };
      aJX.wxXCkey = 4;
      _2z(z, 7, tKX, e, s, gg, aJX, "pItem", "index", "");
      _(cDX, oHX);
      var hEX = _v();
      _(cDX, hEX);
      if (_oz(z, 50, e, s, gg)) {
        hEX.wxVkey = 1;
        var oHY = _mz(
          z,
          "show-more",
          [
            "bind:__l",
            51,
            "bindmounted",
            1,
            "bindtoggleShow",
            2,
            "class",
            3,
            "uI",
            4,
            "uP",
            5,
            "uR",
            6,
          ],
          [],
          e,
          s,
          gg
        );
        _(hEX, oHY);
      }
      var oFX = _v();
      _(cDX, oFX);
      if (_oz(z, 58, e, s, gg)) {
        oFX.wxVkey = 1;
        var fIY = _n("view");
        _rz(z, fIY, "class", 59, e, s, gg);
        var cJY = _v();
        _(fIY, cJY);
        if (_oz(z, 60, e, s, gg)) {
          cJY.wxVkey = 1;
          var oLY = _n("view");
          _rz(z, oLY, "class", 61, e, s, gg);
          var cMY = _oz(z, 62, e, s, gg);
          _(oLY, cMY);
          _(cJY, oLY);
        }
        var hKY = _v();
        _(fIY, hKY);
        if (_oz(z, 63, e, s, gg)) {
          hKY.wxVkey = 1;
          var oNY = _mz(z, "label", ["catchtap", 64, "class", 1], [], e, s, gg);
          var lOY = _n("label");
          _rz(z, lOY, "class", 66, e, s, gg);
          var aPY = _oz(z, 67, e, s, gg);
          _(lOY, aPY);
          _(oNY, lOY);
          var tQY = _n("label");
          _rz(z, tQY, "class", 68, e, s, gg);
          var eRY = _oz(z, 69, e, s, gg);
          _(tQY, eRY);
          _(oNY, tQY);
          _(hKY, oNY);
        } else {
          hKY.wxVkey = 2;
          var bSY = _mz(z, "label", ["catchtap", 70, "class", 1], [], e, s, gg);
          var oTY = _n("label");
          _rz(z, oTY, "class", 72, e, s, gg);
          var xUY = _oz(z, 73, e, s, gg);
          _(oTY, xUY);
          _(bSY, oTY);
          _(hKY, bSY);
        }
        cJY.wxXCkey = 1;
        hKY.wxXCkey = 1;
        _(oFX, fIY);
      }
      var cGX = _v();
      _(cDX, cGX);
      if (_oz(z, 74, e, s, gg)) {
        cGX.wxVkey = 1;
        var oVY = _mz(
          z,
          "label",
          [
            "catchtap",
            75,
            "class",
            1,
            "data-images",
            2,
            "data-index",
            3,
            "data-urls",
            4,
          ],
          [],
          e,
          s,
          gg
        );
        var fWY = _oz(z, 80, e, s, gg);
        _(oVY, fWY);
        _(cGX, oVY);
      }
      hEX.wxXCkey = 1;
      hEX.wxXCkey = 3;
      oFX.wxXCkey = 1;
      cGX.wxXCkey = 1;
      _(r, cDX);
      return r;
    };
    e_[x[0]] = { f: m0, j: [], i: [], ti: [], ic: [] };
    if (path && e_[path]) {
      outerGlobal.__wxml_comp_version__ = 0.02;
      return function (env, dd, global) {
        $gwxc = 0;
        var root = { tag: "wx-page" };
        root.children = [];
        g = "$gwx21_XC_11";
        var main = e_[path].f;
        if (typeof global === "undefined") global = {};
        global.f = $gdc(f_[path], "", 1);
        if (
          typeof outerGlobal.__webview_engine_version__ != "undefined" &&
          outerGlobal.__webview_engine_version__ + 1e-6 >= 0.02 + 1e-6 &&
          outerGlobal.__mergeData__
        ) {
          env = outerGlobal.__mergeData__(env, dd);
        }
        try {
          main(env, {}, root, global);
          _tsd(root);
          if (
            typeof outerGlobal.__webview_engine_version__ == "undefined" ||
            outerGlobal.__webview_engine_version__ + 1e-6 < 0.01 + 1e-6
          ) {
            return _ev(root);
          }
        } catch (err) {
          console.log(err);
        }
        g = "";
        return root;
      };
    }
  };
})(
  __g.a,
  __g.b,
  __g.c,
  __g.d,
  __g.e,
  __g.f,
  __g.g,
  __g.h,
  __g.i,
  __g.j,
  __g.k,
  __g.l,
  __g.m,
  __g.n,
  __g.o,
  __g.p,
  __g.q,
  __g.r,
  __g.s,
  __g.t,
  __g.u,
  __g.v,
  __g.w,
  __g.x,
  __g.y,
  __g.z,
  __g.A,
  __g.B,
  __g.C,
  __g.D,
  __g.E,
  __g.F,
  __g.G,
  __g.H,
  __g.I,
  __g.J,
  __g.K,
  __g.L,
  __g.M,
  __g.N,
  __g.O,
  __g.P,
  __g.Q,
  __g.R,
  __g.S,
  __g.T,
  __g.U,
  __g.V,
  __g.W,
  __g.X,
  __g.Y,
  __g.Z,
  __g.aa
);
if (__vd_version_info__.delayedGwx || false) $gwx21_XC_11();
if (__vd_version_info__.delayedGwx)
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/shortContent/index.wxml"
  ] = [
    $gwx21_XC_11,
    "./pages/newsSbg/@tencent/stock-sq/src/source/shortContent/index.wxml",
  ];
else
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/shortContent/index.wxml"
  ] = $gwx21_XC_11(
    "./pages/newsSbg/@tencent/stock-sq/src/source/shortContent/index.wxml"
  );

var noCss =
  typeof __vd_version_info__ !== "undefined" &&
  __vd_version_info__.noCss === true;
if (!noCss) {
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/shortContent/index.wxss"
  ] = setCssToHead(
    [
      ".",
      [1],
      "mod-show-content\x3ewx-span.",
      [1],
      "plain wx-a.",
      [1],
      "data-v-7acbd3a7{color:#4774b3!important}\n.",
      [1],
      "mod-show-content\x3ewx-span.",
      [1],
      "plain wx-a.",
      [1],
      "disable.",
      [1],
      "data-v-7acbd3a7{color:#32394d}\n@font-face{font-family:snowFont;font-style:normal;font-weight:400;src:url(https://wzq.gtimg.com/resources/mp/lite/fonts/sq/icomoon.eot?knu6e2);src:url(https://wzq.gtimg.com/resources/mp/lite/fonts/sq/icomoon.eot?knu6e2#iefix) format(\x22embedded-opentype\x22),url(https://wzq.gtimg.com/resources/mp/lite/fonts/sq/icomoon.ttf?knu6e2) format(\x22truetype\x22),url(https://wzq.gtimg.com/resources/mp/lite/fonts/sq/icomoon.woff?knu6e2) format(\x22woff\x22),url(https://wzq.gtimg.com/resources/mp/lite/fonts/sq/icomoon.svg) format(\x22svg\x22)}\n[class*\x3d\x22 sq-icon-\x22].",
      [1],
      "data-v-7acbd3a7,[class^\x3dsq-icon-].",
      [1],
      "data-v-7acbd3a7{speak:none;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;display:inline-block;font-family:snowFont!important;font-style:normal;font-variant:normal;font-weight:400;line-height:1;position:relative;text-transform:none}\n.",
      [1],
      "sq-icon-hongniu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e908\x22}\n.",
      [1],
      "sq-icon-niu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e90d\x22}\n.",
      [1],
      "sq-icon-peitu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e902\x22}\n.",
      [1],
      "sq-icon-zhibo.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e905\x22}\n.",
      [1],
      "sq-icon-at.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e900\x22}\n.",
      [1],
      "sq-icon-gegu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e901\x22}\n.",
      [1],
      "sq-icon-huati.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e903\x22}\n.",
      [1],
      "sq-icon-lianjie.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e904\x22}\n.",
      [1],
      "sq-icon-pinglun.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e906\x22}\n.",
      [1],
      "sq-icon-sangedian.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e907\x22}\n.",
      [1],
      "sq-icon-xuangu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e909\x22}\n.",
      [1],
      "sq-icon-zhuanfa.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e90a\x22}\n.",
      [1],
      "sq-icon-bk.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e901\x22}\n.",
      [1],
      "sq-icon-hongniu.",
      [1],
      "data-v-7acbd3a7{color:#e63535}\n.",
      [1],
      "sq-icon-gegu.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "sq-icon-zhuanfa.",
      [1],
      "data-v-7acbd3a7{top:.013333333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "data-v-7acbd3a7{background-image:url(https://st.gtimg.com/design/9bc2b37b992b5f3a575387bab153ed0f.png);background-repeat:no-repeat;background-size:3.36rem 3.92rem;height:.56rem;margin-right:.08rem;width:.56rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-0.",
      [1],
      "data-v-7acbd3a7{background-position:.02666666666666667rem .02666666666666667rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-1.",
      [1],
      "data-v-7acbd3a7{background-position:-.5333333333333333rem .02666666666666667rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-2.",
      [1],
      "data-v-7acbd3a7{background-position:-1.0933333333333333rem .02666666666666667rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-3.",
      [1],
      "data-v-7acbd3a7{background-position:-1.6533333333333333rem .02666666666666667rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-4.",
      [1],
      "data-v-7acbd3a7{background-position:-2.2133333333333334rem .02666666666666667rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-5.",
      [1],
      "data-v-7acbd3a7{background-position:-2.7733333333333334rem .02666666666666667rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-6.",
      [1],
      "data-v-7acbd3a7{background-position:.02666666666666667rem -.5333333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-7.",
      [1],
      "data-v-7acbd3a7{background-position:-.5333333333333333rem -.5333333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-8.",
      [1],
      "data-v-7acbd3a7{background-position:-1.0933333333333333rem -.5333333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-9.",
      [1],
      "data-v-7acbd3a7{background-position:-1.6533333333333333rem -.5333333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-10.",
      [1],
      "data-v-7acbd3a7{background-position:-2.2133333333333334rem -.5333333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-11.",
      [1],
      "data-v-7acbd3a7{background-position:-2.7733333333333334rem -.5333333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-12.",
      [1],
      "data-v-7acbd3a7{background-position:.02666666666666667rem -1.0933333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-13.",
      [1],
      "data-v-7acbd3a7{background-position:-.5333333333333333rem -1.0933333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-14.",
      [1],
      "data-v-7acbd3a7{background-position:-1.0933333333333333rem -1.0933333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-15.",
      [1],
      "data-v-7acbd3a7{background-position:-1.6533333333333333rem -1.0933333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-16.",
      [1],
      "data-v-7acbd3a7{background-position:-2.2133333333333334rem -1.0933333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-17.",
      [1],
      "data-v-7acbd3a7{background-position:-2.7733333333333334rem -1.0933333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-18.",
      [1],
      "data-v-7acbd3a7{background-position:.02666666666666667rem -1.6533333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-19.",
      [1],
      "data-v-7acbd3a7{background-position:-.5333333333333333rem -1.6533333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-20.",
      [1],
      "data-v-7acbd3a7{background-position:-1.0933333333333333rem -1.6533333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-21.",
      [1],
      "data-v-7acbd3a7{background-position:-1.6533333333333333rem -1.6533333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-22.",
      [1],
      "data-v-7acbd3a7{background-position:-2.2133333333333334rem -1.6533333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-23.",
      [1],
      "data-v-7acbd3a7{background-position:-2.7733333333333334rem -1.6533333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-24.",
      [1],
      "data-v-7acbd3a7{background-position:.02666666666666667rem -2.2133333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-25.",
      [1],
      "data-v-7acbd3a7{background-position:-.5333333333333333rem -2.2133333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-26.",
      [1],
      "data-v-7acbd3a7{background-position:-1.0933333333333333rem -2.2133333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-27.",
      [1],
      "data-v-7acbd3a7{background-position:-1.6533333333333333rem -2.2133333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-28.",
      [1],
      "data-v-7acbd3a7{background-position:-2.2133333333333334rem -2.2133333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-29.",
      [1],
      "data-v-7acbd3a7{background-position:-2.7733333333333334rem -2.2133333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-30.",
      [1],
      "data-v-7acbd3a7{background-position:.02666666666666667rem -2.7733333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-31.",
      [1],
      "data-v-7acbd3a7{background-position:-.5333333333333333rem -2.7733333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-32.",
      [1],
      "data-v-7acbd3a7{background-position:-1.0933333333333333rem -2.7733333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-33.",
      [1],
      "data-v-7acbd3a7{background-position:-1.6533333333333333rem -2.7733333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-34.",
      [1],
      "data-v-7acbd3a7{background-position:-2.2133333333333334rem -2.7733333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-35.",
      [1],
      "data-v-7acbd3a7{background-position:-2.7733333333333334rem -2.7733333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-36.",
      [1],
      "data-v-7acbd3a7{background-position:.02666666666666667rem -3.3333333333333335rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-37.",
      [1],
      "data-v-7acbd3a7{background-position:-.5333333333333333rem -3.3333333333333335rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-38.",
      [1],
      "data-v-7acbd3a7{background-position:-1.0933333333333333rem -3.3333333333333335rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-39.",
      [1],
      "data-v-7acbd3a7{background-position:-1.6533333333333333rem -3.3333333333333335rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-40.",
      [1],
      "data-v-7acbd3a7{background-position:-2.2133333333333334rem -3.3333333333333335rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-s0.",
      [1],
      "eid-41.",
      [1],
      "data-v-7acbd3a7{background-position:-2.7733333333333334rem -3.3333333333333335rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "data-v-7acbd3a7{display:inline-block;height:.56rem;position:relative;vertical-align:top;width:.56rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "isAndroid.",
      [1],
      "data-v-7acbd3a7{margin-bottom:.05333333333333334rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "comment.",
      [1],
      "data-v-7acbd3a7{-webkit-transform:scale(.875);transform:scale(.875)}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-0.",
      [1],
      "data-v-7acbd3a7{background-image:url(https://mat1.gtimg.com/finance/images/stock/p/comment_wx/a474ef4a7d889bff.png);background-repeat:no-repeat;background-size:7.333333333333333rem 3.28rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-1.",
      [1],
      "data-v-7acbd3a7{background-image:url(https://mat1.gtimg.com/finance/images/stock/p/comment_wx/0b215560b8caac9e.png);background-repeat:no-repeat;background-size:7.333333333333333rem 3.28rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-2.",
      [1],
      "data-v-7acbd3a7{background-image:url(https://mat1.gtimg.com/finance/images/stock/p/comment_wx/4c2d39200c6e2ae5.png);background-repeat:no-repeat;background-size:7.333333333333333rem 3.28rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-3.",
      [1],
      "data-v-7acbd3a7{background-image:url(https://mat1.gtimg.com/finance/images/stock/p/comment_wx/8adcdc8f0a0fd349.png);background-repeat:no-repeat;background-size:7.333333333333333rem 3.28rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "epage-4.",
      [1],
      "data-v-7acbd3a7{background-image:url(https://mat1.gtimg.com/finance/images/stock/p/comment_wx/fc7e966c0fcb82d6.png);background-repeat:no-repeat;background-size:7.333333333333333rem 3.28rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-0.",
      [1],
      "data-v-7acbd3a7{background-position:-.32rem -.26666666666666666rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-1.",
      [1],
      "data-v-7acbd3a7{background-position:-1.36rem -.26666666666666666rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-2.",
      [1],
      "data-v-7acbd3a7{background-position:-2.4rem -.26666666666666666rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-3.",
      [1],
      "data-v-7acbd3a7{background-position:-3.44rem -.26666666666666666rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-4.",
      [1],
      "data-v-7acbd3a7{background-position:-4.48rem -.26666666666666666rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-5.",
      [1],
      "data-v-7acbd3a7{background-position:-5.493333333333333rem -.26666666666666666rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-6.",
      [1],
      "data-v-7acbd3a7{background-position:-6.533333333333333rem -.26666666666666666rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-7.",
      [1],
      "data-v-7acbd3a7{background-position:-.32rem -1.1733333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-8.",
      [1],
      "data-v-7acbd3a7{background-position:-1.36rem -1.1733333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-9.",
      [1],
      "data-v-7acbd3a7{background-position:-2.4rem -1.1733333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-10.",
      [1],
      "data-v-7acbd3a7{background-position:-3.44rem -1.1733333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-11.",
      [1],
      "data-v-7acbd3a7{background-position:-4.48rem -1.1733333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-12.",
      [1],
      "data-v-7acbd3a7{background-position:-5.493333333333333rem -1.1733333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-13.",
      [1],
      "data-v-7acbd3a7{background-position:-6.533333333333333rem -1.1733333333333333rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-14.",
      [1],
      "data-v-7acbd3a7{background-position:-.32rem -2.08rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-15.",
      [1],
      "data-v-7acbd3a7{background-position:-1.36rem -2.08rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-16.",
      [1],
      "data-v-7acbd3a7{background-position:-2.4rem -2.08rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-17.",
      [1],
      "data-v-7acbd3a7{background-position:-3.44rem -2.08rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-18.",
      [1],
      "data-v-7acbd3a7{background-position:-4.48rem -2.08rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "eid-19.",
      [1],
      "data-v-7acbd3a7{background-position:-5.493333333333333rem -2.08rem}\n.",
      [1],
      "comment_item_emoji.",
      [1],
      "del.",
      [1],
      "data-v-7acbd3a7{background-position:-6.533333333333333rem -2.08rem}\n.",
      [1],
      "black .",
      [1],
      "mod-show-content.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "dark .",
      [1],
      "mod-show-content.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-content.",
      [1],
      "data-v-7acbd3a7,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-content.",
      [1],
      "data-v-7acbd3a7{color:#f0f1f5}\n.",
      [1],
      "black .",
      [1],
      "mod-show-content.",
      [1],
      "isComment.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "dark .",
      [1],
      "mod-show-content.",
      [1],
      "isComment.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-content.",
      [1],
      "isComment.",
      [1],
      "data-v-7acbd3a7,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-content.",
      [1],
      "isComment.",
      [1],
      "data-v-7acbd3a7{color:#a7b0c4}\n.",
      [1],
      "black .",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "onClick.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "dark .",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "onClick.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "onClick.",
      [1],
      "data-v-7acbd3a7,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "onClick.",
      [1],
      "data-v-7acbd3a7{color:#f0f1f5}\n.",
      [1],
      "mod-show-content.",
      [1],
      "data-v-7acbd3a7{word-wrap:break-word;display:inline-block;max-width:100%;overflow:hidden;position:relative;white-space:normal;width:100%;word-break:break-all}\n.",
      [1],
      "mod-show-content.",
      [1],
      "turnShort.",
      [1],
      "data-v-7acbd3a7{color:#606980;font-size:.37333333333333335rem;line-height:.52rem;margin-top:.29333333333333333rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "snp-red.",
      [1],
      "data-v-7acbd3a7{color:#da5341}\n.",
      [1],
      "mod-show-content .",
      [1],
      "snp-blue.",
      [1],
      "data-v-7acbd3a7{color:#007aff}\n.",
      [1],
      "mod-show-content .",
      [1],
      "snp-bold.",
      [1],
      "data-v-7acbd3a7{font-weight:700}\n.",
      [1],
      "mod-show-content .",
      [1],
      "comment-hide-image.",
      [1],
      "data-v-7acbd3a7{color:#4774b3;font-size:.37333333333333335rem;white-space:nowrap}\n.",
      [1],
      "mod-show-content .",
      [1],
      "comment-hide-image.",
      [1],
      "turn.",
      [1],
      "data-v-7acbd3a7{font-size:.4266666666666667rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "comment-hide-image.",
      [1],
      "data-v-7acbd3a7:before{background:url(https://st.gtimg.com/design/61571ebd1761dade49e2354e70e78bb9.svg) no-repeat;background-position:50%;background-size:cover;content:\x22\x22;display:inline-block;height:.29333333333333333rem;margin-right:.05333333333333334rem;width:.37333333333333335rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "comment-hide-image.",
      [1],
      "isDynamic.",
      [1],
      "data-v-7acbd3a7:before{background:url(https://st.gtimg.com/design/e336f57539549ae3a87a95254931a37f.svg) no-repeat;height:.37333333333333335rem;margin-bottom:-.05333333333333334rem;width:.37333333333333335rem}\n.",
      [1],
      "mod-show-content\x3ewx-span.",
      [1],
      "link.",
      [1],
      "data-v-7acbd3a7:first-child,.",
      [1],
      "mod-show-content\x3ewx-span.",
      [1],
      "plain.",
      [1],
      "data-v-7acbd3a7:first-child{margin-left:0}\n.",
      [1],
      "mod-show-content.",
      [1],
      "disabled .",
      [1],
      "link.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content.",
      [1],
      "disabled.",
      [1],
      "data-v-7acbd3a7{color:#7a8499!important}\n.",
      [1],
      "mod-show-content.",
      [1],
      "short-content-additional.",
      [1],
      "data-v-7acbd3a7{padding:0 0 .06666666666666667rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "data-v-7acbd3a7{-webkit-tap-highlight-color:transparent!important;color:#4774b3;display:inline;font-size:.4266666666666667rem;margin-right:.05333333333333334rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "noClick.",
      [1],
      "data-v-7acbd3a7{color:#000}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link [class*\x3d\x22 icon-\x22].",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link [class^\x3dsq-icon-].",
      [1],
      "data-v-7acbd3a7{font-size:.37333333333333335rem;margin-right:.05333333333333334rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "hyperLink .",
      [1],
      "sq-icon-hyperIcon.",
      [1],
      "data-v-7acbd3a7{background-position:0;background-repeat:no-repeat;background-size:contain;display:inline-block}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-at.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-bk.",
      [1],
      "data-v-7acbd3a7:before,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-gegu.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-hongniu.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-huati.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-lianjie.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-niu.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-peitu.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-pinglun.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-sangedian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-xuangu.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-zhibo.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-zhuanfa.",
      [1],
      "data-v-7acbd3a7{font-size:.37333333333333335rem;margin-right:.05333333333333334rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-hongniu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e908\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-niu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e90d\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-peitu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e902\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-zhibo.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e905\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-at.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e900\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-gegu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e901\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-huati.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e903\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-lianjie.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e904\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-pinglun.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e906\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-sangedian.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e907\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-xuangu.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e909\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-zhuanfa.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e90a\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "link .",
      [1],
      "sq-icon-bk.",
      [1],
      "data-v-7acbd3a7:before{content:\x22\\e901\x22}\n.",
      [1],
      "mod-show-content .",
      [1],
      "plain.",
      [1],
      "data-v-7acbd3a7{font-size:.4266666666666667rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "plain.",
      [1],
      "data-v-7acbd3a7:first-child{margin-left:0}\n.",
      [1],
      "mod-show-comment-item .",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-comment-item .",
      [1],
      "mod-show-content .",
      [1],
      "plain.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "plain-comment-mp.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-turn .",
      [1],
      "mod-show-content .",
      [1],
      "link.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-turn .",
      [1],
      "mod-show-content .",
      [1],
      "plain.",
      [1],
      "data-v-7acbd3a7{font-size:.37333333333333335rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "plain-br.",
      [1],
      "data-v-7acbd3a7{display:block}\n.",
      [1],
      "mod-show-content.",
      [1],
      "disabled.",
      [1],
      "data-v-7acbd3a7{color:#262e40}\n.",
      [1],
      "mod-show-content.",
      [1],
      "isDetail.",
      [1],
      "data-v-7acbd3a7{display:inline}\n.",
      [1],
      "mod-show-content.",
      [1],
      "is-mp-square.",
      [1],
      "data-v-7acbd3a7{max-height:2.56rem;overflow:hidden}\n.",
      [1],
      "mod-show-content.",
      [1],
      "is-mp-comment.",
      [1],
      "data-v-7acbd3a7{max-height:2.24rem;overflow:hidden}\n.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{background:#171d28!important}\n.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7{background:linear-gradient(90deg,rgba(23,29,40,0),#171d28)}\n.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{background:#12161f!important}\n.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7{background:linear-gradient(90deg,rgba(18,22,31,0),#12161f)}\n.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{display:-webkit-flex;display:flex;-webkit-flex-shrink:0;flex-shrink:0}\n.",
      [1],
      "mod-show-content .",
      [1],
      "black .",
      [1],
      "show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "dark .",
      [1],
      "show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "fund-black .",
      [1],
      "show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content wx-html.",
      [1],
      "zxg_black .",
      [1],
      "show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7{color:#262e40}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "data-v-7acbd3a7{bottom:0;color:#5f86bd;position:absolute;right:0;z-index:1}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{background-color:#fff;display:-webkit-flex;display:flex;-webkit-flex-shrink:0;flex-shrink:0;font-size:.4266666666666667rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7{color:#262e40}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "isFolded.",
      [1],
      "data-v-7acbd3a7{-webkit-align-items:flex-start;align-items:flex-start;display:-webkit-flex;display:flex}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "isFolded .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7{display:inline-block;height:.5866666666666667rem;width:.6666666666666666rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{background-color:#fff;font-size:.4266666666666667rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7{background:linear-gradient(90deg,hsla(0,0%,100%,0),#fff)}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{font-size:.37333333333333335rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{background:linear-gradient(180deg,#f5f6fa,#fafafc);font-size:.37333333333333335rem}\n.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,.",
      [1],
      "mod-show-content .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7{background:linear-gradient(90deg,rgba(245,246,250,0),#f5f6fa)}\n[data-st-theme\x3dblack] .",
      [1],
      "mod-show-content .",
      [1],
      "plain.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "mod-show-content .",
      [1],
      "plain.",
      [1],
      "data-v-7acbd3a7{color:var(--color-heavygray)}\n[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "data-v-7acbd3a7{--gradient-start:rgba(23,29,40,.3);--comment-shadow-box-gradient-start:rgba(23,29,40,.3);--comment-shadow-box-gradient-end:#171d28}\n[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{background-color:var(--fill-content-layer)}\n[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7{background:linear-gradient(90deg,var(--gradient-start) 0,var(--fill-content-layer) 100%)}\n[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7acbd3a7{background:var(--color-card)}\n[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3dblack] .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7acbd3a7{background:linear-gradient(90deg,var(--comment-shadow-box-gradient-start) 0,var(--comment-shadow-box-gradient-end) 100%)}\n[data-st-theme\x3dblack] .",
      [1],
      "show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7,[data-st-theme\x3ddark] .",
      [1],
      "show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7acbd3a7{color:var(--color-heavygray)}\n",
    ],
    "Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/newsSbg/@tencent/stock-sq/src/source/shortContent/index.wxss:1:31847)",
    {
      path: "./pages/newsSbg/@tencent/stock-sq/src/source/shortContent/index.wxss",
    }
  );
}
