$gwx21_XC_8 = (function (
  _,
  _v,
  _n,
  _p,
  _s,
  _wp,
  _wl,
  $gwn,
  $gwl,
  $gwh,
  wh,
  $gstack,
  $gwrt,
  gra,
  grb,
  TestTest,
  wfor,
  _ca,
  _da,
  _r,
  _rz,
  _o,
  _oz,
  _1,
  _1z,
  _2,
  _2z,
  _m,
  _mz,
  nv_getDate,
  nv_getRegExp,
  nv_console,
  nv_parseInt,
  nv_parseFloat,
  nv_isNaN,
  nv_isFinite,
  nv_decodeURI,
  nv_decodeURIComponent,
  nv_encodeURI,
  nv_encodeURIComponent,
  $gdc,
  nv_JSON,
  _af,
  _gv,
  _ai,
  _grp,
  _gd,
  _gapi,
  $ixc,
  _ic,
  _w,
  _ev,
  _tsd
) {
  return function (path, global) {
    if (typeof global === "undefined") {
      if (typeof __GWX_GLOBAL__ === "undefined") global = {};
      else global = __GWX_GLOBAL__;
    }
    if (typeof __WXML_GLOBAL__ === "undefined") {
      __WXML_GLOBAL__ = {};
    }
    __WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
    var e_ = {};
    if (typeof global.entrys === "undefined") global.entrys = {};
    e_ = global.entrys;
    var d_ = {};
    if (typeof global.defines === "undefined") global.defines = {};
    d_ = global.defines;
    var f_ = {};
    if (typeof global.modules === "undefined") global.modules = {};
    f_ = global.modules || {};
    var p_ = {};
    __WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {};
    __WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
    __WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
    var z = __WXML_GLOBAL__.ops_set.$gwx21_XC_8 || [];
    function gz$gwx21_XC_8_1() {
      if (__WXML_GLOBAL__.ops_cached.$gwx21_XC_8_1)
        return __WXML_GLOBAL__.ops_cached.$gwx21_XC_8_1;
      __WXML_GLOBAL__.ops_cached.$gwx21_XC_8_1 = [];
      (function (z) {
        var a = 11;
        function Z(ops) {
          z.push(ops);
        }
        Z([[7], [3, "a"]]);
        Z([[7], [3, "f"]]);
        Z([
          [4],
          [
            [5],
            [
              [5],
              [
                [5],
                [
                  [5],
                  [[5], [[5], [1, "_span"]], [1, "data-v-7c900e3e"]],
                  [1, "mod-cmp"],
                ],
                [[7], [3, "c"]],
              ],
              [[7], [3, "d"]],
            ],
            [[7], [3, "e"]],
          ],
        ]);
        Z([a, [[7], [3, "b"]]]);
      })(__WXML_GLOBAL__.ops_cached.$gwx21_XC_8_1);
      return __WXML_GLOBAL__.ops_cached.$gwx21_XC_8_1;
    }
    function gz$gwx21_XC_8_2() {
      if (__WXML_GLOBAL__.ops_cached.$gwx21_XC_8_2)
        return __WXML_GLOBAL__.ops_cached.$gwx21_XC_8_2;
      __WXML_GLOBAL__.ops_cached.$gwx21_XC_8_2 = [];
      (function (z) {
        var a = 11;
        function Z(ops) {
          z.push(ops);
        }
        Z([
          [4],
          [
            [5],
            [
              [5],
              [
                [5],
                [[5], [[5], [1, "_div"]], [1, "data-v-7bc09ac2"]],
                [1, "mod-show-more"],
              ],
              [[7], [3, "k"]],
            ],
            [[7], [3, "l"]],
          ],
        ]);
        Z([
          [2, "!"],
          [[7], [3, "m"]],
        ]);
        Z([3, "showMore"]);
        Z([[7], [3, "a"]]);
        Z([3, "_i shadow-box data-v-7bc09ac2"]);
        Z([3, " "]);
        Z([[7], [3, "b"]]);
        Z([[7], [3, "e"]]);
        Z([
          [4],
          [
            [5],
            [
              [5],
              [[5], [[5], [1, "_span"]], [1, "data-v-7bc09ac2"]],
              [1, "text"],
            ],
            [[7], [3, "f"]],
          ],
        ]);
        Z([3, "_span dian data-v-7bc09ac2"]);
        Z([
          [2, "+"],
          [1, "color:"],
          [[7], [3, "c"]],
        ]);
        Z([3, "..."]);
        Z([3, "_span fold-text data-v-7bc09ac2"]);
        Z([a, [[7], [3, "d"]]]);
        Z([[7], [3, "g"]]);
        Z([[7], [3, "i"]]);
        Z([
          [4],
          [
            [5],
            [
              [5],
              [[5], [[5], [1, "_span"]], [1, "data-v-7bc09ac2"]],
              [1, "text"],
            ],
            [[7], [3, "j"]],
          ],
        ]);
        Z([3, "_span data-v-7bc09ac2"]);
        Z([a, [[7], [3, "h"]]]);
      })(__WXML_GLOBAL__.ops_cached.$gwx21_XC_8_2);
      return __WXML_GLOBAL__.ops_cached.$gwx21_XC_8_2;
    }
    __WXML_GLOBAL__.ops_set.$gwx21_XC_8 = z;
    __WXML_GLOBAL__.ops_init.$gwx21_XC_8 = true;
    var x = [
      "./pages/newsSbg/@tencent/stock-sq/src/source/itemCmp/index.wxml",
      "./pages/newsSbg/@tencent/stock-sq/src/source/showMore/index.wxml",
    ];
    d_[x[0]] = {};
    var m0 = function (e, s, r, gg) {
      var z = gz$gwx21_XC_8_1();
      var l7U = _v();
      _(r, l7U);
      if (_oz(z, 0, e, s, gg)) {
        l7U.wxVkey = 1;
        var a8U = _mz(z, "label", ["catchtap", 1, "class", 1], [], e, s, gg);
        var t9U = _oz(z, 3, e, s, gg);
        _(a8U, t9U);
        _(l7U, a8U);
      }
      l7U.wxXCkey = 1;
      return r;
    };
    e_[x[0]] = { f: m0, j: [], i: [], ti: [], ic: [] };
    d_[x[1]] = {};
    var m1 = function (e, s, r, gg) {
      var z = gz$gwx21_XC_8_2();
      var bAV = _mz(
        z,
        "view",
        ["class", 0, "hidden", 1, "ref", 1],
        [],
        e,
        s,
        gg
      );
      var oBV = _v();
      _(bAV, oBV);
      if (_oz(z, 3, e, s, gg)) {
        oBV.wxVkey = 1;
        var fEV = _n("view");
        _rz(z, fEV, "class", 4, e, s, gg);
        var cFV = _oz(z, 5, e, s, gg);
        _(fEV, cFV);
        _(oBV, fEV);
      }
      var xCV = _v();
      _(bAV, xCV);
      if (_oz(z, 6, e, s, gg)) {
        xCV.wxVkey = 1;
        var hGV = _mz(z, "label", ["catchtap", 7, "class", 1], [], e, s, gg);
        var oHV = _mz(z, "label", ["class", 9, "style", 1], [], e, s, gg);
        var cIV = _oz(z, 11, e, s, gg);
        _(oHV, cIV);
        _(hGV, oHV);
        var oJV = _n("label");
        _rz(z, oJV, "class", 12, e, s, gg);
        var lKV = _oz(z, 13, e, s, gg);
        _(oJV, lKV);
        _(hGV, oJV);
        _(xCV, hGV);
      }
      var oDV = _v();
      _(bAV, oDV);
      if (_oz(z, 14, e, s, gg)) {
        oDV.wxVkey = 1;
        var aLV = _mz(z, "label", ["catchtap", 15, "class", 1], [], e, s, gg);
        var tMV = _n("label");
        _rz(z, tMV, "class", 17, e, s, gg);
        var eNV = _oz(z, 18, e, s, gg);
        _(tMV, eNV);
        _(aLV, tMV);
        _(oDV, aLV);
      }
      oBV.wxXCkey = 1;
      xCV.wxXCkey = 1;
      oDV.wxXCkey = 1;
      _(r, bAV);
      return r;
    };
    e_[x[1]] = { f: m1, j: [], i: [], ti: [], ic: [] };
    if (path && e_[path]) {
      outerGlobal.__wxml_comp_version__ = 0.02;
      return function (env, dd, global) {
        $gwxc = 0;
        var root = { tag: "wx-page" };
        root.children = [];
        g = "$gwx21_XC_8";
        var main = e_[path].f;
        if (typeof global === "undefined") global = {};
        global.f = $gdc(f_[path], "", 1);
        if (
          typeof outerGlobal.__webview_engine_version__ != "undefined" &&
          outerGlobal.__webview_engine_version__ + 1e-6 >= 0.02 + 1e-6 &&
          outerGlobal.__mergeData__
        ) {
          env = outerGlobal.__mergeData__(env, dd);
        }
        try {
          main(env, {}, root, global);
          _tsd(root);
          if (
            typeof outerGlobal.__webview_engine_version__ == "undefined" ||
            outerGlobal.__webview_engine_version__ + 1e-6 < 0.01 + 1e-6
          ) {
            return _ev(root);
          }
        } catch (err) {
          console.log(err);
        }
        g = "";
        return root;
      };
    }
  };
})(
  __g.a,
  __g.b,
  __g.c,
  __g.d,
  __g.e,
  __g.f,
  __g.g,
  __g.h,
  __g.i,
  __g.j,
  __g.k,
  __g.l,
  __g.m,
  __g.n,
  __g.o,
  __g.p,
  __g.q,
  __g.r,
  __g.s,
  __g.t,
  __g.u,
  __g.v,
  __g.w,
  __g.x,
  __g.y,
  __g.z,
  __g.A,
  __g.B,
  __g.C,
  __g.D,
  __g.E,
  __g.F,
  __g.G,
  __g.H,
  __g.I,
  __g.J,
  __g.K,
  __g.L,
  __g.M,
  __g.N,
  __g.O,
  __g.P,
  __g.Q,
  __g.R,
  __g.S,
  __g.T,
  __g.U,
  __g.V,
  __g.W,
  __g.X,
  __g.Y,
  __g.Z,
  __g.aa
);
if (__vd_version_info__.delayedGwx || false) $gwx21_XC_8();
if (__vd_version_info__.delayedGwx)
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/itemCmp/index.wxml"
  ] = [
    $gwx21_XC_8,
    "./pages/newsSbg/@tencent/stock-sq/src/source/itemCmp/index.wxml",
  ];
else
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/itemCmp/index.wxml"
  ] = $gwx21_XC_8(
    "./pages/newsSbg/@tencent/stock-sq/src/source/itemCmp/index.wxml"
  );
if (__vd_version_info__.delayedGwx)
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/showMore/index.wxml"
  ] = [
    $gwx21_XC_8,
    "./pages/newsSbg/@tencent/stock-sq/src/source/showMore/index.wxml",
  ];
else
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/showMore/index.wxml"
  ] = $gwx21_XC_8(
    "./pages/newsSbg/@tencent/stock-sq/src/source/showMore/index.wxml"
  );

var noCss =
  typeof __vd_version_info__ !== "undefined" &&
  __vd_version_info__.noCss === true;
if (!noCss) {
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/itemCmp/index.wxss"
  ] = setCssToHead(
    [
      ".",
      [1],
      "mod-cmp.",
      [1],
      "hasIcon.",
      [1],
      "data-v-7c900e3e{background-image:url(https://mat1.gtimg.com/finance/images/stock/p/community/comItem/CMP/hyperIcon-active.svg);background-position:0;background-repeat:no-repeat;background-size:.4266666666666667rem .4266666666666667rem;padding-left:.48rem}\n.",
      [1],
      "mod-cmp.",
      [1],
      "disabled.",
      [1],
      "data-v-7c900e3e{background-image:url(https://mat1.gtimg.com/finance/images/stock/p/community/comItem/CMP/hyperIcon-disabled.svg);color:#262e40!important}\n.",
      [1],
      "mod-cmp.",
      [1],
      "activity.",
      [1],
      "data-v-7c900e3e{background-image:url(https://dlied5.qq.com/zixuangu/pkg/community/b3fa4938f3a5fcfcd270bb6726796226.png)}\n",
    ],
    undefined,
    { path: "./pages/newsSbg/@tencent/stock-sq/src/source/itemCmp/index.wxss" }
  );
  __wxAppCode__[
    "pages/newsSbg/@tencent/stock-sq/src/source/showMore/index.wxss"
  ] = setCssToHead(
    [
      ".",
      [1],
      "mod-show-more.",
      [1],
      "data-v-7bc09ac2{--gradient-start:hsla(0,0%,100%,0);--comment-shadow-box-gradient-start:rgba(245,246,250,0);--comment-shadow-box-gradient-end:#f5f6fa}\n.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2{background:#171d28!important}\n.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2{background:linear-gradient(90deg,rgba(23,29,40,0),#171d28)}\n.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2{background:#12161f!important}\n.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2{background:linear-gradient(90deg,rgba(18,22,31,0),#12161f)}\n.",
      [1],
      "black .",
      [1],
      "mod-show-more .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2{display:-webkit-flex;display:flex;-webkit-flex-shrink:0;flex-shrink:0}\n.",
      [1],
      "black .",
      [1],
      "mod-show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "dark .",
      [1],
      "mod-show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "fund-black .",
      [1],
      "mod-show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,wx-html.",
      [1],
      "zxg_black .",
      [1],
      "mod-show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2{color:#262e40}\n.",
      [1],
      "mod-show-more.",
      [1],
      "data-v-7bc09ac2{color:#5f86bd;display:inline-block;position:absolute;right:0;z-index:1}\n.",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2{background-color:#fff}\n.",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2{font-size:.4266666666666667rem}\n.",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2{background:linear-gradient(90deg,hsla(0,0%,100%,0),#fff)}\n.",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "fold-text.",
      [1],
      "data-v-7bc09ac2{font-size:.37333333333333335rem}\n.",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2{background:linear-gradient(180deg,#f5f6fa,#fafafc)}\n.",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,.",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2{background:linear-gradient(90deg,rgba(245,246,250,0),#f5f6fa)}\n.",
      [1],
      "mod-show-more wx-i.",
      [1],
      "data-v-7bc09ac2{display:none}\n.",
      [1],
      "mod-show-more .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2{display:-webkit-flex;display:flex;-webkit-flex-shrink:0;flex-shrink:0}\n.",
      [1],
      "mod-show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2{color:#262e40}\n.",
      [1],
      "mod-show-more.",
      [1],
      "isFolded.",
      [1],
      "data-v-7bc09ac2{-webkit-align-items:flex-start;align-items:flex-start;display:-webkit-flex;display:flex}\n.",
      [1],
      "mod-show-more.",
      [1],
      "isFolded wx-i.",
      [1],
      "data-v-7bc09ac2{display:block;height:.5866666666666667rem;width:.6666666666666666rem}\n[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "data-v-7bc09ac2{--gradient-start:rgba(23,29,40,.3);--comment-shadow-box-gradient-start:rgba(23,29,40,.3);--comment-shadow-box-gradient-end:#171d28}\n[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2{background-color:var(--fill-content-layer)}\n[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "desc .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "long .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "reply .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "short .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turn .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnLog .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnNews .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2{background:linear-gradient(90deg,var(--gradient-start) 0,var(--fill-content-layer) 100%)}\n[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "text.",
      [1],
      "data-v-7bc09ac2{background:var(--color-card)}\n[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "comment .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more.",
      [1],
      "turnShort .",
      [1],
      "shadow-box.",
      [1],
      "data-v-7bc09ac2{background:linear-gradient(90deg,var(--comment-shadow-box-gradient-start) 0,var(--comment-shadow-box-gradient-end) 100%)}\n[data-st-theme\x3dblack] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2,[data-st-theme\x3ddark] .",
      [1],
      "detail-portrait .",
      [1],
      "mod-show-more .",
      [1],
      "text .",
      [1],
      "dian.",
      [1],
      "data-v-7bc09ac2{color:var(--color-heavygray)}\n",
    ],
    "Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.(./pages/newsSbg/@tencent/stock-sq/src/source/showMore/index.wxss:1:14794)",
    { path: "./pages/newsSbg/@tencent/stock-sq/src/source/showMore/index.wxss" }
  );
}
