var E,
  T,
  A,
  O,
  _,
  N,
  L,
  R,
  I,
  D,
  S,
  C,
  U,
  e,
  t,
  P,
  o,
  r,
  B,
  M,
  p,
  s,
  x,
  Y,
  G,
  F,
  W,
  n,
  V,
  K,
  H,
  i,
  a,
  d,
  u,
  l = require("../@babel/runtime/helpers/defineProperty");
require("../app.js");
var X = (function (E) {
    return (E.NORMAL = "0"), (E.MARGIN = "1"), (E.UNKNOWN = "99"), E;
  })(X || {}),
  c = {
    0: "sz",
    1: "sh",
    12: "nq",
    13: "bj",
    14: "hk",
    SA: "0",
    HA: "1",
    NQ: "12",
    BJ: "13",
    HK: "14",
  },
  v = {
    STOCK: "0",
    DEBT: "1",
    BOND: "2",
    NEWSTOCK: "3",
    DEPOSITE: "4",
    ALLOT: "5",
    DUOTIANQI: "6",
    ALLOCATE_DEBT: "7",
    BALANCE: "8",
  },
  Q = [v.DUOTIANQI, v.BALANCE, v.DEBT],
  f =
    (l((E = {}), "-1", "未知"),
    l(E, "0", "未提交"),
    l(E, "1", "已提交"),
    l(E, "2", "全部成交"),
    l(E, "3", "部分成交"),
    l(E, "4", "未成交"),
    l(E, "5", "全部撤单"),
    l(E, "6", "募集失败"),
    E),
  g = {
    LOT_WINNING: "1",
    WAITING_NUMBER: "2",
    WAITING_LOT: "3",
    NOT_LOT: "4",
    INVALID: "5",
    APPLYING: "6",
    UNKOWN: "7",
    IS_COMPLETED: "8",
  },
  b =
    (l((T = {}), "-1", "未知"),
    l(T, "0", "未提交"),
    l(T, "1", "已提交"),
    l(T, "6", "废单"),
    T),
  m =
    (l((A = {}), g.LOT_WINNING, "中签"),
    l(A, g.WAITING_NUMBER, "待配号"),
    l(A, g.WAITING_LOT, "待抽签"),
    l(A, g.NOT_LOT, "未中签"),
    l(A, g.INVALID, "无效"),
    l(A, g.APPLYING, "申购中"),
    l(A, g.UNKOWN, "未知"),
    l(A, g.IS_COMPLETED, "认购完成"),
    A),
  $ = {
    LIVE: "1",
    RECEIVE_TODAY: "2",
    INTERST_RECEIVED: "3",
    PRE_PURCHASE: "4",
  },
  h =
    (l((O = {}), $.LIVE, "生息中"),
    l(O, $.RECEIVE_TODAY, "今日到账"),
    l(O, $.INTERST_RECEIVED, "本息到账"),
    l(O, $.PRE_PURCHASE, "提前回购"),
    O),
  q =
    (l((_ = {}), v.STOCK, "股"),
    l(_, v.DEBT, "元"),
    l(_, v.BOND, "张"),
    l(_, v.ALLOT, "股"),
    l(_, v.NEWSTOCK, "股"),
    l(_, v.DEPOSITE, ""),
    l(_, v.DUOTIANQI, "元"),
    l(_, v.ALLOCATE_DEBT, "张"),
    l(_, v.BALANCE, "元"),
    _),
  j = {
    BUY: "1",
    SELL: "2",
    ALLOT: "18",
    LEND: "20",
    AFTER_BUY: "23",
    AFTER_SELL: "24",
    ETF_SUBSCRIBE: "25",
    COLLATERAL_BUY: "26",
    COLLATERAL_SELL: "27",
    MARGIN_BUY: "28",
    SHORT_SELL: "29",
    BUY_AND_COVER: "30",
    REPURCHASE_AGREEMENT: "31",
    COLLATERAL_TRANSFER_IN: "32",
    COLLATERAL_TRANSFER_OUT: "33",
    REPURCHASE: "34",
    AFTER_COLLATERAL_BUY: "23",
    AFTER_COLLATERAL_SELL: "24",
    REST_STOCK_TRANSFER: "37",
    WEALTH_MANAGEMEN: "38",
    NEWSTOCK_BUY: "15",
    AUO_BUY: "40",
    AUO_SELL: "41",
    ELO_BUY: "1",
    ELO_SELL: "2",
    ODD_LOT_ELO_BUY: "42",
    ODD_LOT_ELO_SELL: "43",
  },
  k = l({}, j.ETF_SUBSCRIBE, "份"),
  y =
    (l(
      (C = {}),
      v.STOCK,
      (l((N = {}), j.BUY, "买入"),
      l(N, j.SELL, "卖出"),
      l(N, j.AFTER_BUY, "买入"),
      l(N, j.AFTER_SELL, "卖出"),
      l(N, j.ETF_SUBSCRIBE, "认购"),
      l(N, j.COLLATERAL_BUY, "买入"),
      l(N, j.COLLATERAL_SELL, "卖出"),
      l(N, j.MARGIN_BUY, "买入"),
      l(N, j.SHORT_SELL, "卖出"),
      l(N, j.BUY_AND_COVER, "买入"),
      l(N, j.REPURCHASE_AGREEMENT, "卖出"),
      l(N, j.COLLATERAL_TRANSFER_IN, "转入"),
      l(N, j.COLLATERAL_TRANSFER_OUT, "转出"),
      l(N, j.REPURCHASE, "还券"),
      l(N, j.AFTER_COLLATERAL_BUY, "买入"),
      l(N, j.AFTER_COLLATERAL_SELL, "卖出"),
      l(N, j.REST_STOCK_TRANSFER, "划转"),
      l(N, j.NEWSTOCK_BUY, "打新"),
      l(N, j.AUO_BUY, "买入"),
      l(N, j.AUO_SELL, "卖出"),
      l(N, j.ELO_BUY, "买入"),
      l(N, j.ELO_SELL, "卖出"),
      l(N, j.ODD_LOT_ELO_BUY, "买入"),
      l(N, j.ODD_LOT_ELO_SELL, "卖出"),
      N)
    ),
    l(
      C,
      v.DEBT,
      (l((L = {}), j.BUY, "理财"),
      l(L, j.SELL, "理财"),
      l(L, j.LEND, "理财"),
      L)
    ),
    l(C, v.BOND, (l((R = {}), j.BUY, "买入"), l(R, j.SELL, "卖出"), R)),
    l(C, v.NEWSTOCK, (l((I = {}), j.BUY, "申购"), l(I, j.SELL, "申购"), I)),
    l(C, v.DEPOSITE, (l((D = {}), j.BUY, "托管"), l(D, j.SELL, "托管"), D)),
    l(C, v.ALLOT, l({}, j.ALLOT, "配股")),
    l(
      C,
      v.DUOTIANQI,
      (l((S = {}), j.BUY, "理财"),
      l(S, j.SELL, "理财"),
      l(S, j.WEALTH_MANAGEMEN, "理财"),
      S)
    ),
    l(C, v.BALANCE, l({}, j.WEALTH_MANAGEMEN, "理财")),
    l(C, v.ALLOCATE_DEBT, l({}, j.ALLOT, "配股缴款")),
    C),
  J =
    (l((U = {}), j.COLLATERAL_BUY, "担保品买入"),
    l(U, j.COLLATERAL_SELL, "担保品卖出"),
    l(U, j.MARGIN_BUY, "融资买入"),
    l(U, j.SHORT_SELL, "融券卖出"),
    l(U, j.BUY_AND_COVER, "买券还券"),
    l(U, j.REPURCHASE_AGREEMENT, "卖券还款"),
    l(U, j.COLLATERAL_TRANSFER_IN, "担保品转入"),
    l(U, j.COLLATERAL_TRANSFER_OUT, "担保品转出"),
    l(U, j.REPURCHASE, "直接还券"),
    l(U, j.AFTER_COLLATERAL_BUY, "担保品买入"),
    l(U, j.AFTER_COLLATERAL_SELL, "担保品卖出"),
    l(U, j.REST_STOCK_TRANSFER, "余券划转"),
    U),
  w = {
    WIP: "0",
    PARTLY: "1",
    PROCESSED: "2",
    NOTTRADEED: "3",
    REVOKING: "5",
    REVOKINGPARTLY: "6",
    REVOKEDPARTLY: "7",
    REVOKED: "8",
    FAILED: "9",
    WATITING: "10",
  },
  z = {
    COMMIT: "1",
    COMMITED: "2",
    COMFIRMED: "3",
    COMMITED_NOT_DRAWN: "4",
    WITHDRAW_COMMITTING: "5",
    WITHDRAW_FINISHED: "8",
    FAILED: "9",
  },
  Z =
    (l((e = {}), v.STOCK, w),
    l(e, v.BOND, w),
    l(e, v.DEBT, w),
    l(e, v.ALLOT, {
      NO_COMMIT: "1",
      COMMITED: "2",
      COMFIRMED: "3",
      COMMITED_NOT_DRAWN: "4",
      WITHDRAW_COMMITTING: "5",
      WITHDRAW_FINISHED: "8",
    }),
    l(e, v.DUOTIANQI, w),
    l(e, v.ALLOCATE_DEBT, z),
    e),
  EE =
    (l(
      (p = {}),
      v.STOCK,
      (l((t = {}), Z[v.STOCK].WIP, "交易中"),
      l(t, Z[v.STOCK].PARTLY, "部分成交"),
      l(t, Z[v.STOCK].PROCESSED, "全部成交"),
      l(t, Z[v.STOCK].NOTTRADEED, "未成交"),
      l(t, Z[v.STOCK].REVOKING, "撤单中"),
      l(t, Z[v.STOCK].REVOKINGPARTLY, "部分撤单中"),
      l(t, Z[v.STOCK].REVOKEDPARTLY, "部成部撤"),
      l(t, Z[v.STOCK].REVOKED, "全部撤单"),
      l(t, Z[v.STOCK].FAILED, "委托无效"),
      l(t, Z[v.STOCK].WATITING, "等待开市"),
      t)
    ),
    l(
      p,
      v.DEBT,
      (l((P = {}), Z[v.DEBT].WIP, "交易中"),
      l(P, Z[v.DEBT].PARTLY, "部分成交"),
      l(P, Z[v.DEBT].PROCESSED, "全部成交"),
      l(P, Z[v.DEBT].NOTTRADEED, "未成交"),
      l(P, Z[v.DEBT].REVOKING, "撤单中"),
      l(P, Z[v.DEBT].REVOKINGPARTLY, "部分撤单中"),
      l(P, Z[v.DEBT].REVOKEDPARTLY, "部成部撤"),
      l(P, Z[v.DEBT].REVOKED, "全部撤单"),
      l(P, Z[v.DEBT].FAILED, "委托无效"),
      l(P, Z[v.DEBT].WATITING, "等待开市"),
      P)
    ),
    l(
      p,
      v.BOND,
      (l((o = {}), Z[v.BOND].WIP, "交易中"),
      l(o, Z[v.BOND].PARTLY, "部分成交"),
      l(o, Z[v.BOND].PROCESSED, "全部成交"),
      l(o, Z[v.BOND].NOTTRADEED, "未成交"),
      l(o, Z[v.BOND].REVOKING, "撤单中"),
      l(o, Z[v.BOND].REVOKINGPARTLY, "部分撤单中"),
      l(o, Z[v.BOND].REVOKEDPARTLY, "部成部撤"),
      l(o, Z[v.BOND].REVOKED, "全部撤单"),
      l(o, Z[v.BOND].FAILED, "委托无效"),
      l(o, Z[v.BOND].WATITING, "等待开市"),
      o)
    ),
    l(
      p,
      v.ALLOT,
      (l((r = {}), Z[v.ALLOT].NO_COMMIT, "已提交"),
      l(r, Z[v.ALLOT].COMMITED, "等待确认"),
      l(r, Z[v.ALLOT].COMFIRMED, "全部成交"),
      l(r, Z[v.ALLOT].COMMITED_NOT_DRAWN, "等待确认"),
      l(r, Z[v.ALLOT].WITHDRAW_COMMITTING, "撤单中"),
      l(r, Z[v.ALLOT].WITHDRAW_FINISHED, "已撤单"),
      r)
    ),
    l(
      p,
      v.DUOTIANQI,
      (l((B = {}), Z[v.DUOTIANQI].WIP, "委托中"),
      l(B, Z[v.DUOTIANQI].PROCESSED, "全部成交"),
      l(B, Z[v.DUOTIANQI].FAILED, "无效单"),
      B)
    ),
    l(
      p,
      v.ALLOCATE_DEBT,
      (l((M = {}), Z[v.ALLOCATE_DEBT].COMMIT, "委托中"),
      l(M, Z[v.ALLOCATE_DEBT].COMMITED, "等待确认"),
      l(M, Z[v.ALLOCATE_DEBT].COMFIRMED, "配债已确认"),
      l(M, Z[v.ALLOCATE_DEBT].COMMITED_NOT_DRAWN, "等待确认"),
      l(M, Z[v.ALLOCATE_DEBT].WITHDRAW_COMMITTING, "撤单中"),
      l(M, Z[v.ALLOCATE_DEBT].WITHDRAW_FINISHED, "已撤单"),
      l(M, Z[v.ALLOCATE_DEBT].FAILED, "委托无效"),
      M)
    ),
    p),
  TE = {
    NORMAL: "0",
    DELISTED: "D",
    SUSPENSION: "S",
    SUSPENDED: "Z",
    UNLIST: "U",
    UNISSUED: "I",
    PURCHASE: "P",
  },
  AE =
    (l((s = {}), TE.DELISTED, "退市"),
    l(s, TE.SUSPENDED, "暂停上市"),
    l(s, TE.SUSPENSION, "停牌"),
    l(s, TE.PURCHASE, "待上市"),
    l(s, TE.UNLIST, "待上市"),
    l(s, TE.UNISSUED, "待发行"),
    l(s, TE.NORMAL, ""),
    s),
  OE =
    (l((x = {}), c.SA, {
      DELISTING_ARRANGEMENT: "J",
      DELISTING_ARRANGEMENT_FD: "R",
    }),
    l(x, c.HA, { DELISTING_ARRANGEMENT: "P" }),
    x),
  _E = {
    NOT_TRADEDAY: "-1",
    NOT_OPEN: "0",
    OPEN_AUCTION: "1",
    MORNING_OPENED: "2",
    SIESTA: "3",
    AFTERNOON_OPENED: "4",
    CLOSE_AUCTION: "5",
    CLOSED: "6",
    PAUSED: "7",
    OPEN_AUCTION_NOT_CANCEL: "8",
    OPEN_AUCTION_DELAY: "9",
    AFTER_PREPARE: "10",
    AFTER_TRADING: "11",
    ALL_DAY_AUCTION: "12",
  },
  NE =
    (l((Y = {}), _E.NOT_TRADEDAY, "休市中"),
    l(Y, _E.NOT_OPEN, "未开市"),
    l(Y, _E.OPEN_AUCTION, "集合竞价"),
    l(Y, _E.MORNING_OPENED, "交易中"),
    l(Y, _E.SIESTA, "午间休市"),
    l(Y, _E.AFTERNOON_OPENED, "交易中"),
    l(Y, _E.CLOSE_AUCTION, "交易中"),
    l(Y, _E.CLOSED, "休市中"),
    l(Y, _E.AFTER_PREPARE, "盘后交易"),
    l(Y, _E.AFTER_TRADING, "盘后交易"),
    l(Y, _E.ALL_DAY_AUCTION, "交易中"),
    Y),
  LE = {
    LIMIT: "1",
    PRICE: "2",
    INVEST: "3",
    GRID: "4",
    TPSL: "5",
    ELO: "6",
    ALO: "7",
    OLO: "8",
  },
  RE =
    (l((G = {}), LE.PRICE, "PriceCondition"),
    l(G, LE.INVEST, "InvestCondition"),
    l(G, LE.GRID, "GridCondition"),
    l(G, LE.TPSL, "TPSLCondition"),
    G),
  IE =
    (l((F = {}), LE.LIMIT, "限价单"),
    l(F, LE.PRICE, "价格条件单"),
    l(F, LE.INVEST, "定期定投单"),
    l(F, LE.GRID, "网格条件单"),
    l(F, LE.TPSL, "止盈止损单"),
    l(F, LE.ELO, "增强限价单"),
    l(F, LE.ALO, "竞价限价单"),
    l(F, LE.OLO, "碎股单"),
    F),
  DE =
    (l((W = {}), LE.ELO, "增强限价"),
    l(W, LE.ALO, "竞价限价"),
    l(W, LE.OLO, "碎股单"),
    W),
  SE =
    (l((n = {}), LE.PRICE, "设置价格条件单"),
    l(n, LE.INVEST, "设置定期定投单"),
    n),
  CE = (l((V = {}), LE.PRICE, "价格条件"), l(V, LE.INVEST, "定期定投"), V),
  UE = [
    { value: LE.LIMIT, text: IE[LE.LIMIT] },
    { value: LE.TPSL, text: IE[LE.TPSL] },
    { value: LE.PRICE, text: IE[LE.PRICE] },
    { value: LE.INVEST, text: IE[LE.INVEST] },
    { value: LE.GRID, text: IE[LE.GRID] },
  ],
  eE = [
    { value: LE.ELO, text: IE[LE.ELO] },
    { value: LE.ALO, text: IE[LE.ALO] },
    { value: LE.OLO, text: IE[LE.OLO] },
  ],
  tE = { TODAY: "1", WEEK: "2", MONTH: "3", YEAR: "4" },
  PE =
    (l((K = {}), tE.TODAY, "当天"),
    l(K, tE.WEEK, "7天"),
    l(K, tE.MONTH, "30天"),
    l(K, tE.YEAR, "1年"),
    K),
  oE =
    (l((H = {}), tE.TODAY, 0),
    l(H, tE.WEEK, 6),
    l(H, tE.MONTH, 29),
    l(H, tE.YEAR, 364),
    H),
  rE = function (E) {
    return Object.keys(E).map(function (T) {
      return { value: T, text: E[T] };
    });
  },
  BE = rE(PE),
  ME = (l((i = {}), j.BUY, "买入"), l(i, j.SELL, "卖出"), i);
rE(ME);
for (
  var pE = { MONTH3: "1", MONTH6: "2", YEAR1: "3", YEAR2: "4" },
    sE =
      (l((a = {}), pE.MONTH3, 89),
      l(a, pE.MONTH6, 179),
      l(a, pE.YEAR1, 364),
      l(a, pE.YEAR2, 729),
      a),
    xE = rE(
      (l((d = {}), pE.MONTH3, "90天"),
      l(d, pE.MONTH6, "半年"),
      l(d, pE.YEAR1, "1年"),
      l(d, pE.YEAR2, "2年"),
      d)
    ),
    YE = [],
    GE = 1;
  GE <= 28;
  GE++
)
  YE.push("".concat(GE, "日"));
var FE = { TRADE_DAY: "1", WEEK: "2", DOUBLE_WEEK: "3", MONTH: "4" },
  WE =
    (l((u = {}), FE.TRADE_DAY, "每交易日"),
    l(u, FE.WEEK, "每周"),
    l(u, FE.DOUBLE_WEEK, "每双周"),
    l(u, FE.MONTH, "每月"),
    u),
  nE = rE(WE),
  VE = (function (E) {
    return (
      (E[(E.complete = 0)] = "complete"),
      (E[(E.pagination = 1)] = "pagination"),
      (E[(E.paginationFail = 2)] = "paginationFail"),
      (E[(E.loading = 3)] = "loading"),
      (E[(E.fail = 4)] = "fail"),
      E
    );
  })(VE || {}),
  KE = (function (E) {
    return (E.STANDARD = "STANDARD"), (E.QUICKTRADE = "QUICKTRADE"), E;
  })(KE || {}),
  HE = (function (E) {
    return (E.normal = "normal"), (E.continueTrade = "continueTrade"), E;
  })(HE || {}),
  iE = (function (E) {
    return (E.sub = "0"), (E.add = "1"), (E.row = "2"), E;
  })(iE || {});
(exports.ACCOUNT_STATE = { NOACCOUNT: "0", HASACCOUNT: "1" }),
  (exports.ACCT_ACTIVE_STATE = { WAITTING: "0", FAILED: "1", SUCCEED: "2" }),
  (exports.ACTION = j),
  (exports.ACTION_TEXT = y),
  (exports.ACTION_UNIT = k),
  (exports.ALLOCATE_DEBT_STATE = z),
  (exports.BALANCE_PRODUCTS = Q),
  (exports.BALANCE_STATE = $),
  (exports.BALANCE_STATE_TEXT = h),
  (exports.BALANCE_STATUS_TEXT = { 0: "已成交", 1: "计息中", 2: "本息待收" }),
  (exports.BANK_ACTIVE_STATE = { WAITTING: "0", FAILED: "1", SUCCEED: "2" }),
  (exports.CHECK_PWD_SCENES = HE),
  (exports.COND_TAB_VALUE = {
    priceCond: "priceCond",
    investCond: "investCond",
    gridCond: "gridCond",
    tpslCond: "tpslCond",
    limitUpCond: "limitUpCond",
    openingSellCond: "openingSellCond",
  }),
  (exports.DATA_AUDIT_STATE = { WAITTING: "0", FAILED: "1", SUCCEED: "2" }),
  (exports.ETFSUBSCRIBE_STATE_FOR_RECORD_TEXT = f),
  (exports.E_ACCOUNT_MODE = X),
  (exports.FACELIVE_TYPE = {
    YOUTU: "1",
    WEIXIN: "2",
    NOTNEED: "3",
    SHANGTANG: "4",
  }),
  (exports.FAIL_REASON_TYPE = { DATA: "0", BANKCARD: "1", ACCOUNT: "2" }),
  (exports.FAIL_TYPE = {
    RECOVER: "recover",
    REOPEN: "reopen",
    BAN: "ban",
    BIND: "bind",
  }),
  (exports.FEE_MODE = { ESTIMATE: "1", SETTLE: "0" }),
  (exports.FIXED_POSITION = ["1", "1/2", "1/3", "1/4"]),
  (exports.FUNDSINFO_ASSET_STATUS = {
    ASSET_EXCEPTION: "-1",
    ASSET_DEFAULT: "0",
    ASSET_REMOVED: "1",
    ASSET_ABNORMAL: "2",
    ASSET_PERFECT: "3",
    ASSET_MISSING: "4",
    ASSET_ABNORMAL_OPEN: "5",
  }),
  (exports.FUND_SHOW_MODE = iE),
  (exports.GGT_ORDER_GROUP_LIST = eE),
  (exports.IDCARD_OCR_TYPE = { BROKER: "0", CREDIT: "1", SHANGTANG: "2" }),
  (exports.IDCARD_SIDE = { FRONT: "front", BACK: "back" }),
  (exports.IDCARD_TIP_TEXT = {
    LOADING: "上传中...",
    SUCCESS: "已上传",
    FAIL: "上传失败",
    WAITING: "等待上传",
  }),
  (exports.INCOME_ALGORITHM_TYPES = { FUND_WEIGHT: "1", MAX_COST: "2" }),
  (exports.INDEPENDENT_PAGE_CONFIG = RE),
  (exports.INTENTION_VIDEO_TYPE = {
    WORDS: "1",
    NUMBER: "2",
    WX_LIVE: "3",
    WX_VIDEO: "4",
    VOICE: "5",
  }),
  (exports.INVEST_MONTH_DAY_LIST = YE),
  (exports.INVEST_ORDER_PERIOD = FE),
  (exports.INVEST_ORDER_PERIOD_LIST = nE),
  (exports.INVEST_ORDER_PERIOD_TEXT = WE),
  (exports.INVEST_ORDER_VALIDATES = pE),
  (exports.INVEST_ORDER_VALIDATES_NUM = sE),
  (exports.INVEST_ORDER_VALIDATE_DAYS = xE),
  (exports.INVEST_TRADE_TIME_LIST = [
    "09:30",
    "10:00",
    "10:30",
    "11:00",
    "13:00",
    "13:30",
    "14:00",
    "14:30",
  ]),
  (exports.INVEST_WEEK_LIST = ["周一", "周二", "周三", "周四", "周五"]),
  (exports.MARGIN_ACTION_DESC = J),
  (exports.MARKET = c),
  (exports.MARKET_STATE = _E),
  (exports.MARKET_STATE_LABEL = NE),
  (exports.MEDIA_STATUS = {
    UNSET: "UNSET",
    UPLOADING: "UPLOADING",
    VERIFY: "VERIFY",
    SUCCESS: "SUCCESS",
    FAIL: "FAIL",
    UNPASS: "UNPASS",
    PREVIEW: "PREVIEW",
    CANCEL: "CANCEL",
    LOADING: "LOADING",
    OUTDATED: "OUTDATED",
    PRERECORD: "PRERECORD",
    RECORDING: "RECORDING",
    RECORDEND: "RECORDEND",
    WAITING: "WAITING",
  }),
  (exports.NEWSTOCK_STATUS = {
    PURCHASE: "P",
    PURCHASE_ENDED: "U",
    PURCHASE_NOT_START: "I",
  }),
  (exports.ORDER_ACTIONS_TEXTS = ME),
  (exports.ORDER_DESC_LABEL = DE),
  (exports.ORDER_PAGE_TITLE = SE),
  (exports.ORDER_POPUP_LIST = UE),
  (exports.ORDER_QUOTE_INFO_LABEL = CE),
  (exports.ORDER_TYPES = LE),
  (exports.ORDER_TYPES_TEXT = IE),
  (exports.ORDER_VALIDATES = tE),
  (exports.ORDER_VALIDATES_NUM = oE),
  (exports.ORDER_VALIDATE_DAYS = BE),
  (exports.PLAYNEW_STATE = g),
  (exports.PLAYNEW_STATE_TEMP_TEXT = b),
  (exports.PLAYNEW_STATE_TEXT = m),
  (exports.PRODUCT_STATE = OE),
  (exports.PageStatus = VE),
  (exports.Quotes = { DROP: "drop", EQUAL: "equal", RISE: "rise" }),
  (exports.RANGE = [
    "固定收益类",
    "权益类",
    "衍生品类",
    "复杂投资类",
    "其他产品",
    "全部",
    "未知",
    "未知",
    "其他",
    "未评测",
    "已过期",
  ]),
  (exports.REGEXP_VALID_ID = /(^\d{15}$)|(^\d{18}$)|(^\d{17}x$)/i),
  (exports.REGX = { ID: /(^\d{18}$)|(^\d{17}(\d|X|x)$)/, MOBILE: /^1\d{10}$/ }),
  (exports.RISK_STOCK = {
    0: "R1低风险",
    1: "R2较低风险",
    2: "R3中风险",
    3: "R4较高风险",
    4: "R5高风险",
    5: "未知",
    6: "未知",
    7: "未知",
    8: "未测评",
    9: "已过期",
  }),
  (exports.STOCK_STATE = TE),
  (exports.STRATEGY = {
    MANUAL: 1,
    LATEST: 2,
    BUY: 3,
    SELL: 4,
    AFTER_CLOSED: 5,
  }),
  (exports.STRATEGY_TEXT = {
    1: "限价",
    2: "跟最新价",
    3: "跟买一价",
    4: "跟卖一价",
    5: "盘后",
  }),
  (exports.TARGET = v),
  (exports.TARGET_UNIT = q),
  (exports.TIPS_STOCK_STATE = AE),
  (exports.TRADE_BASE_STATE = w),
  (exports.TRADE_MATCH_TYPE = {
    NOT_NEED_MATCH: "0",
    NEED_SIGN_MATCH_PRO: "1",
    NEED_SIGN_NOT_MATCH_PRO: "2",
    NEED_LOAD_VIDEO: "3",
    CAN_NOT_BUY: "4",
    RISK_LEVEL_OUTDATED: "5",
    OTHER_REASON: "7",
    NOT_TEST: "8",
    TEST_OUTTIME: "9",
    RISK_LEVEL_NONSTANDARD: "10",
    NO_INVEST_QY: "11",
  }),
  (exports.TRADE_MODE = KE),
  (exports.TRADE_STATE = Z),
  (exports.TRADE_STATE_TEXT = EE),
  (exports.USERSTATE = {
    HASACCOUNT: "0",
    NOACCOUNT: "1",
    VERIFYING: "2",
    HASBUNDLE: "3",
    FAILED: "4",
  }),
  (exports.VIDEO_STATUS = { UNSET: "0", UPLOADED: "1" }),
  (exports.VISIT_QUERY_RESULT = { OK: "0", NOT_FOUND: "1", NOT_SUPPORT: "2" }),
  (exports.VISIT_STATUS = {
    NOTNEED: "-1",
    NOTCALL: "0",
    NOTANSWER: "1",
    PASS: "2",
    NOTPASS: "3",
  });
