require("../app.js"),
  (exports.BOOKING_REPEAT_ERR = "101321182"),
  (exports.CANCEL_BOOKING_REPEAT_ERR = "101321183"),
  (exports.COND_AGE_NOT_MATCH = 51093410),
  (exports.COND_DUPLICATE_STOCK = 1612787023),
  (exports.COND_NO_AUTH = 51093412),
  (exports.COND_RISK_NOT_MATCH = 51093411),
  (exports.DEFAULT = "网络繁忙 请稍后再试"),
  (exports.IDCARD_EXPIRED_UNMATCH = 51088860),
  (exports.IPOBOOKING_INVALID_ORDER_TIME = "101321191"),
  (exports.NETWORK_CHANGE = "网络发生切换，请刷新重试"),
  (exports.NETWORK_DISCONNECT = "网络断开，请检查网络后再试"),
  (exports.NETWORK_INTERRUPTED = "网络中断，请刷新重试"),
  (exports.PASSWORD_CANCEL = "用户取消密码验证"),
  (exports.SHAREHOLDER_NOT_DESIGNATED = 103490146),
  (exports.SHAREHOLDER_NOT_FOUND = 103490151),
  (exports.TIMEOUT = "系统超时 请稍后再试"),
  (exports.TRADE_HIGHRISK_GUOXIN = 103490103),
  (exports.TRADE_NOT_TRADING_TIME = 103490152),
  (exports.TRADE_RISKTEST_UNMATCH = 176250010),
  (exports.TRADE_RISK_TEST_EXPIRED = 103422157),
  (exports.TRADE_RISK_TEST_UNMATCH = 103422156),
  (exports.TRADE_SUBMIT_STOCK_NO_AUTH = 103424135),
  (exports.TRADE_SUBMIT_TIMEOUT = 51079709),
  (exports.TRANSFER_CANCEL = "用户取消转账"),
  (exports.TRANSFER_CLEARTIME =
    "资金晚间结算中，转账服务暂停，请5分钟之后再试"),
  (exports.TRANSFER_NOT_AVAILABLE =
    "券商系统维护中，资金转账暂停服务，请稍后再试"),
  (exports.TRANSFER_PENDING_TOO_MANY = "你当前已有10笔转账中，请稍后再试"),
  (exports.TRANSFER_T1_FAIL = "预约转账T+1失败"),
  (exports.TRANSFER_T1_TIMEOUT = "预约转账T+1失败"),
  (exports.TRANSFER_T2_FAIL = "预约转账T+2失败"),
  (exports.TRANSFER_T2_TIMEOUT = "预约转账T+2失败"),
  (exports.UPDATE_END_CONDITION = 1612787003),
  (exports.USER_CAN_NOT_TRADE_TODAY = 103422127),
  (exports.WRONG_TRANSFER_MODE = "转账模式错误 请稍后再试"),
  (exports.WRONG_TRANSFER_PWDCHECK_TYPE = "转账验密模式错误 请稍后再试"),
  (exports.getBrokerNginxMaintainTip = function (T) {
    return "为提升证券服务质量，".concat(
      (null == T ? void 0 : T.trim()) || "券商平台",
      "将进行系统升级，期间资产查询、开户等服务暂停，您的账户资产处于安全状态。由此造成不便，敬请谅解。"
    );
  });
