require("../app.js"),
  (exports.NEED_TRADE_SESSION = "NEED_TRADE_SESSION"),
  (exports.PASSWORD_COMPLETE = "PASSWORD_COMPLETE"),
  (exports.PLUGIN_NEED_PWD = "PLUGIN_NEED_PWD"),
  (exports.PLUGIN_SHOW_NETWORK_DETECT = "PLUGIN_SHOW_NETWORK_DETECT"),
  (exports.PLUGIN_SHOW_PWD = "PLUGIN_SHOW_PWD"),
  (exports.QUOTES_CLICK_AMOUNT_CHANGE = "QUOTES_CLICK_AMOUNT_CHANGE"),
  (exports.QUOTES_CLICK_PRICE_CHANGE = "QUOTES_CLICK_PRICE_CHANGE");
