require("../app.js"),
  (exports.BIZ_URL_ARGS = [
    "stat",
    "stat_data",
    "console",
    "chrome",
    "debug",
    "channel",
    "channel-popup",
    "remindtype",
    "fromshare",
    "appver",
    "_buildh5ver",
    "hidenav",
    "srcsite",
    "webviewnum",
    "escape",
  ]),
  (exports.CLIENT_URL_ARGS = ["v", "t", "cdn_domain_type"]),
  (exports.MP_INFO = {
    APP_ID: "wx4ffb369b6881ee5e",
    zxgxcx: "wx4ffb369b6881ee5e",
    wzqxcx: "wx4eff699c2e813ab6",
    ORIGIN_ID: "gh_debd46be9dc3",
  });
