var _,
  E,
  T,
  A,
  S,
  I,
  R,
  O,
  N,
  D,
  C,
  e,
  B,
  P,
  L,
  t,
  s,
  U,
  r,
  o,
  p,
  a,
  i,
  K,
  M,
  Y,
  G,
  H,
  F,
  W,
  x,
  n,
  d,
  l,
  c,
  b,
  u,
  V,
  Z,
  g,
  z,
  m,
  y,
  h,
  X,
  w,
  k,
  f,
  v,
  q,
  Q,
  j,
  J,
  $,
  __,
  E_,
  T_,
  A_,
  S_,
  I_,
  R_,
  O_,
  N_,
  D_,
  C_,
  e_,
  B_,
  P_,
  L_,
  t_,
  s_,
  U_,
  r_,
  o_,
  p_,
  a_,
  i_,
  K_,
  M_,
  Y_,
  G_,
  H_,
  F_,
  W_,
  x_,
  n_,
  d_,
  l_,
  c_,
  b_,
  u_,
  V_,
  Z_,
  g_,
  z_,
  m_,
  y_,
  h_,
  X_,
  w_,
  k_,
  f_,
  v_,
  q_,
  Q_,
  j_,
  J_,
  $_,
  _E,
  EE,
  TE,
  AE,
  SE,
  IE,
  RE,
  OE,
  NE,
  DE,
  CE,
  eE,
  BE,
  PE,
  LE,
  tE,
  sE,
  UE,
  rE,
  oE,
  pE,
  aE,
  iE,
  KE,
  ME,
  YE,
  GE,
  HE,
  FE,
  WE,
  xE,
  nE,
  dE,
  lE,
  cE,
  bE,
  uE,
  VE,
  ZE,
  gE,
  zE,
  mE,
  yE,
  hE,
  XE,
  wE,
  kE,
  fE,
  vE,
  qE,
  QE,
  jE,
  JE,
  $E,
  _T,
  ET = require("../@babel/runtime/helpers/taggedTemplateLiteral"),
  TT = function (_) {
    return "mp-broker://".concat(_);
  },
  AT = TT(_ || (_ = ET(["BI_REFERS"]))),
  ST = TT(E || (E = ET(["statData"]))),
  IT = TT(T || (T = ET(["statDataFm"]))),
  RT = TT(A || (A = ET(["statDataI"]))),
  OT = TT(S || (S = ET(["statDataO"]))),
  NT = TT(I || (I = ET(["wzq_channel"]))),
  DT = TT(R || (R = ET(["STAT_CACHE"]))),
  CT = TT(O || (O = ET(["relogin"]))),
  eT = TT(N || (N = ET(["relogin_webiew"]))),
  BT = TT(D || (D = ET(["MAIN_WEBVIEW_COOKIES"]))),
  PT = TT(C || (C = ET(["MP_LOGIN_OPENID_BIND"]))),
  LT = TT(e || (e = ET(["wx_sign"]))),
  tT = TT(B || (B = ET(["WEBSOCKET_ERROR_COUNT"]))),
  sT = "wzq_qluin",
  UT = TT(P || (P = ET(["userinfo"]))),
  rT = TT(L || (L = ET(["LAST_AVAILABLE_DOMAIN"]))),
  oT = TT(t || (t = ET(["TRADE_SEED"]))),
  pT = TT(s || (s = ET(["ASSET_SORT_TYPE"]))),
  aT = TT(U || (U = ET(["FINANCIAL_SORT_TYPE"]))),
  iT = TT(r || (r = ET(["ALLOCATE_DEBT_SORT_TYPE"]))),
  KT = TT(o || (o = ET(["KEY_ASSET_HIDDEN"]))),
  MT = TT(p || (p = ET(["TRADE_CONFIRM_NEED_SIGN"]))),
  YT = TT(a || (a = ET(["NEWSTOCK_LUCKY"]))),
  GT = TT(i || (i = ET(["ASSET_NEWSTOCK_REDPOINT"]))),
  HT = TT(K || (K = ET(["LOTTERY_POPUP_SHOWN"]))),
  FT = TT(M || (M = ET(["ASSET_ORDER_LIST_EXPANDED"]))),
  WT = TT(Y || (Y = ET(["TRADE_TRANS_INFO_NUM"]))),
  xT = TT(G || (G = ET(["ASSET_SHOW_JXB_ENTRY"]))),
  nT = TT(H || (H = ET(["ASSET_HOLDSTOCK_LEN"]))),
  dT = TT(F || (F = ET(["ASSET_SHOW_DUOTIANQI_ENTRY"]))),
  lT = TT(W || (W = ET(["ASSET_BACK_BUTTON"]))),
  cT = TT(x || (x = ET(["TRADE_SEARCH_LOCAL_DATA"]))),
  bT = TT(n || (n = ET(["ACTIVITY_INFO"]))),
  uT = TT(d || (d = ET(["BALANCE_CONFIRMATION_SIGN_KEY"]))),
  VT = TT(l || (l = ET(["BALANCE_PROTOCOL_SIGN_KEY"]))),
  ZT = TT(c || (c = ET(["NEWSTOCK_TIPS"]))),
  gT = TT(b || (b = ET(["AICS_BUTTON_REDPOINT"]))),
  zT = TT(u || (u = ET(["ASSET_AICS_BANNER"]))),
  mT = TT(V || (V = ET(["ASSET_AICS_BUBBLE"]))),
  yT = TT(Z || (Z = ET(["TRADE_INFO"]))),
  hT = TT(g || (g = ET(["NEWSTOCK_BOOKING_NOTIFY"]))),
  XT = TT(z || (z = ET(["NEWSTOCK_BOOKING_BUBBLE"]))),
  wT = TT(m || (m = ET(["WEEKLY_REPORT_BUBBLE"]))),
  kT = TT(y || (y = ET(["DEBT_AUTO_ORDER_TIME_GUIDE"]))),
  fT = TT(h || (h = ET(["DEBT_AUTO_ORDER_TIME_RED_DOT_CLICKED"]))),
  vT = TT(X || (X = ET(["TRADE_ST_RISK_TIPS"]))),
  qT = TT(w || (w = ET(["TRADE_DELISTING_ARRANGEMENT_TIPS"]))),
  QT = TT(k || (k = ET(["TRADE_RISK_TIPS_STOCK_DIC"]))),
  jT = TT(f || (f = ET(["NEWSTOCK_BUBBLE_TIP"]))),
  JT = TT(v || (v = ET(["NEWSTOCK_IPO_INFO"]))),
  $T = TT(q || (q = ET(["apply/steplist"]))),
  _A = TT(Q || (Q = ET(["apply/noaccount_agreement"]))),
  EA = TT(j || (j = ET(["apply/noaccount_useragreementlist"]))),
  TA = TT(J || (J = ET(["apply/selected_card"]))),
  AA = TT($ || ($ = ET(["apply/bankcard_example"]))),
  SA = TT(__ || (__ = ET(["apply/idcard_example"]))),
  IA = TT(E_ || (E_ = ET(["apply/idcard_retake"]))),
  RA = TT(T_ || (T_ = ET(["apply/risktest_skipdesc"]))),
  OA = TT(A_ || (A_ = ET(["biz/pwd_reset/video_filename"]))),
  NA = TT(S_ || (S_ = ET(["apply/nosign_privacyprotocol"]))),
  DA = TT(I_ || (I_ = ET(["apply/video_label_miss"]))),
  CA = TT(R_ || (R_ = ET(["apply/idcard_oom_detect"]))),
  eA = TT(O_ || (O_ = ET(["apply/retain_exit_reason_show_date"]))),
  BA = TT(N_ || (N_ = ET(["apply/apply_channel"]))),
  PA = TT(D_ || (D_ = ET(["APPLY_ARGS_SAVED"]))),
  LA = TT(C_ || (C_ = ET(["biz/pwd_reset/fundaccount"]))),
  tA = TT(e_ || (e_ = ET(["biz/pwd_reset/video_filename"]))),
  sA = TT(B_ || (B_ = ET(["biz/pwd_reset/cy_code"]))),
  UA = TT(P_ || (P_ = ET(["biz/pwd_reset/timeLimit"]))),
  rA = TT(L_ || (L_ = ET(["biz/pwd_reset/form/show"]))),
  oA = TT(t_ || (t_ = ET(["biz/pwd_change/oldpwd"]))),
  pA = TT(s_ || (s_ = ET(["biz/pwd_change/transfer_session"]))),
  aA = TT(U_ || (U_ = ET(["biz/pwd_change/xid_session"]))),
  iA = TT(r_ || (r_ = ET(["biz/pwd_change/sms_code"]))),
  KA = TT(o_ || (o_ = ET(["biz/pwd_change/account"]))),
  MA = TT(p_ || (p_ = ET(["biz/pwd_change/tel"]))),
  YA = TT(a_ || (a_ = ET(["biz/pwd_change/returnUrl"]))),
  GA = TT(i_ || (i_ = ET(["biz/risk_update/testRisk"]))),
  HA = TT(K_ || (K_ = ET(["biz/risk_reminder/showTime"]))),
  FA = TT(M_ || (M_ = ET(["biz/risk_reminder/update_action"]))),
  WA = TT(Y_ || (Y_ = ET(["biz/risk_reminder/complete_time"]))),
  xA = TT(G_ || (G_ = ET(["biz/id_update/photoinfo"]))),
  nA = TT(H_ || (H_ = ET(["biz/id_update/sex"]))),
  dA = TT(F_ || (F_ = ET(["biz/id_update/nation"]))),
  lA = TT(W_ || (W_ = ET(["biz/id_update/issue_authority"]))),
  cA = TT(x_ || (x_ = ET(["biz/id_front_filename"]))),
  bA = TT(n_ || (n_ = ET(["biz/id_back_filename"]))),
  uA = TT(d_ || (d_ = ET(["biz/userinfo_force_update"]))),
  VA = TT(l_ || (l_ = ET(["biz/kechuang_come_from"]))),
  ZA = TT(c_ || (c_ = ET(["biz/kechuang_test_answer"]))),
  gA = TT(b_ || (b_ = ET(["biz/kechuang_test_score"]))),
  zA = TT(u_ || (u_ = ET(["biz/kechuang_test_topic_no"]))),
  mA = TT(V_ || (V_ = ET(["biz/kechuang_test_times"]))),
  yA = TT(Z_ || (Z_ = ET(["biz/gem/transfer"]))),
  hA = TT(g_ || (g_ = ET(["biz/gem/returl"]))),
  XA = TT(z_ || (z_ = ET(["asset/asset_entry_all_redpoint"]))),
  wA = TT(m_ || (m_ = ET(["asset/gov_rp_type_adv"]))),
  kA = TT(y_ || (y_ = ET(["all/gov_rp_type_adv"]))),
  fA = TT(h_ || (h_ = ET(["asset/asset_has_gov"]))),
  vA = TT(X_ || (X_ = ET(["asset/gov_adv_info"]))),
  qA = TT(w_ || (w_ = ET(["account/bstmark_entry"]))),
  QA = TT(k_ || (k_ = ET(["/account/auto_addchoose_entry"]))),
  jA = TT(f_ || (f_ = ET(["choose/auth_dialog"]))),
  JA = TT(v_ || (v_ = ET(["analysis/guided"]))),
  $A = TT(q_ || (q_ = ET(["analysis/band_assist_bubble_tip"]))),
  _S = TT(Q_ || (Q_ = ET(["analysis/stock_signal_bubble_tip"]))),
  ES = TT(j_ || (j_ = ET(["asset/cmschina_agree_share"]))),
  TS = TT(J_ || (J_ = ET(["analysis/agree_share"]))),
  AS = TT($_ || ($_ = ET(["analysis/asset_bar"]))),
  SS = TT(_E || (_E = ET(["analysis/tips_hide"]))),
  IS = TT(EE || (EE = ET(["asset/condition_sign"]))),
  RS = TT(TE || (TE = ET(["asset/price_condition_breakthough_tips"]))),
  OS = TT(AE || (AE = ET(["biz/duotianqi_buy_limit_tips"]))),
  NS = TT(SE || (SE = ET(["zxg/asset_tab_refresh"]))),
  DS = TT(IE || (IE = ET(["TRADE_FROM_LCT"]))),
  CS = TT(RE || (RE = ET(["REGISTER_RISK_SIGN"]))),
  eS = TT(OE || (OE = ET(["MP_FROM_SOURCE"]))),
  BS = TT(NE || (NE = ET(["ETF_RACE_HOT_RANK_ANIMATE"]))),
  PS = TT(DE || (DE = ET(["ETF_RACE_HOT_RANK_SHOW_DETAIL"]))),
  LS = TT(CE || (CE = ET(["ETF_RACE_HOT_FUND_COMP_ORDER"]))),
  tS = TT(eE || (eE = ET(["ETF_RACE_ETF_ADD_STATUS"]))),
  sS = TT(BE || (BE = ET(["BIND_OEM_OFFICIAL_DIALOG_TIME_LIMIT"]))),
  US = TT(PE || (PE = ET(["ETF_RACE_ETF_ICON_REDPOINT"]))),
  rS = TT(LE || (LE = ET(["SHADOW_ACCOUNT_REDPOINT"]))),
  oS = TT(tE || (tE = ET(["ETF_SUBSCRIBE_INVEST_EDU_FLAG"]))),
  pS = TT(sE || (sE = ET(["operate-expanded"]))),
  aS = TT(UE || (UE = ET(["cookies"]))),
  iS = TT(rE || (rE = ET(["MP_NOPROXY"]))),
  KS = TT(oE || (oE = ET(["MARGIN_ACCOUNT_STATUS"]))),
  MS = TT(pE || (pE = ET(["MARGIN_ASSET_BACK_BUTTON"]))),
  YS = TT(aE || (aE = ET(["MARGIN_MODE_CHANGED"]))),
  GS = TT(iE || (iE = ET(["ACTIVITY_BANK_CHANNEL"]))),
  HS = TT(KE || (KE = ET(["MARGIN_RELEASE_SUBSCRIBE"]))),
  FS = TT(ME || (ME = ET(["H5_COOKIE_IN_BROKER_XCX"]))),
  WS = TT(YE || (YE = ET(["BST_DAY_TYPE_CACHE"]))),
  xS = TT(GE || (GE = ET(["BST_MINTUE_TYPE_CACHE"]))),
  nS = TT(HE || (HE = ET(["BST_SWITCH_CACHE"]))),
  dS = TT(FE || (FE = ET(["BST_TRADE_RECORD_CACHE"]))),
  lS = TT(WE || (WE = ET(["PLUGIN_FIRST_OPEN"]))),
  cS = TT(xE || (xE = ET(["FUND_ACCOUNTS"]))),
  bS = TT(nE || (nE = ET(["FUND_RECORD_DETAIL_CANCE_ORDER"]))),
  uS = TT(dE || (dE = ET(["TRANSFER_DETAIL_CANCE_ORDER"]))),
  VS = TT(lE || (lE = ET(["CHARGE_EVALUATION_STATUS"]))),
  ZS = TT(cE || (cE = ET(["ASSET_INDEX_BULLETIN"]))),
  gS = TT(bE || (bE = ET(["TRADE_STOCK_BULLETIN"]))),
  zS = TT(uE || (uE = ET(["TRANSFER_BULLETIN"]))),
  mS = TT(VE || (VE = ET(["APPLY_PROGRESS_BULLETIN"]))),
  yS = TT(ZE || (ZE = ET(["IDCARD_VERIFY_BULLETIN"]))),
  hS = TT(gE || (gE = ET(["ASSET_NEW_USER_GUIDE"]))),
  XS = TT(zE || (zE = ET(["TRADE_STOCK_NEW_USER_GUIDE"]))),
  wS = TT(mE || (mE = ET(["ASSET_DRAWER_BUBBLE_TIPS"]))),
  kS = TT(yE || (yE = ET(["ASSET_GGT_BUBBLE_TIPS"]))),
  fS = TT(hE || (hE = ET(["NEW_STOCK_BULLETBAR_HAS_SHOW"]))),
  vS = TT(XE || (XE = ET(["LAST_TRADE_MODE"]))),
  qS = TT(wE || (wE = ET(["TRADE_MODE_SWITCH_BUBBLE_TIPS"]))),
  QS = TT(kE || (kE = ET(["TRADE_MODE_TABBAR_DROPDOWN_BUBBLE_TIPS"]))),
  jS = TT(fE || (fE = ET(["LAST_TRADE_PRICE_STRATEGY"]))),
  JS = TT(vE || (vE = ET(["FIVE_TRANSINFO_ENTRY_TIP"]))),
  $S = TT(qE || (qE = ET(["APP_TRADE_MODE_SYNC"]))),
  _I = TT(QE || (QE = ET(["APP_CUR_SWITCH_SYNC"]))),
  EI = TT(jE || (jE = ET(["LAST_TRADE_RECORD_TAB"]))),
  TI = TT(JE || (JE = ET(["MILESTONE_SHOWN_EXCITES"]))),
  AI = TT($E || ($E = ET(["CARD_ORDER_STORAGE_KEY"]))),
  SI = TT(_T || (_T = ET(["STOCK_COLOR_MODE"]))),
  II = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        ACTIVITY_BANK_CHANNEL: GS,
        ACTIVITY_INFO: bT,
        AICS_BUTTON_REDPOINT: gT,
        ALLOCATE_DEBT_SORT_TYPE: iT,
        ANALYSIS_AGREE_SHARE: TS,
        ANALYSIS_ASSET_BAR: AS,
        ANALYSIS_GUIDED: JA,
        ANALYSIS_TIPS_HIDE: SS,
        APPLY_ARGS_SAVED: PA,
        APPLY_BANKCARD_EXAMPLE: AA,
        APPLY_BINDCARD_SELECTEDCARD: TA,
        APPLY_CHANNEL: BA,
        APPLY_IDCARD_EXAMPLE: SA,
        APPLY_IDCARD_OOM_DETECT: CA,
        APPLY_IDCARD_RETAKE: IA,
        APPLY_NOACCOUNT_AGREEMENT: _A,
        APPLY_NOACCOUNT_USERAGREEMENTLIST: EA,
        APPLY_NOSIGN_PRIVACYPROTOCOL: NA,
        APPLY_PROGRESS_BULLETIN: mS,
        APPLY_RETAIN_EXIT_REASON_SHOW_DATE: eA,
        APPLY_RISKTEST_SKIPDESC: RA,
        APPLY_STEP_LIST: $T,
        APPLY_VIDEO_FILENAME: OA,
        APPLY_VIDEO_LABEL_MISS: DA,
        APP_CUR_SWITCH_SYNC: _I,
        APP_TRADE_MODE_SYNC: $S,
        ASSET_AICS_BANNER: zT,
        ASSET_AICS_BUBBLE: mT,
        ASSET_BACK_BUTTON: lT,
        ASSET_DRAWER_BUBBLE_TIPS: wS,
        ASSET_ENTRY_ALL_REDPOINT: XA,
        ASSET_ENTRY_GOV_RP_TYPE_ADV: wA,
        ASSET_ENTRY_HAS_GOV: fA,
        ASSET_GGT_BUBBLE_TIPS: kS,
        ASSET_GOV_ADV_INFO: vA,
        ASSET_HOLDSTOCK_LEN: nT,
        ASSET_INDEX_BULLETIN: ZS,
        ASSET_NEWSTOCK_REDPOINT: GT,
        ASSET_NEW_USER_GUIDE: hS,
        ASSET_ORDER_LIST_EXPANDED: FT,
        ASSET_SHOW_DUOTIANQI_ENTRY: dT,
        ASSET_SHOW_JXB_ENTRY: xT,
        ASSET_SORT_TYPE: pT,
        AUTO_ADDCHOOSE_MARK_ENTRY: QA,
        All_ENTRY_GOV_RP_TYPE_ADV: kA,
        BALANCE_CONFIRMATION_SIGN_KEY: uT,
        BALANCE_PROTOCOL_SIGN_KEY: VT,
        BAND_ASSIST_BUBBLE_TIP: $A,
        BIND_OEM_OFFICIAL_DIALOG_TIME_LIMIT: sS,
        BIZ_DUOTIANQI_BUY_LIMIT_TIPS: OS,
        BIZ_GEM_RETURL: hA,
        BIZ_GEM_TRANSFER: yA,
        BIZ_IDUPDATE_ISSUE_AUTHORITY: lA,
        BIZ_IDUPDATE_NATION: dA,
        BIZ_IDUPDATE_PHOTOINFO: xA,
        BIZ_IDUPDATE_SEX: nA,
        BIZ_ID_BACK_FILENAME: bA,
        BIZ_ID_FRONT_FILENAME: cA,
        BIZ_KECHUANG_COME_FROM: VA,
        BIZ_KECHUANG_TEST_ANSWER: ZA,
        BIZ_KECHUANG_TEST_SCORE: gA,
        BIZ_KECHUANG_TEST_TIMES: mA,
        BIZ_KECHUANG_TEST_TOPIC_NO: zA,
        BIZ_PWDCHANGE_ACCOUNT: KA,
        BIZ_PWDCHANGE_OLDPWD: oA,
        BIZ_PWDCHANGE_RETURNURL: YA,
        BIZ_PWDCHANGE_SMS_CODE: iA,
        BIZ_PWDCHANGE_TEL: MA,
        BIZ_PWDCHANGE_TRANSFER_SESSION: pA,
        BIZ_PWDCHANGE_XID_SESSION: aA,
        BIZ_PWDRESET_CY_CODE: sA,
        BIZ_PWDRESET_FORM_SHOW: rA,
        BIZ_PWDRESET_FUNDACCOUNT: LA,
        BIZ_PWDRESET_TIMELIMIT: UA,
        BIZ_PWDRESET_VIDEO_FILENAME: tA,
        BIZ_REMINDER_COMPLETETIME: WA,
        BIZ_RISKREMINDER_SHOWTIME: HA,
        BIZ_RISKREMINDER_UPADTED: FA,
        BIZ_RISKUPDATE_TESTRISK: GA,
        BIZ_USERINFO_FORCE_UPDATE: uA,
        BI_COOKIE: NT,
        BI_REF_CACHE: AT,
        BI_STAT: ST,
        BI_STAT_FM: IT,
        BI_STAT_I: RT,
        BI_STAT_O: OT,
        BST_DAY_TYPE_CACHE: WS,
        BST_MARK_ENTRY: qA,
        BST_MINTUE_TYPE_CACHE: xS,
        BST_SWITCH_CACHE: nS,
        BST_TRADE_RECORD_CACHE: dS,
        CARD_ORDER_STORAGE_KEY: AI,
        CHARGE_EVALUATION_STATUS: VS,
        CHOOSE_INDEX_AUTH_DIALOG: jA,
        CMSCHINA_AGREE_SHARE: ES,
        CONDIITON_SIGN_PROTOCOL: IS,
        COOKIES: aS,
        DEBT_AUTO_ORDER_TIME_GUIDE: kT,
        DEBT_AUTO_ORDER_TIME_RED_DOT_CLICKED: fT,
        ETF_RACE_ETF_ADD_STATUS: tS,
        ETF_RACE_ETF_ICON_REDPOINT: US,
        ETF_RACE_HOT_FUND_COMP_ORDER: LS,
        ETF_RACE_HOT_RANK_ANIMATE: BS,
        ETF_RACE_HOT_RANK_SHOW_DETAIL: PS,
        ETF_SUBSCRIBE_INVEST_EDU_FLAG: oS,
        FINANCIAL_SORT_TYPE: aT,
        FIVE_TRANSINFO_ENTRY_TIP: JS,
        FUND_ACCOUNTS: cS,
        FUND_RECORD_DETAIL_CANCE_ORDER: bS,
        H5_COOKIE_IN_BROKER_XCX: FS,
        IDCARD_VERIFY_BULLETIN: yS,
        KEY_ASSET_HIDDEN: KT,
        LAST_AVAILABLE_DOMAIN: rT,
        LAST_TRADE_MODE: vS,
        LAST_TRADE_PRICE_STRATEGY: jS,
        LAST_TRADE_RECORD_TAB: EI,
        LOTTERY_POPUP_SHOWN: HT,
        MAIN_WEBVIEW_COOKIES: BT,
        MARGIN_ACCOUNT_STATUS: KS,
        MARGIN_ASSET_BACK_BUTTON: MS,
        MARGIN_MODE_CHANGED: YS,
        MARGIN_RELEASE_SUBSCRIBE: HS,
        MILESTONE_SHOWN_EXCITES: TI,
        MP_FROM_SOURCE: eS,
        MP_LOGIN_OPENID_BIND: PT,
        MP_NOPROXY: iS,
        NEWSTOCK_BOOKING_BUBBLE: XT,
        NEWSTOCK_BOOKING_NOTIFY: hT,
        NEWSTOCK_BUBBLE_TIP: jT,
        NEWSTOCK_IPO_INFO: JT,
        NEWSTOCK_LUCKY: YT,
        NEWSTOCK_TIPS: ZT,
        NEW_STOCK_BULLETBAR_HAS_SHOW: fS,
        OPERATE_EXPANDED: pS,
        PLUGIN_FIRST_OPEN: lS,
        PRICE_CONDITION_BREAKTHOUGH_TIPS: RS,
        REGISTER_RISK_SIGN: CS,
        RELOGIN: CT,
        RELOGIN_WEBVIEW: eT,
        SESSION_UIN: sT,
        SHADOW_ACCOUNT_REDPOINT: rS,
        STAT_CACHE: DT,
        STOCK_SIGNAL_BUBBLE_TIP: _S,
        STORAGE_KEY_COLOR_MODE: SI,
        TRADE_CONFIRM_NEED_SIGN: MT,
        TRADE_DELISTING_ARRANGEMENT_TIPS: qT,
        TRADE_EMBEDDED_PRICE_STRATEGY_TIPS:
          "TRADE_EMBEDDED_PRICE_STRATEGY_TIPS",
        TRADE_EMBEDDED_STATUS_KEY: "TRADE_EMBEDDED_STATUS_KEY",
        TRADE_FROM_LCT: DS,
        TRADE_INFO: yT,
        TRADE_MODE_SWITCH_BUBBLE_TIPS: qS,
        TRADE_RISK_TIPS_STOCK_DIC: QT,
        TRADE_SEARCH_LOCAL_DATA: cT,
        TRADE_SEED: oT,
        TRADE_STOCK_BULLETIN: gS,
        TRADE_STOCK_NEW_USER_GUIDE: XS,
        TRADE_ST_RISK_TIPS: vT,
        TRADE_TABBAR_DROPDOWN_BUBBLE_TIPS: QS,
        TRADE_TRANS_INFO_NUM: WT,
        TRANSFER_BULLETIN: zS,
        TRANSFER_DETAIL_CANCE_ORDER: uS,
        USERINFO: UT,
        WEBSOCKET_ERROR_COUNT: tT,
        WEEKLY_REPORT_BUBBLE: wT,
        WX_SIGN: LT,
        ZXG_ASSET_TAB_REFRESH: NS,
      },
      Symbol.toStringTag,
      { value: "Module" }
    )
  );
(exports.ACTIVITY_BANK_CHANNEL = GS),
  (exports.ALLOCATE_DEBT_SORT_TYPE = iT),
  (exports.APPLY_BANKCARD_EXAMPLE = AA),
  (exports.APPLY_CHANNEL = BA),
  (exports.APPLY_IDCARD_OOM_DETECT = CA),
  (exports.APPLY_NOSIGN_PRIVACYPROTOCOL = NA),
  (exports.APPLY_RISKTEST_SKIPDESC = RA),
  (exports.APP_CUR_SWITCH_SYNC = _I),
  (exports.APP_TRADE_MODE_SYNC = $S),
  (exports.ASSET_BACK_BUTTON = lT),
  (exports.ASSET_DRAWER_BUBBLE_TIPS = wS),
  (exports.ASSET_ENTRY_ALL_REDPOINT = XA),
  (exports.ASSET_ENTRY_GOV_RP_TYPE_ADV = wA),
  (exports.ASSET_ENTRY_HAS_GOV = fA),
  (exports.ASSET_GGT_BUBBLE_TIPS = kS),
  (exports.ASSET_GOV_ADV_INFO = vA),
  (exports.ASSET_HOLDSTOCK_LEN = nT),
  (exports.ASSET_INDEX_BULLETIN = ZS),
  (exports.ASSET_NEWSTOCK_REDPOINT = GT),
  (exports.ASSET_ORDER_LIST_EXPANDED = FT),
  (exports.ASSET_SORT_TYPE = pT),
  (exports.AUTO_ADDCHOOSE_MARK_ENTRY = QA),
  (exports.All_ENTRY_GOV_RP_TYPE_ADV = kA),
  (exports.BAND_ASSIST_BUBBLE_TIP = $A),
  (exports.BIZ_KECHUANG_COME_FROM = VA),
  (exports.BIZ_REMINDER_COMPLETETIME = WA),
  (exports.BIZ_RISKREMINDER_SHOWTIME = HA),
  (exports.BIZ_RISKREMINDER_UPADTED = FA),
  (exports.BIZ_USERINFO_FORCE_UPDATE = uA),
  (exports.BI_COOKIE = NT),
  (exports.BST_DAY_TYPE_CACHE = WS),
  (exports.BST_MARK_ENTRY = qA),
  (exports.BST_MINTUE_TYPE_CACHE = xS),
  (exports.BST_SWITCH_CACHE = nS),
  (exports.BST_TRADE_RECORD_CACHE = dS),
  (exports.CARD_ORDER_STORAGE_KEY = AI),
  (exports.CONDIITON_SIGN_PROTOCOL = IS),
  (exports.COOKIES = aS),
  (exports.DEBT_AUTO_ORDER_TIME_GUIDE = kT),
  (exports.DEBT_AUTO_ORDER_TIME_RED_DOT_CLICKED = fT),
  (exports.ETF_RACE_ETF_ICON_REDPOINT = US),
  (exports.FINANCIAL_SORT_TYPE = aT),
  (exports.FIVE_TRANSINFO_ENTRY_TIP = JS),
  (exports.FUND_ACCOUNTS = cS),
  (exports.FUND_RECORD_DETAIL_CANCE_ORDER = bS),
  (exports.KEY_ASSET_HIDDEN = KT),
  (exports.LAST_AVAILABLE_DOMAIN = rT),
  (exports.LAST_TRADE_MODE = vS),
  (exports.LAST_TRADE_PRICE_STRATEGY = jS),
  (exports.LAST_TRADE_RECORD_TAB = EI),
  (exports.LOTTERY_POPUP_SHOWN = HT),
  (exports.MILESTONE_SHOWN_EXCITES = TI),
  (exports.MP_FROM_SOURCE = eS),
  (exports.NEWSTOCK_BOOKING_BUBBLE = XT),
  (exports.NEWSTOCK_BOOKING_NOTIFY = hT),
  (exports.NEWSTOCK_BUBBLE_TIP = jT),
  (exports.NEWSTOCK_IPO_INFO = JT),
  (exports.NEWSTOCK_TIPS = ZT),
  (exports.NEW_STOCK_BULLETBAR_HAS_SHOW = fS),
  (exports.PLUGIN_FIRST_OPEN = lS),
  (exports.PRICE_CONDITION_BREAKTHOUGH_TIPS = RS),
  (exports.RELOGIN = CT),
  (exports.RELOGIN_WEBVIEW = eT),
  (exports.SESSION_UIN = sT),
  (exports.SHADOW_ACCOUNT_REDPOINT = rS),
  (exports.STOCK_SIGNAL_BUBBLE_TIP = _S),
  (exports.STORAGE_KEY_COLOR_MODE = SI),
  (exports.TRADE_CONFIRM_NEED_SIGN = MT),
  (exports.TRADE_MODE_SWITCH_BUBBLE_TIPS = qS),
  (exports.TRADE_RISK_TIPS_STOCK_DIC = QT),
  (exports.TRADE_SEARCH_LOCAL_DATA = cT),
  (exports.TRADE_STOCK_BULLETIN = gS),
  (exports.TRADE_STOCK_NEW_USER_GUIDE = XS),
  (exports.TRADE_TABBAR_DROPDOWN_BUBBLE_TIPS = QS),
  (exports.TRADE_TRANS_INFO_NUM = WT),
  (exports.TRANSFER_DETAIL_CANCE_ORDER = uS),
  (exports.USERINFO = UT),
  (exports.ZXG_ASSET_TAB_REFRESH = NS),
  (exports.storageKey = II);
