var e = { exports: {} },
  l = [
    {
      root: "pages/apply",
      pages: [
        {
          path: "guide",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyGuide",
          busis: ["apply"],
        },
        {
          path: "bindmobile",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyBindMobile",
          busis: ["apply"],
        },
        {
          path: "idcard",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyIdCard",
          busis: ["apply"],
        },
        {
          path: "profile",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyProfile",
          busis: ["apply"],
        },
        {
          path: "bindcard",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyBindCard",
          busis: ["apply"],
        },
        {
          path: "bankauth",
          style: { enablePullDownRefresh: !1 },
          name: "ApplyBankAuth",
          busis: ["apply"],
        },
        {
          path: "bankpwd",
          style: {
            enablePullDownRefresh: !1,
            navigationBarTitleText: "设置密码",
          },
          buildPlugin: "1",
          name: "ApplyBankPwd",
          busis: ["apply"],
        },
        {
          path: "setpwd",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplySetPwd",
          busis: ["apply"],
        },
        {
          path: "risktest",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyRiskTest",
          busis: ["apply"],
        },
        {
          path: "submit",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplySubmit",
          busis: ["apply"],
        },
        {
          path: "pre-review",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyPreReview",
          busis: ["apply"],
        },
        {
          path: "progress",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyProgress",
          busis: ["apply"],
        },
        {
          path: "recover",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyRecover",
          busis: ["apply"],
        },
        {
          path: "facecheck",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyFacecheck",
          busis: ["apply"],
        },
        {
          path: "video",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyVideo",
          busis: ["apply"],
        },
        {
          path: "advisory",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyAdvisory",
          busis: ["apply"],
        },
        {
          path: "questionnaire",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyQuestionnaire",
          busis: ["apply"],
        },
        {
          path: "take-photo",
          style: { enablePullDownRefresh: !1 },
          buildPlugin: "1",
          name: "ApplyTakePhoto",
          busis: ["apply"],
        },
      ],
    },
  ];
({
  "BROKER-ZHONGXINJIANTOU": !0,
  "PLUGIN-MODE": !0,
  "BROKER-CMS": !1,
  "BROKER-HUALIN": !1,
  "BROKER-ZSZQ": !1,
  "BROKER-GJZQ": !1,
  PURE_MINIAPP: !1,
  "BROKER-CNHT": !1,
  "BROKER-GUOSEN": !1,
  OEM: !1,
  MICRO: !1,
  "BROKER-ZHONGJINCAIFU": !1,
  "BROKER-GUANGFA": !1,
  "BROKER-HTSEC": !1,
  "BROKER-ZHONGXIN": !1,
  "BROKER-GUOTAIJUNAN": !1,
  "BROKER-HUATAI": !1,
  "BROKER-XINGYE": !1,
  "BROKER-CAIXIN": !1,
}) &&
  l[0].pages.push({
    path: "video-success",
    style: { enablePullDownRefresh: !1 },
    name: "ApplyVideoSuccess",
    busis: ["apply"],
  }),
  (e.exports = l);
var p = (null == e.exports ? {} : e.exports).default || e.exports,
  s = Object.freeze(
    Object.defineProperty({ __proto__: null, default: p }, Symbol.toStringTag, {
      value: "Module",
    })
  );
(exports.__CJS__export_default__ = p), (exports.__CJS__import__3__ = s);
