var t = require("../../../../../@babel/runtime/helpers/createForOfIteratorHelper"),
  r = Object.defineProperty,
  e = Object.defineProperties,
  i = Object.getOwnPropertyDescriptors,
  n = Object.getOwnPropertySymbols,
  o = Object.prototype.hasOwnProperty,
  a = Object.prototype.propertyIsEnumerable,
  l = function (t, e, i) {
    return e in t
      ? r(t, e, { enumerable: !0, configurable: !0, writable: !0, value: i })
      : (t[e] = i);
  },
  s = function (r, e) {
    for (var i in e || (e = {})) o.call(e, i) && l(r, i, e[i]);
    if (n) {
      var s,
        c = t(n(e));
      try {
        for (c.s(); !(s = c.n()).done; ) {
          i = s.value;
          a.call(e, i) && l(r, i, e[i]);
        }
      } catch (t) {
        c.e(t);
      } finally {
        c.f();
      }
    }
    return r;
  },
  c = function (t, r) {
    return e(t, i(r));
  },
  d = require("../../../../../common/vendor.js"),
  f = {
    text: "股票代码",
    rank: "name",
    isFreeze: !0,
    isRetain: !0,
    isShowCode: !0,
    width: "col-long",
  },
  p = {
    text: "首日开盘涨幅",
    rank: "firstOpenZdf",
    reportRank: "firstOpenZdf",
    franctionalDigit: 2,
    isSign: !0,
    unit: "%",
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  k = {
    text: "首日最高涨幅",
    rank: "firstHighZdf",
    reportRank: "firstHighZdf",
    franctionalDigit: 2,
    isSign: !0,
    unit: "%",
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  g = {
    text: "首日涨幅",
    rank: "firstZdf",
    reportRank: "firstZdf",
    franctionalDigit: 2,
    isSign: !0,
    unit: "%",
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  h = {
    text: "上市日期",
    rank: "ssrq",
    reportRank: "goPublicDate",
    isRetain: !0,
    isSort: !0,
    sortBy: "desc",
    width: "col-long",
    eventId: "",
  },
  S = {
    text: "上市日期\n(美东时间)",
    rank: "ssrq",
    reportRank: "ssrqus",
    isRetain: !0,
    isSort: !0,
    sortBy: "desc",
    width: "col-long",
    eventId: "",
  },
  x = {
    text: "现价/发行价",
    rank: ["price", "fxj"],
    reportRank: "price",
    isSort: !0,
    width: "col-long",
    eventId: "",
  },
  w = {
    text: "发行价",
    rank: "fxj",
    reportRank: "fxj",
    isSort: !0,
    width: "col-short",
    eventId: "",
  },
  v = {
    text: "最新价",
    rank: "price",
    reportRank: "price",
    isSort: !0,
    width: "col-short",
    eventId: "",
  },
  R = {
    text: "最新价",
    rank: "price",
    reportRank: "price",
    franctionalDigit: 3,
    isSort: !0,
    width: "col-short",
    eventId: "",
  },
  D = {
    text: "最新价",
    rank: "zxj",
    reportRank: "zxj",
    franctionalDigit: 3,
    isSort: !0,
    width: "col-short",
    eventId: "",
  },
  u = {
    text: "首日开盘价",
    rank: "firstOpenPrice",
    reportRank: "firstOpenPrice",
    franctionalDigit: 2,
    isSort: !0,
    width: "col-long",
    eventId: "",
  },
  I = {
    text: "首日开盘价",
    rank: "first_open",
    reportRank: "first_open",
    franctionalDigit: 3,
    isSort: !0,
    width: "col-long",
    eventId: "",
  },
  y = {
    text: "涨跌幅",
    rank: "zdf",
    reportRank: "zdf",
    franctionalDigit: 2,
    isSign: !0,
    unit: "%",
    isSort: !0,
    isSetColor: !0,
    width: "col-short",
    eventId: "",
  },
  z = {
    text: "累计涨幅",
    rank: "jdzdf",
    reportRank: "accumulatedZdf",
    franctionalDigit: 2,
    isSign: !0,
    unit: "%",
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  P = {
    text: "累计涨幅",
    rank: "ljzf",
    reportRank: "ljzf",
    franctionalDigit: 2,
    isSign: !0,
    unit: "%",
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  j = {
    text: "每签收益",
    rank: "oneProfit",
    reportRank: "oneProfit",
    franctionalDigit: 2,
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  m = {
    text: "每签获利",
    rank: "oneProfit",
    reportRank: "oneProfit",
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  b = {
    text: "首日最高收益",
    rank: "firstHighProfit",
    reportRank: "firstHighProfit",
    franctionalDigit: 2,
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  O = {
    text: "顶格中签率",
    rank: "zql",
    reportRank: "dgzql",
    type: "dgzql",
    franctionalDigit: 2,
    isCut: !0,
    unit: "%",
    isSort: !0,
    width: "col-long",
    eventId: "",
  },
  q = {
    text: "单账户收益",
    rank: "dzhsy",
    reportRank: "singleAccountProfit",
    franctionalDigit: 2,
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  C = {
    text: "连续涨停",
    rank: "maxDailyLimt",
    reportRank: "maxDailyLimt",
    isSort: !0,
    width: "col-long",
    eventId: "",
  },
  _ = {
    text: "单签收益",
    rank: "dqsy",
    reportRank: "dqsy",
    isSort: !0,
    isSetColor: !0,
    width: "col-long",
    eventId: "",
  },
  Z = {
    text: "中签率",
    rank: "zql",
    reportRank: "zql",
    franctionalDigit: 4,
    unit: "%",
    isSort: !0,
    width: "col-long",
    eventId: "",
  },
  H = {
    text: "成交量",
    rank: "cjl",
    reportRank: "cjl",
    isSort: !0,
    isBig: !0,
    width: "col-long",
    eventId: "",
  },
  B = {
    text: "换手率",
    rank: "hsl",
    reportRank: "hsl",
    franctionalDigit: 2,
    unit: "%",
    isSort: !0,
    width: "col-short",
    eventId: "",
  },
  F = {
    text: "市盈率",
    rank: "syl",
    reportRank: "syl",
    franctionalDigit: 2,
    isSort: !0,
    width: "col-short",
    eventId: "",
  },
  L = {
    text: "市值",
    rank: "zsz",
    reportRank: "zsz",
    isRetain: !0,
    isSort: !0,
    width: "col-short",
    eventId: "",
  },
  A = d.cloneDeep([
    f,
    p,
    k,
    h,
    c(s({}, x), { format: [{ franctionalDigit: 2 }, { franctionalDigit: 2 }] }),
    u,
    y,
    z,
    j,
    b,
  ]),
  E = d.cloneDeep([
    f,
    c(s({}, p), { rank: "first_open_zdf" }),
    c(s({}, k), { rank: "first_high_zdf" }),
    h,
    c(s({}, x), { format: [{ franctionalDigit: 2 }, { isRetain: !0 }] }),
    c(s({}, u), { rank: "first_open", franctionalDigit: 3 }),
    y,
    c(s({}, z), { rank: "ljzf" }),
    c(s({}, j), { rank: "dqsy" }),
    c(s({}, b), { rank: "first_high_profit" }),
    O,
    q,
  ]),
  K = d.cloneDeep([f, h, w, v, y, z, g, C, m]),
  U = d.cloneDeep([f, h, R, P, I, _, Z, q]),
  G = d.cloneDeep([f, h, w, D, y, P, g, H, B, F, L]),
  J = d.cloneDeep([f, S, w, D, y, P, g, H, B, F, L]);
(exports.newBond = E),
  (exports.newHKPerformStock = G),
  (exports.newPerformBond = U),
  (exports.newPerformStock = K),
  (exports.newStock = A),
  (exports.newUSPerformStock = J);
