require("../../app.js"),
  (exports.AVATAR_SIZE = 64),
  (exports.CARD_BG_RADIAL_CLASSIC = {
    cxRatio: 0.1533,
    cyRatio: 0,
    rxRatio: 4.5248,
    ryRatio: 1.6936,
    stops: [
      [0, "#E6EFFF"],
      [0.7969, "#D1E3FF"],
      [1, "#B2D0FF"],
    ],
  }),
  (exports.CARD_BG_RADIAL_SIMPLE = {
    cxRatio: 0.1533,
    cyRatio: 0,
    rxRatio: 4.5477,
    ryRatio: 1.6993,
    stops: [
      [0, "#FFE7E6"],
      [0.7969, "#FFD1D1"],
      [1, "#FFB2B2"],
    ],
  }),
  (exports.CARD_WIDTH = 600),
  (exports.DATE_FONT_SIZE = 24),
  (exports.DATE_LINE_HEIGHT = 34),
  (exports.FOOTER_HEIGHT = 168),
  (exports.FOOTER_PADDING = 24),
  (exports.HEADER_HEIGHT = 226),
  (exports.ITEM_HEADER_GAP = 12),
  (exports.ITEM_HEIGHT = 168),
  (exports.LABEL_FONT_SIZE = 24),
  (exports.LABEL_LINE_HEIGHT = 34),
  (exports.LIST_AREA_BOTTOM_MARGIN = 40),
  (exports.LIST_AREA_RADIUS = 16),
  (exports.LIST_AREA_TOP_MARGIN = 44),
  (exports.LIST_AREA_X_MARGIN = 40),
  (exports.LIST_BG_GRADIENT_CLASSIC = {
    angle: 148,
    stops: [
      [0, "#FCFDFF"],
      [1.001, "#F0F6FF"],
    ],
  }),
  (exports.LIST_BG_GRADIENT_SIMPLE = {
    angle: 148,
    stops: [
      [0, "#FFFCFC"],
      [1.001, "#FFF0F0"],
    ],
  }),
  (exports.LIST_INNER_TOP_PADDING = 32),
  (exports.LIST_INNER_X_PADDING = 32),
  (exports.MARKET_LOGO_GAP = 8),
  (exports.MARKET_LOGO_HEIGHT = 20),
  (exports.MARKET_LOGO_WIDTH = 28),
  (exports.NICKNAME_DATE_GAP = 4),
  (exports.NICKNAME_FONT_SIZE = 24),
  (exports.NICKNAME_LEFT_GAP = 12),
  (exports.NICKNAME_LINE_HEIGHT = 34),
  (exports.NICKNAME_MAX_WIDTH = 356),
  (exports.PRIMARY_CLASSIC = "#3077EC"),
  (exports.PRIMARY_SIMPLE = "#E63535"),
  (exports.QR_SIZE = 108),
  (exports.QR_WRAP_BORDER_COLOR = "#FFDFA0"),
  (exports.QR_WRAP_BORDER_WIDTH = 2),
  (exports.QR_WRAP_RADIUS = 16),
  (exports.QR_WRAP_SHADOW_BLUR = 12),
  (exports.QR_WRAP_SHADOW_COLOR = "rgba(0, 0, 0, 0.10)"),
  (exports.QR_WRAP_SHADOW_OFFSET_X = 0),
  (exports.QR_WRAP_SHADOW_OFFSET_Y = 6),
  (exports.QR_WRAP_SIZE = 120),
  (exports.STOCK_LOGO_SIZE = 32),
  (exports.STOCK_NAME_FONT_SIZE = 30),
  (exports.STOCK_NAME_LINE_HEIGHT = 42),
  (exports.SUBTITLE_FONT_SIZE = 28),
  (exports.SUBTITLE_LINE_HEIGHT = 40),
  (exports.TEXT_PRIMARY = "#262E40"),
  (exports.TITLE_FONT_FAMILY = '"TencentSans W7"'),
  (exports.TITLE_FONT_SIZE = 48),
  (exports.TITLE_FONT_WEIGHT = 700),
  (exports.TITLE_LINE_HEIGHT = 72),
  (exports.TITLE_PADDING_TOP = 114),
  (exports.TITLE_PADDING_X = 40),
  (exports.VALUE_FONT_SIZE = 34),
  (exports.VALUE_LINE_HEIGHT = 48),
  (exports.calcShareCardHeight = function (_) {
    return 302 + 168 * Math.max(_, 1) + 40 + 168;
  });
