require("../broker.js"),
  (exports.BIPLATFORM = "WZQ-WX"),
  (exports.BRIEF = {
    EXTERNAL: {
      SHARELINKS: "osz92p00gf001",
      WXNOTICE: "opk65p00gf001",
      WXNAVMAIN: "orv53p00gf001",
      WXNAVSUB: "owi37p00gf001",
      WXCMSCHINA: "obu16p00gf001",
      WXMOMENTSAD: "ofv15p00gf001",
      WXWALLET: "ohm97p00gf001",
      INTRACOMPANY: "oxk39p00gf001",
    },
    INTERNAL: {},
    FM: {
      REMIND: "fm_wzq_wx_v1_remind_01",
      EXPLORE: "fm_wzq_wx_v1_Find_01",
      ACCOUNT: "fm_wzq_wx_v1_account_01",
      RANKING: "fm_wzq_wx_v1_ranking_01",
      MY: "fm_wzq_wx_v1_my_01",
      TRADE: "fm_wzq_wx_v1_trade_01",
      CHOOSE: "fm_wzq_wx_v1_stocklist_01",
      ASSETS: "fm_wzq_wx_v1_assets_01",
      APPLY: "fm_wzq_wx_v1_apply_01",
      UNKNOWN: "fm_wzq_wx_v1_unknow_01",
    },
  }),
  (exports.DOMAIN = "wzq.tenpay.com"),
  (exports.FIT_REPORTER = {
    fitReporter: 1,
    fitReporterTest: !1,
    fitReporterPath: [],
    sendWithQueue: !0,
    reportQueueSize: 5,
  }),
  (exports.INVEST_COND_SCENE_CONFIG = {
    assetIndex: "IBF00p000u002",
    h5Embeded: "I9x00p000u002",
    simpleEmbeded: "IuZ00p000u003",
    conditionIndex: "I6T00p000u002",
    tradeStock: "IZu00p000u002",
  }),
  (exports.MP_KEYS = { appID: "530010117", eventID: "530010117" }),
  (exports.REGEXP = {
    OCHANNEL: /\bO\w+\b/i,
    ICHANNEL: /\bI\w+\b/i,
    FMCHANNEL: /^fm\w+|^\d+$/i,
  }),
  (exports.SYSTEMCODE = "86"),
  (exports.VERSION = "2"),
  (exports.WZQ_MP_KEYS = { appID: "530010122", eventID: "530010122" }),
  (exports.preserveTags = [
    "information.focus",
    "news_yaowen_touzi_click",
    "news_yaowen_touzimore_click",
    "information.open_importment",
    "information.recommend",
    "information.open_favour",
    "information.flash",
    "information.open_stockflash",
    "information.userstock",
    "information.open_stockuserstock",
    "information.open_userstock",
    "apply.index_again",
    "apply.bankcard_again",
    "apply.photo_again",
    "apply.profile_again",
    "apply.face_again",
    "apply.pwd_again",
    "apply.risktest_again",
    "apply.riskresult_again",
    "apply.progress_again",
    "apply.index_first",
    "apply.bankcard_first",
    "apply.photo_first",
    "apply.profile_first",
    "apply.face_first",
    "apply.pwd_first",
    "apply.risktest_first",
    "apply.riskresult_first",
    "apply.progress_first",
    "brokerstat",
    "retentionrate.optimization",
  ]);
