Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" }),
  (exports.TID = {
    CUSTOM_NEW_ADDSTOCK: 1011,
    CUSTOM_NEW_ADDREMAIND: 1012,
    CUSTOM_NEW_ADDBASKET: 1013,
    CUSTOM_NEW_ADDLIKE: 1014,
    CUSTOM_NEW_GUESSRISEFAIL: 1015,
    CUSTOM_PRO_SHARESTOCK: 1016,
    CUSTOM_PRO_SHAREBASKET: 1017,
    CUSTOM_PRO_ADDPLATE: 1018,
    CUSTOM_PRO_SHAREINFORM: 1019,
    CUSTOM_PRO_MOCKTRADE: 1020,
  });
