exports.config = [
  {
    type: "apply_account_submit",
    path: "/apply/guide",
    name: "ApplyGuide",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki001" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "apply_account_success_no_active",
    path: "/transfer/fund",
    name: "TransferFund",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "in" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf00p000f079" },
    ],
  },
  {
    type: "apply_account_success_need_connect",
    path: "/transfer/checkpwd",
    name: "CheckPwd",
    params: [
      { pKey: "show", pValue: "", pDefaultValue: "true" },
      { pKey: "name", pValue: "", pDefaultValue: "TransferIn" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf00p000f083" },
    ],
  },
  {
    type: "apply_account_success_active_success",
    path: "/transfer/fund",
    name: "TransferFund",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "in" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf00p000f080" },
    ],
  },
  {
    type: "apply_account_tip,apply_account_tip_wait",
    path: "/apply/guide",
    name: "ApplyGuide",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf00p000j011" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "apply_account_failed",
    path: "/apply/guide",
    name: "ApplyGuide",
    params: [
      { pKey: "stat", pValue: "", pDefaultValue: "Ozn01p0070004" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "apply_need_bind",
    path: "/account/bind",
    name: "AccountBind",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf00p000j011" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "replenish_account_failed",
    path: "/apply/guide",
    name: "ApplyGuide",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "Ozn01p0070004" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "apply_source_remind_huafei",
    path: "/apply/index",
    name: "ApplyIndex",
    params: [],
    opt: "not-broker",
  },
  {
    type: "audit_fail_source_remind_huafei",
    path: "/apply/guide",
    name: "ApplyGuide",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf01p000g001" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "apply_source_remind_xinyonka",
    path: "/apply/index",
    name: "ApplyIndex",
    params: [],
    opt: "not-broker",
  },
  {
    type: "audit_fail_source_remind_xinyonka",
    path: "/apply/guide",
    name: "ApplyGuide",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf00p000g014" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "apply_lost_remind",
    path: "/apply/index",
    name: "ApplyIndex",
    params: [],
    opt: "not-broker",
  },
  {
    type: "apply_visit_remind",
    path: "/apply/guide",
    name: "ApplyGuide",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf00p000j010" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "audit_fail_lost_remind",
    path: "/apply/guide",
    name: "ApplyGuide",
    params: [
      { pKey: "stat", pValue: "", pDefaultValue: "Opf00p000j012" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "bank_depoistory_connect_remind",
    path: "/transfer/checkpwd",
    name: "CheckPwd",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00gf240" },
    ],
  },
  {
    type: "bank_depoistory_active_remind",
    path: "/guide/common",
    name: "GuideCommon",
    params: [{ pKey: "bank", pValue: "bankabbr", pDefaultValue: "" }],
  },
  {
    type: "trade_notification",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00gf00009" },
    ],
  },
  {
    type: "cashin_succ,cashin_fail,cashout_succ,cashout_fail",
    path: "/transfer/fund/recordsdetail",
    name: "TransferFundRecordsDetail",
    params: [
      { pKey: "dealNo", pValue: "url_transfer_id", pDefaultValue: "" },
      { pKey: "transfer_type", pValue: "type", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki009" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "margin_cashin_succ",
    path: "/transfer/detail",
    name: "TransferRecordsDetails",
    params: [
      { pKey: "id", pValue: "url_transfer_id", pDefaultValue: "" },
      { pKey: "contract_no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "time", pDefaultValue: "" },
      { pKey: "type", pValue: "type", pDefaultValue: "" },
      { pKey: "money", pValue: "money", pDefaultValue: "" },
      { pKey: "state", pValue: "state", pDefaultValue: "" },
      { pKey: "transferredTime", pValue: "transferredTime", pDefaultValue: "" },
      { pKey: "bank_name", pValue: "bankname", pDefaultValue: "" },
      { pKey: "card_num", pValue: "cardnum", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki004" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "margin_cashin_fail",
    path: "/transfer/result",
    name: "TransferResult",
    params: [
      { pKey: "showwxpaytitle", pValue: "", pDefaultValue: "1" },
      { pKey: "type", pValue: "type", pDefaultValue: "" },
      { pKey: "amount", pValue: "amount", pDefaultValue: "" },
      { pKey: "reason", pValue: "reason", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki009" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "cashinfail_activate,cashoutfail_activate",
    path: "/guide/common",
    name: "GuideCommon",
    params: [{ pKey: "nologinchecks", pValue: "", pDefaultValue: "1" }],
  },
  {
    type: "cashin_fail_indetity_out,cashout_fail_indetity_out,identity_card_remind,identity_card_remind_sx,margin_cashin_fail_indetity_out,margin_cashout_fail_indetity_out",
    path: "/biz/id-update/index",
    name: "BizIdUpdate",
    params: [{ pKey: "from", pValue: "", pDefaultValue: "msg" }],
  },
  {
    type: "online_bussiness_identity_card_scs,online_bussiness_identity_card_fail",
    path: "/biz/id-update/index",
    name: "BizIdUpdate",
    params: [],
  },
  {
    type: "margin_cashout_succ",
    path: "/transfer/detail",
    name: "TransferRecordsDetails",
    params: [
      { pKey: "id", pValue: "url_transfer_id", pDefaultValue: "" },
      { pKey: "contract_no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "time", pDefaultValue: "" },
      { pKey: "type", pValue: "type", pDefaultValue: "" },
      { pKey: "money", pValue: "money", pDefaultValue: "" },
      { pKey: "state", pValue: "state", pDefaultValue: "" },
      { pKey: "transferredTime", pValue: "transferredTime", pDefaultValue: "" },
      { pKey: "bank_name", pValue: "bankname", pDefaultValue: "" },
      { pKey: "card_num", pValue: "cardnum", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki008" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "margin_cashout_fail",
    path: "/transfer/result",
    name: "TransferResult",
    params: [
      { pKey: "showwxpaytitle", pValue: "", pDefaultValue: "1" },
      { pKey: "type", pValue: "type", pDefaultValue: "" },
      { pKey: "amount", pValue: "amount", pDefaultValue: "" },
      { pKey: "reason", pValue: "reason", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki010" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "fund_short_notification",
    path: "/transfer/fund",
    name: "TransferFund",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "in" },
      { pKey: "showwxpaytitle", pValue: "", pDefaultValue: "1" },
      { pKey: "from", pValue: "", pDefaultValue: "ipo" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki024" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "allocate_notification,newstock_payment_notification",
    path: "/newstock/list",
    name: "NewStockList",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "purchaseDate", pValue: "purchase_date", pDefaultValue: "" },
      { pKey: "stat", pValue: "", pDefaultValue: "opk65p00ki023" },
    ],
  },
  {
    type: "PurchaseInfo_notification",
    path: "/newstock/index",
    name: "NewStock",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "purchase_type", pValue: "purchase_type", pDefaultValue: "" },
      { pKey: "stat", pValue: "", pDefaultValue: "opk65p00ki021" },
    ],
  },
  {
    type: "trade_newstock",
    path: "/newstock/records",
    name: "NewStockRecords",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "purchase_type", pValue: "purchase_type", pDefaultValue: "" },
      { pKey: "stat", pValue: "", pDefaultValue: "opk65p00ki022" },
    ],
  },
  {
    type: "trade_newstock_fail",
    path: "/newstock/index",
    name: "NewStock",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "purchase_type", pValue: "purchase_type", pDefaultValue: "" },
      { pKey: "stat", pValue: "", pDefaultValue: "opk65p00ki025" },
    ],
  },
  {
    type: "price_remind_up,price_remind_down",
    path: "/trade/stock",
    name: "TradeStock",
    params: [
      { pKey: "market", pValue: "", pDefaultValue: "" },
      { pKey: "code", pValue: "", pDefaultValue: "" },
      { pKey: "showwxpaytitle", pValue: "", pDefaultValue: "1" },
      { pKey: "skin", pValue: "", pDefaultValue: "light" },
      { pKey: "font", pValue: "", pDefaultValue: "west" },
    ],
  },
  {
    type: "repo_remind_up",
    path: "/debt/index",
    name: "Debt",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki028" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "index_remind_up,index_remind_down",
    path: "/quote/quote",
    name: "stockdetail",
    params: [
      { pKey: "scode", pValue: "scode", pDefaultValue: "" },
      { pKey: "type", pValue: "", pDefaultValue: "" },
      { pKey: "holder", pValue: "", pDefaultValue: "" },
      { pKey: "frombroker", pValue: "", pDefaultValue: "" },
      { pKey: "remindtype", pValue: "", pDefaultValue: "" },
      { pKey: "market", pValue: "type", pDefaultValue: "" },
      { pKey: "act_flow_id", pValue: "", pDefaultValue: "stk_wave" },
    ],
  },
  {
    type: "trade_buy",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki011" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "0" },
    ],
  },
  {
    type: "trade_buy_beforeopen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki033" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "trade_buy_afteropen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki035" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "trade_buy_nottradeday",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki036" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_buy_middle",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki034" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_sell",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki012" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_sell_beforeopen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki037" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_sell_afteropen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki039" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_sell_nottradeday",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki040" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_sell_middle",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki038" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_buy_match",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki014" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_buy_firstmatch",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki013" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_buy_notmatch",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00gf00009" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_sell_match",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki016" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_sell_firstmatch",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki015" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_sell_notmatch",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00gf00009" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_cancel",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki019" },
    ],
  },
  {
    type: "trade_cancel_succ",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki020" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
    ],
  },
  {
    type: "trade_not_trade",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki017" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "0" },
    ],
  },
  {
    type: "repo_receipt",
    path: "/asset/index",
    name: "AssetIndex",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "Opf00p000f075" },
      { pKey: "showgznhgbar", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "account_profit",
    path: "/transfer/detail",
    name: "TransferRecordsDetails",
    params: [
      { pKey: "type", pValue: "type", pDefaultValue: "" },
      { pKey: "contract_no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "transferredTime", pValue: "transferredTime", pDefaultValue: "" },
      { pKey: "money", pValue: "money", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki026" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "stock_profit",
    path: "/transfer/detail",
    name: "TransferRecordsDetails",
    params: [
      { pKey: "type", pValue: "type", pDefaultValue: "" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
      { pKey: "contract_no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "transferredTime", pValue: "transferredTime", pDefaultValue: "" },
      { pKey: "money", pValue: "money", pDefaultValue: "" },
      { pKey: "stock_name", pValue: "stock_name", pDefaultValue: "" },
      { pKey: "stock_code", pValue: "stock_code", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki027" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "order_failed",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "market", pValue: "market", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki018" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "0" },
    ],
  },
  {
    type: "new_user_no_transfer_in_notification",
    path: "/product/duotianqi/index",
    name: "ProductDuoTianQi",
    params: [
      { pKey: "activity_id", pValue: "", pDefaultValue: "activity_common" },
      { pKey: "activity_acct", pValue: "", pDefaultValue: "2" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "Ote34p00qb491" },
    ],
  },
  {
    type: "repo_trade_sell,repo_condorder_order_success",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki044" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_sell_beforeopen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki045" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_sell_afteropen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki046" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "order_not_matched",
    path: "/asset/index",
    name: "AssetIndex",
    params: [{ pKey: "tab", pValue: "", pDefaultValue: "history" }],
  },
  {
    type: "repo_trade_sell_nottradeday",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki047" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_sell_middle",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki048" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_sell_match",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki049" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_sell_firstmatch",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki050" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_sell_notmatch",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki051" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_order_failed",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki052" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_cancel",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki053" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_cancel_succ",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki054" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_trade_not_trade",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki055" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "type", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "pgstock_remind_notification,pgstock_market_notification",
    path: "/asset/index",
    name: "AssetIndex",
    params: [
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki021" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "online_bussiness_reset_passwd_fail",
    path: "/biz/pwd-reset/index",
    name: "BizPwdReset",
    params: [{ pKey: "from", pValue: "", pDefaultValue: "msg" }],
  },
  {
    type: "zq_trade_not_trade",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki017" },
    ],
  },
  {
    type: "zq_trade_buy_match",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki014" },
    ],
  },
  {
    type: "zq_trade_buy_firstmatch",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki013" },
    ],
  },
  {
    type: "zq_trade_sell_match",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki016" },
    ],
  },
  {
    type: "zq_trade_sell_firstmatch",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki015" },
    ],
  },
  {
    type: "zq_trade_buy",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki011" },
    ],
  },
  {
    type: "zq_trade_buy_beforeopen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki033" },
    ],
  },
  {
    type: "zq_trade_buy_afteropen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki035" },
    ],
  },
  {
    type: "zq_trade_buy_nottradeday",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki036" },
    ],
  },
  {
    type: "zq_trade_buy_middle",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki034" },
    ],
  },
  {
    type: "zq_trade_sell",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki012" },
    ],
  },
  {
    type: "zq_trade_sell_beforeopen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki037" },
    ],
  },
  {
    type: "zq_trade_sell_afteropen",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki039" },
    ],
  },
  {
    type: "zq_trade_sell_nottradeday",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki040" },
    ],
  },
  {
    type: "zq_trade_sell_middle",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki038" },
    ],
  },
  {
    type: "zq_trade_cancel",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki019" },
    ],
  },
  {
    type: "zq_trade_cancel_succ",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki020" },
    ],
  },
  {
    type: "zq_order_failed",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki018" },
    ],
  },
  {
    type: "wxmsg_authorize",
    path: "/account/setting",
    name: "AccountSetting",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "skin", pValue: "", pDefaultValue: "light" },
      { pKey: "font", pValue: "", pDefaultValue: "west" },
    ],
  },
  {
    type: "balance_order_succ,balance_order_fail,balance_order_fail_no_quota",
    path: "/product/jiaxinbao/record",
    name: "ProductJiaXinBaoIncomeRecord",
    params: [
      { pKey: "reportid", pValue: "reportid", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "balance_order_fail_funds_low",
    path: "/transfer/fund",
    name: "TransferFund",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "in" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "newstock_market_notification,conv_market_notification",
    path: "/asset/index",
    name: "AssetIndex",
    params: [
      { pKey: "stat", pValue: "", pDefaultValue: "opk65p00ki069" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "special_order_succ,special_order_expire",
    path: "/product/duotianqi/trade-record-detail",
    name: "ProductDuoTianQiTradeRecordDetail",
    params: [
      { pKey: "contract_no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "order_date", pValue: "order_date", pDefaultValue: "" },
      { pKey: "status", pValue: "", pDefaultValue: "0" },
    ],
  },
  {
    type: "special_order_auto_extend",
    path: "/product/duotianqi/trade-record-detail",
    name: "ProductDuoTianQiTradeRecordDetail",
    params: [
      { pKey: "contract_no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "order_date", pValue: "order_date", pDefaultValue: "" },
      { pKey: "status", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "special_order_succ_redeem",
    path: "/product/duotianqi/trade-record-detail",
    name: "ProductDuoTianQiTradeRecordDetail",
    params: [
      { pKey: "contract_no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "order_date", pValue: "order_date", pDefaultValue: "" },
      { pKey: "status", pValue: "", pDefaultValue: "2" },
    ],
  },
  {
    type: "account_success_jxb_promote",
    path: "/product/duotianqi/project-detail",
    name: "ProductDuoTianQiDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "1" },
      { pKey: "limit", pValue: "", pDefaultValue: "8" },
    ],
  },
  {
    type: "special_order_pur_remind",
    path: "/product/duotianqi/project-detail",
    name: "ProductDuoTianQiDetail",
    params: [
      { pKey: "type", pValue: "balance_type", pDefaultValue: "" },
      { pKey: "limit", pValue: "time_limit", pDefaultValue: "" },
    ],
  },
  {
    type: "limit_audit_result",
    path: "/account/personal",
    name: "AccountPersonal",
    params: [{ pKey: "from", pValue: "", pDefaultValue: "msg" }],
  },
  {
    type: "condorder_order_success,condorder_order_failed,condorder_order_invalid",
    path: "/trade/condition/detail",
    name: "ConditionDetail",
    params: [
      { pKey: "cond_id", pValue: "cond_id", pDefaultValue: "" },
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
    ],
  },
  {
    type: "condorder_order_unbind_invalid,newstock_booking_unbind_invalid",
    path: "/apply/index",
    name: "ApplyIndex",
    params: [],
    opt: "not-broker",
  },
  {
    type: "booked_newstock_order_succ",
    path: "/newstock/records",
    name: "NewStockRecords",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "purchase_type", pValue: "", pDefaultValue: "0" },
      { pKey: "stat", pValue: "", pDefaultValue: "opk65p00ki022" },
    ],
  },
  {
    type: "booked_newstock_order_fail",
    path: "/newstock/index",
    name: "NewStock",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat", pValue: "", pDefaultValue: "opk65p00ki021" },
    ],
  },
  {
    type: "booked_newstock_expire,booked_newstock_newly",
    path: "/newstock/index",
    name: "NewStock",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat", pValue: "", pDefaultValue: "opk65p00ki022" },
      { pKey: "tab", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "repo_condorder_order_failed,repo_condorder_order_invalid",
    path: "/debt/auto-order",
    name: "DebtAutoOrder",
    params: [{ pKey: "from", pValue: "", pDefaultValue: "msg" }],
  },
  {
    type: "cond_repo_reset_notify",
    path: "/debt/auto-order",
    name: "DebtAutoOrder",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "forceSetting", pValue: "", pDefaultValue: "1" },
    ],
  },
  {
    type: "cond_repo_open_notify",
    path: "/debt/auto-order",
    name: "DebtAutoOrder",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "forceSetting", pValue: "", pDefaultValue: "1" },
      { pKey: "conf_from_flag", pValue: "", pDefaultValue: "promotional_msg" },
    ],
  },
  {
    type: "fixed_condorder_order_success,fixed_condorder_order_failed",
    path: "/trade/condition/detail",
    name: "ConditionDetail",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "cond_id", pValue: "cond_id", pDefaultValue: "" },
    ],
  },
  {
    type: "apply_account_success_no_active_balance,apply_account_success_active_success_balance",
    path: "/product/duotianqi/index",
    name: "ProductDuoTianQi",
    params: [
      { pKey: "from", pValue: "", pDefaultValue: "msg" },
      { pKey: "stat_data", pValue: "", pDefaultValue: "opk65p00ki024" },
    ],
  },
  {
    type: "margin_dbp_trade_buy,margin_dbp_trade_buy_beforeopen,margin_dbp_trade_buy_afteropen,margin_dbp_trade_buy_nottradeday,margin_dbp_trade_buy_middle,margin_dbp_trade_sell,margin_dbp_trade_sell_beforeopen,margin_dbp_trade_sell_afteropen,margin_dbp_trade_sell_nottradeday,margin_dbp_trade_sell_middle,margin_dbp_trade_buy_match,margin_dbp_trade_buy_firstmatch,margin_dbp_trade_buy_notmatch,margin_dbp_trade_sell_match,margin_dbp_trade_sell_firstmatch,margin_dbp_trade_sell_notmatch,margin_dbp_trade_cancel,margin_dbp_trade_cancel_succ,margin_dbp_trade_not_trade,margin_dbp_order_failed,margin_dbp_zq_trade_not_trade,margin_dbp_zq_trade_buy_match,margin_dbp_zq_trade_buy_firstmatch,margin_dbp_zq_trade_sell_match,margin_dbp_zq_trade_sell_firstmatch,margin_dbp_zq_trade_buy,margin_dbp_zq_trade_buy_beforeopen,margin_dbp_zq_trade_buy_afteropen,margin_dbp_zq_trade_buy_nottradeday,margin_dbp_zq_trade_buy_middle,margin_dbp_zq_trade_sell,margin_dbp_zq_trade_sell_beforeopen,margin_dbp_zq_trade_sell_afteropen,margin_dbp_zq_trade_sell_nottradeday,margin_dbp_zq_trade_sell_middle,margin_dbp_zq_trade_cancel,margin_dbp_zq_trade_cancel_succ,margin_dbp_zq_order_failed,margin_rzrq_trade_buy,margin_rzrq_trade_buy_beforeopen,margin_rzrq_trade_buy_afteropen,margin_rzrq_trade_buy_nottradeday,margin_rzrq_trade_buy_middle,margin_rzrq_trade_sell,margin_rzrq_trade_sell_beforeopen,margin_rzrq_trade_sell_afteropen,margin_rzrq_trade_sell_nottradeday,margin_rzrq_trade_sell_middle,margin_rzrq_trade_buy_match,margin_rzrq_trade_buy_firstmatch,margin_rzrq_trade_buy_notmatch,margin_rzrq_trade_sell_match,margin_rzrq_trade_sell_firstmatch,margin_rzrq_trade_sell_notmatch,margin_rzrq_trade_cancel,margin_rzrq_trade_cancel_succ,margin_rzrq_trade_not_trade,margin_rzrq_order_failed,margin_mq_trade_buy,margin_mq_trade_buy_beforeopen,margin_mq_trade_buy_afteropen,margin_mq_trade_buy_nottradeday,margin_mq_trade_buy_middle,margin_mq_trade_sell,margin_mq_trade_sell_beforeopen,margin_mq_trade_sell_afteropen,margin_mq_trade_sell_nottradeday,margin_mq_trade_sell_middle,margin_mq_trade_buy_match,margin_mq_trade_buy_firstmatch,margin_mq_trade_buy_notmatch,margin_mq_trade_sell_match,margin_mq_trade_sell_firstmatch,margin_mq_trade_sell_notmatch,margin_mq_trade_cancel,margin_mq_trade_cancel_succ,margin_mq_trade_not_trade,margin_mq_order_failed",
    path: "/trade/detail",
    name: "TradeDetail",
    params: [
      { pKey: "type", pValue: "", pDefaultValue: "0" },
      { pKey: "id", pValue: "url_trade_id", pDefaultValue: "" },
      { pKey: "no", pValue: "contract_no", pDefaultValue: "" },
      { pKey: "time", pValue: "trade_time", pDefaultValue: "" },
      { pKey: "skin", pValue: "", pDefaultValue: "light" },
      { pKey: "from", pValue: "", pDefaultValue: "" },
      { pKey: "font", pValue: "", pDefaultValue: "west" },
    ],
  },
  {
    type: "margin_cashinfail_activate,apply_reset_submit,apply_reset_success,apply_reset_failed,pgstock_confirm_notification,pgstock_trade_submit,reward_expired_remind_5210000101001,reward_expired_remind_5210000101002,reward_expired_remind_6190000122001,reward_expired_remind_6190000122002,margin_cashoutfail_activate,apply_account_success,activity_cash_recv_1001_5210000101001,activity_cash_recv_1001_5210000101002,activity_mpp_recv_6190000122001,activity_mpp_recv_6190000122002,online_bussiness_reset_passwd_send,online_bussiness_reset_passwd_scs,activity_lottery_chance,activity_comment_5210000101001,activity_comment_5210000101002,activity_comment_6190000122001,activity_comment_6190000122002,fund_report",
    path: "",
    name: "",
    params: [],
  },
];
