var e = [3, 1, 2],
  l = [
    { id: "solid", name: "实心阳线" },
    { id: "hollow", name: "空心阳线" },
  ],
  t = {
    fq: e[1],
    trendline: !1,
    supportPressureLine: !1,
    gap: !1,
    lastestPrice: !1,
    remindPrice: !1,
    ds: !0,
    zx: !0,
    zjzf: !0,
    minsIndicator: "volume",
    mainIndicator: "ma",
    indicatorCount: 2,
    firstIndicator: "volume",
    secondIndicator: "macd",
    thirdIndicator: "kdj",
    fourthIndicator: "rsi",
    yangKStyle: l[0],
    auctionMode: "close",
    maTypes: [5, 10, 20, 30, 0, 0, 0, 0, 0, 0],
    maTemp: [],
    emaTypes: [12, 50, 0, 0, 0, 0, 0, 0, 0, 0],
    emaTemp: [],
    volumeTypes: [5, 10, 20, 0, 0],
    volumeTemp: [],
    cjeTypes: [5, 10, 20, 0, 0],
    cjeTemp: [],
    macdParams: { short: 12, long: 26, m: 9 },
    dmiParams: { n: 14, m: 6 },
    cciParams: { n: 14 },
    wrParams: { n1: 10, n2: 6 },
    bollParams: { deviation: 20, width: 2 },
    kdjParams: { n1: 9, n2: 3, n3: 3 },
    rsiParams: { n1: 6, n2: 12, n3: 24 },
    chartRatio: 100,
    foldState: !0,
    macdPattern: !0,
    magicNine: !1,
    tradeSecret: !1,
    tradeLine: !1,
    tradeEntranceClosed: null,
  };
(exports.AVG_PAGE_DEFAULT = {
  maTypes: [
    { value: 5, defValue: 5, isSelect: !0, defSelect: !0 },
    { value: 10, defValue: 10, isSelect: !0, defSelect: !0 },
    { value: 20, defValue: 20, isSelect: !0, defSelect: !0 },
    { value: 30, defValue: 30, isSelect: !0, defSelect: !0 },
    { value: 60, defValue: 60, isSelect: !1, defSelect: !1 },
    { value: 120, defValue: 120, isSelect: !1, defSelect: !1 },
    { value: 250, defValue: 250, isSelect: !1, defSelect: !1 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
  ],
  emaTypes: [
    { value: 12, defValue: 12, isSelect: !0, defSelect: !0 },
    { value: 50, defValue: 50, isSelect: !0, defSelect: !0 },
    { value: 20, defValue: 20, isSelect: !1, defSelect: !1 },
    { value: 30, defValue: 30, isSelect: !1, defSelect: !1 },
    { value: 60, defValue: 60, isSelect: !1, defSelect: !1 },
    { value: 120, defValue: 120, isSelect: !1, defSelect: !1 },
    { value: 250, defValue: 250, isSelect: !1, defSelect: !1 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
  ],
  volumeTypes: [
    { value: 5, defValue: 5, isSelect: !0, defSelect: !0 },
    { value: 10, defValue: 10, isSelect: !0, defSelect: !0 },
    { value: 20, defValue: 20, isSelect: !0, defSelect: !0 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
  ],
  cjeTypes: [
    { value: 5, defValue: 5, isSelect: !0, defSelect: !0 },
    { value: 10, defValue: 10, isSelect: !0, defSelect: !0 },
    { value: 20, defValue: 20, isSelect: !0, defSelect: !0 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
    { value: 1, defValue: 1, isSelect: !1, defSelect: !1 },
  ],
}),
  (exports.CHART_SETTING = "hq-chart-setting-pro"),
  (exports.DEFAULT_SETTING = t),
  (exports.FQ = e),
  (exports.FQ_NAMES = ["不复权", "前复权", "后复权"]),
  (exports.INDICATOR = [
    "volume",
    "cje",
    "macd",
    "dmi",
    "cci",
    "wr",
    "boll",
    "kdj",
    "ema",
    "obv",
    "rsi",
    "sar",
    "bias",
    "bbi",
    "trix",
    "ene",
    "vr",
    "arbr",
    "psy",
    "dma",
    "dpo",
  ]),
  (exports.INDICATOR_TEXT = [
    "成交量",
    "成交额",
    "MACD",
    "DMI",
    "CCI",
    "WR",
    "BOLL",
    "KDJ",
    "EMA",
    "OBV",
    "RSI",
    "SAR",
    "BIAS",
    "BBI",
    "TRIX",
    "ENE",
    "VR",
    "ARBR",
    "PSY",
    "DMA",
    "DPO",
  ]),
  (exports.KLINE_MARK = {
    zx: { text: "加自选记录" },
    ds: { text: "公司大事" },
    gap: { text: "跳空缺口" },
    lastestPrice: { text: "最新价" },
    remindPrice: { text: "提醒价" },
    zjzf: { text: "至今涨幅" },
  }),
  (exports.K_STYLES = l),
  (exports.MINS_INDICATORS = ["volume", "macd", "rsi"]),
  (exports.MINS_INDICATORS_TEXT = ["成交量", "MACD", "RSI"]);
