var e = { COMMON: 2048 },
  n = function () {
    var n = arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : 0,
      a = arguments.length > 1 ? arguments[1] : void 0;
    return !!(n & (e.COMMON | e[a]));
  },
  a = [
    { name: "BizIdUpdate", key: "idcard" },
    { name: "BizRiskUpdate", key: "risk", open: !0 },
    { name: "BizRiskUpdateResult", key: "risk" },
    { name: "BizPhoneUpdate", key: "changephone" },
    { name: "BizGem", key: "gem" },
    { name: "BizSt", key: "st" },
    { name: "BizKeChuangOpen", key: "kcb" },
    { name: "BizKeChuangGrowthOpen", key: "kechuanggrowth" },
    { name: "BizKzz", key: "kzzopen" },
    { name: "BizGGTOpen", key: "ggtopen" },
    { name: "BizJifenProductDetail", key: "jifenProductDetail" },
    { name: "AccountCardChange", key: "bankcardchange" },
    { name: "AboutCompany", key: "aboutcompany" },
    { name: "BizDebtIndex", key: "debtopen" },
    { name: "BizPwdReset", key: "resetpwd" },
    { name: "BizPwdChange", key: "changepwd" },
    { name: "BizShareHolderBind", key: "shareholder" },
    { name: "BizPwdChangeFund", key: "changefundpwd" },
    { name: "BizPwdChangeTrade", key: "changetradepwd" },
    { name: "BizPwdResetFund", key: "resetfundpwd" },
    { name: "ProductDuoTianQiOpen", key: "duotianqiopen" },
    { name: "ShadowAccountThird", key: "shadowaccount" },
    { name: "BizProfileUpdate", key: "personal" },
    {
      name: "MarginAssetIndex",
      key: "MarginAssetIndex",
      isMargin: !0,
      replace: !0,
    },
    {
      name: "MarginFundRecord",
      key: "MarginFundRecord",
      isMargin: !0,
      replace: !0,
    },
    {
      name: "MarginTradeIndex",
      key: "MarginTradeIndex",
      isMargin: !0,
      replace: !0,
    },
    {
      name: "MarginIpoIndex",
      key: "MarginIpoIndex",
      isMargin: !0,
      replace: !0,
    },
    {
      name: "MarginFundTransfer",
      key: "MarginFundTransfer",
      isMargin: !0,
      replace: !0,
    },
    { name: "MarginReserveRedirect", key: "MarginReserveRedirect" },
    { name: "BizWakeAccount", key: "wakeAccount" },
    { name: "BizDeleteBankcard", key: "bankcarddelete" },
    { name: "BizChangeMasterCard", key: "changemastercard" },
    { name: "BizModifyFundLimit", key: "modifyFundLimit" },
    { name: "BizAccountUnlock", key: "accountUnlock" },
    { name: "BizAddBankcard", key: "bankcardadd" },
    { name: "BizBjIndex", key: "bj" },
    { name: "BizStockTransferIndex", key: "stocktransfer" },
    { name: "BizStockTransferAuth", key: "stocktransferAuth" },
    { name: "BizOpenStock", key: "openstock" },
    { name: "AccountBind", key: "bind" },
    { name: "AssetIndex", key: "assetIndex" },
    { name: "ApplyIndex", key: "applyIndex" },
  ],
  i = Object.freeze(
    Object.defineProperty(
      {
        __proto__: null,
        F_BROKER_NOPEN: e,
        HALL_ROUTER_MAP: a,
        isNoOpenCanVisit: n,
      },
      Symbol.toStringTag,
      { value: "Module" }
    )
  );
(exports.HALL_ROUTER_MAP = a),
  (exports.__CJS__import__15__ = i),
  (exports.isNoOpenCanVisit = n);
