<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import DataState from '@/components/DataState.vue'
import EmptyState from '@/components/EmptyState.vue'
import { getEtfDetail } from '@/services/market'
import { getKlineSeries, type KlineCandle } from '@/services/kline'

import type { MarketEtfDetail } from '@/services/market-types'
import { useWatchlistStore } from '@/stores/watchlist'

const route = useRoute(); const code = computed(() => String(route.params.code || '')); const detail = ref<MarketEtfDetail | null>(null); const candles = ref<KlineCandle[]>([]); const loading = ref(true); const chartLoading = ref(false); const error = ref(''); const chartError = ref(''); const activeTab = ref<'quote' | 'holdings'>('quote'); const watchlist = useWatchlistStore()
const item = computed(() => detail.value?.quote ?? null); const status = computed<'loading' | 'error' | 'empty' | 'ready'>(() => loading.value ? 'loading' : error.value ? 'error' : item.value ? 'ready' : 'empty'); const view = computed(() => detail.value ?? { code: code.value, quote: null, availability: { available: false, source: 'market-provider' }, holdings: [], holdingsAvailability: { available: false, source: 'market-provider', reason: '详情数据不可用' }, size: null, premium: null, indexName: null }); const followed = computed(() => watchlist.has(code.value))
function formatAmount(value: number | null | undefined) { if (!value || value <= 0) return '不可用'; return value >= 100000000 ? `${(value / 100000000).toFixed(1)}亿` : `${(value / 10000).toFixed(1)}万` }
function metric(value: number | null | undefined, suffix = '') { return value == null ? '不可用' : `${value.toFixed(2)}${suffix}` }
async function load() { loading.value = true; error.value = ''; try { detail.value = await getEtfDetail(code.value); if (!detail.value.quote) return; chartLoading.value = true; const [bars] = await Promise.all([getKlineSeries(code.value, 'daily', '')]); candles.value = bars; if (!bars.length) chartError.value = '暂无日 K 数据，未使用模拟 K 线。' } catch { error.value = 'ETF 详情暂时无法加载，请稍后重试。' } finally { chartLoading.value = false; loading.value = false } }
function toggleFollow() { watchlist.toggle(code.value) }
onMounted(load)
</script>
<template><section class="etf-detail"><header class="detail-nav"><RouterLink to="/etf">‹</RouterLink><span>ETF详情</span><button type="button" aria-label="刷新" @click="load">↻</button></header><DataState :status="status" loading-label="正在加载 ETF 详情" error-title="详情加载失败" empty-title="暂未找到该 ETF" :message="error || '数据源没有返回该标的行情，未展示零值占位数据。'" :retry="load"><template v-if="item"><section class="overview"><p class="eyebrow">ETF / FUND PROFILE</p><div class="name-line"><div><h1>{{ item.name }}</h1><span>{{ item.code }}</span></div><strong :class="item.changePercent >= 0 ? 'text-up' : 'text-down'">{{ item.price.toFixed(3) }}</strong></div><div class="change" :class="item.changePercent >= 0 ? 'text-up' : 'text-down'">{{ item.changePercent >= 0 ? '+' : '' }}{{ item.changePercent.toFixed(2) }}%</div><div class="actions"><button class="secondary-button" type="button" @click="toggleFollow">{{ followed ? '★ 已自选' : '☆ 加入自选' }}</button><RouterLink class="primary-button" :to="`/trade?code=${item.code}`">交易入口</RouterLink></div></section><nav class="detail-tabs panel"><button type="button" :class="{ active: activeTab === 'quote' }" @click="activeTab = 'quote'">行情 / K线</button><button type="button" :class="{ active: activeTab === 'holdings' }" @click="activeTab = 'holdings'">持仓</button></nav><template v-if="activeTab === 'quote'"><section class="metrics panel"><div><small>成交额</small><b>{{ formatAmount(item.amount) }}</b></div><div><small>基金规模</small><b>{{ metric(view.size, ' 亿元') }}</b></div><div><small>折溢价</small><b>{{ metric(view.premium, '%') }}</b></div><div><small>跟踪指数</small><b>{{ view.indexName || '不可用' }}</b></div></section><section class="chart panel"><h2>日 K 线</h2><LoadingState v-if="chartLoading" label="正在加载 K 线" /><EmptyState v-else-if="chartError" title="K 线不可用" :message="chartError" /><div v-else class="candles" role="img" aria-label="ETF日K线"><i v-for="bar in candles" :key="bar.timestamp" :style="{ height: `${Math.max(8, Math.min(100, (bar.high - bar.low) / Math.max(bar.high, 0.01) * 1200))}%`, background: bar.close >= bar.open ? 'var(--up)' : 'var(--down)' }" /></div></section></template><section v-else-if="activeTab === 'holdings'" class="panel placeholder"><h2>ETF 持仓</h2><div v-if="view.holdings.length" class="holdings"><div v-for="holding in view.holdings" :key="holding.code"><span>{{ holding.name }}<small>{{ holding.code }}</small></span><b>{{ metric(holding.weight, '%') }}</b></div></div><EmptyState v-else title="持仓不可用" :message="view.holdingsAvailability.reason || '当前数据源未提供持仓明细。'" /></section></template></DataState></section></template>
<style scoped>.etf-detail{max-width:720px;min-height:100vh;margin:0 auto;background:var(--bg)}.detail-nav{position:sticky;top:0;z-index:2;display:flex;align-items:center;justify-content:space-between;height:48px;padding:0 14px;background:var(--card);border-bottom:1px solid var(--border);font-size:15px;font-weight:600}.detail-nav a,.detail-nav button{border:0;background:transparent;color:var(--muted);font-size:25px}.overview{padding:18px 14px;background:var(--card)}.name-line{display:flex;align-items:flex-end;justify-content:space-between;gap:15px}.name-line h1{font-size:20px}.name-line span{display:block;margin-top:5px;color:var(--muted);font:10px 'JetBrains Mono',monospace}.name-line strong{font:600 30px 'JetBrains Mono',monospace}.change{margin-top:7px;font:13px 'JetBrains Mono',monospace}.actions{display:flex;gap:8px;margin-top:16px}.actions a,.actions button{padding:8px 14px}.detail-tabs{display:flex;margin-top:8px;padding:0 14px}.detail-tabs button{position:relative;flex:1;padding:13px 4px;border:0;background:transparent;color:var(--muted);font-size:12px}.detail-tabs button.active{color:var(--primary);font-weight:600}.detail-tabs button.active:after{position:absolute;right:15%;bottom:-1px;left:15%;height:2px;background:var(--primary);content:''}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:8px;padding:15px 14px}.metrics div{display:flex;flex-direction:column;gap:6px}.metrics small,.holdings small,.news-list small{color:var(--muted);font-size:10px}.metrics b{font:12px 'JetBrains Mono',monospace}.chart,.placeholder{margin-top:8px;padding:16px 14px}.chart h2,.placeholder h2{font-size:15px}.candles{display:flex;align-items:flex-end;gap:3px;height:190px;margin-top:18px;padding:8px;border-bottom:1px solid var(--border);overflow:hidden}.candles i{display:block;min-width:4px;flex:1;opacity:.8}.holdings>div,.news-list a{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid var(--border)}.holdings span,.news-list a{display:flex;flex-direction:column;gap:4px}.news-list a{color:var(--text);text-decoration:none}.news-list strong{font-size:12px}.news-list small{font-size:10px}@media(max-width:520px){.metrics{grid-template-columns:repeat(2,1fr);row-gap:15px}}</style>
