<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import EmptyState from '@/components/EmptyState.vue'
import LoadingState from '@/components/LoadingState.vue'
import type { NewsArticle } from '@/services/news-types'
import { getNewsArticles, getNewsFavorites, removeNewsFavorites, updateNewsFavorites, updateNewsFavorite, type NewsFavorite } from '@/services/news'
import { useFavoritesStore } from '@/stores/favorites'

interface FavoriteView extends NewsFavorite { article: NewsArticle }
const favorites = useFavoritesStore(); const records = ref<FavoriteView[]>([]); const loading = ref(true); const error = ref(''); const category = ref(''); const tag = ref(''); const note = ref(''); const selected = ref<string[]>([]); const editCategory = ref(''); const editTags = ref(''); const editNote = ref('')
const categories = computed(() => [...new Set(records.value.map((item) => item.category || '未分类'))])
const items = computed(() => records.value.filter((item) => (!category.value || item.category === category.value) && (!tag.value || item.tags.some((value) => value.toLowerCase().includes(tag.value.toLowerCase()))) && (!note.value || (item.note ?? '').toLowerCase().includes(note.value.toLowerCase()))))
const allSelected = computed(() => items.value.length > 0 && items.value.every((item) => selected.value.includes(item.newsId)))
async function load() { loading.value = true; error.value = ''; try { if (localStorage.getItem('zedarc-access-token')) records.value = await getNewsFavorites({ category: category.value || undefined, tag: tag.value || undefined, note: note.value || undefined }); else { const all = await getNewsArticles(); records.value = all.filter((item) => favorites.has(item.id)).map((article) => ({ id: article.id, newsId: article.id, category: '未分类', tags: [], createdAt: '', article })) as FavoriteView[] } } catch { error.value = '收藏资讯暂时无法加载。' } finally { loading.value = false } }
function toggleSelected(id: string) { selected.value = selected.value.includes(id) ? selected.value.filter((item) => item !== id) : [...selected.value, id] }
function toggleAll() { selected.value = allSelected.value ? [] : items.value.map((item) => item.newsId) }
async function removeSelected() { if (!selected.value.length) return; const ids = [...selected.value]; if (localStorage.getItem('zedarc-access-token')) await removeNewsFavorites(ids); ids.forEach((id) => { if (favorites.has(id)) favorites.toggle(id) }); records.value = records.value.filter((item) => !ids.includes(item.newsId)); selected.value = [] }
async function applyBatch() { if (!selected.value.length) return; const metadata = { category: editCategory.value || undefined, tags: editTags.value.split(',').map((item) => item.trim()).filter(Boolean), note: editNote.value || undefined }; if (localStorage.getItem('zedarc-access-token')) await updateNewsFavorites(selected.value, metadata); records.value.forEach((item) => { if (selected.value.includes(item.newsId)) { if (metadata.category) item.category = metadata.category; item.tags = metadata.tags ?? item.tags; if (metadata.note !== undefined) item.note = metadata.note } }); editCategory.value = ''; editTags.value = ''; editNote.value = '' }
async function updateNote(item: FavoriteView) { if (localStorage.getItem('zedarc-access-token')) await updateNewsFavorite(item.newsId, { note: item.note }) }
onMounted(load)
</script>
<template>
  <section class="news-sub-page"><header class="sub-header"><RouterLink to="/news">‹ 资讯</RouterLink><div><p>MY NEWS</p><h1>我的收藏</h1></div><span>{{ items.length }} 条</span></header>
    <section class="filters"><select v-model="category" @change="load"><option value="">全部分类</option><option v-for="item in categories" :key="item">{{ item }}</option></select><input v-model="tag" placeholder="标签筛选" @keyup.enter="load" /><input v-model="note" placeholder="备注筛选" @keyup.enter="load" /><button @click="load">筛选</button></section>
    <section v-if="!loading && !error && items.length" class="batch-bar"><label><input type="checkbox" :checked="allSelected" @change="toggleAll" /> 全选</label><input v-model="editCategory" placeholder="批量分类" /><input v-model="editTags" placeholder="批量标签（逗号分隔）" /><input v-model="editNote" placeholder="批量备注" /><button :disabled="!selected.length" @click="applyBatch">更新 {{ selected.length }} 条</button><button class="danger" :disabled="!selected.length" @click="removeSelected">批量取消收藏</button></section>
    <LoadingState v-if="loading" label="正在加载收藏" /><p v-else-if="error" class="error">{{ error }} <button @click="load">重试</button></p><section v-else class="article-list"><div v-for="item in items" :key="item.newsId" class="article-row"><input type="checkbox" :checked="selected.includes(item.newsId)" @change="toggleSelected(item.newsId)" /><RouterLink :to="`/news/${item.article.id}`"><small>{{ item.article.source }} · {{ item.article.time }} · {{ item.category }}<em v-if="item.tags.length"> · #{{ item.tags.join(' #') }}</em></small><strong>{{ item.article.title }}</strong><p>{{ item.article.summary }}</p></RouterLink><input v-model="item.note" class="note" placeholder="添加备注" @blur="updateNote(item)" /><button aria-label="取消收藏" @click="selected = [item.newsId]; removeSelected">★</button></div><EmptyState v-if="!items.length" title="还没有符合条件的收藏" message="调整筛选条件，或在资讯详情中点击收藏。" icon="☆" /></section>
  </section>
</template>
<style scoped>.news-sub-page{width:min(720px,100%);margin:0 auto;color:var(--text)}.sub-header{display:flex;align-items:center;gap:14px;padding:16px;border-bottom:1px solid var(--border);background:var(--card)}.sub-header>a{color:var(--primary);font-size:13px}.sub-header div{flex:1}.sub-header p{color:var(--primary);font:9px 'JetBrains Mono',monospace;letter-spacing:.12em}.sub-header h1{font-size:21px;margin-top:3px}.sub-header>span{color:var(--muted);font-size:10px}.filters,.batch-bar{display:flex;flex-wrap:wrap;gap:7px;padding:10px 16px;background:var(--card);border-bottom:1px solid var(--border)}select,input,button{border:1px solid var(--border);border-radius:5px;padding:7px 8px;background:var(--card);color:var(--text);font-size:11px}.filters input{min-width:100px;flex:1}.filters button,.batch-bar button{color:var(--primary)}.batch-bar label{display:flex;align-items:center;gap:5px;width:100%;font-size:11px}.batch-bar .danger{color:var(--down)}.article-list{background:var(--card)}.article-row{display:flex;gap:9px;align-items:center;margin:0 16px;padding:14px 0;border-bottom:1px solid var(--border)}.article-row>a{min-width:0;flex:1}.article-row small{color:var(--muted);font:10px 'JetBrains Mono',monospace}.article-row em{font-style:normal;color:var(--primary)}.article-row strong{display:block;margin-top:7px;font-size:14px;font-weight:500}.article-row p{overflow:hidden;margin-top:5px;color:var(--muted);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.article-row button{border:0;background:transparent;color:var(--gold);font-size:19px}.note{width:105px}.error{padding:28px 16px;color:var(--down);font-size:12px}.error button{border:0;background:transparent;color:var(--primary)}</style>
