<script setup lang="ts">
import { onMounted, ref } from 'vue'
import EmptyState from '@/components/EmptyState.vue'
import LoadingState from '@/components/LoadingState.vue'
import { getNewsTopic, type NewsTopic } from '@/services/news'
const props = defineProps<{ topicId: string }>(); const topic = ref<NewsTopic>(); const loading = ref(true); const error = ref('')
async function load() { loading.value = true; error.value = ''; try { topic.value = await getNewsTopic(props.topicId) } catch { error.value = '专题详情暂时无法加载。' } finally { loading.value = false } }
function formatDate(date: string) { return new Intl.DateTimeFormat('zh-CN', { month: 'long', day: 'numeric', weekday: 'short' }).format(new Date(`${date}T00:00:00`)) }
onMounted(load)
</script>
<template><section class="topic-detail"><header class="sub-header"><RouterLink to="/news?view=topics">‹ 专题</RouterLink><div><p>TOPIC DETAIL</p><h1>{{ topic?.title || '专题详情' }}</h1></div></header><LoadingState v-if="loading" label="正在加载专题详情" /><p v-else-if="error" class="error">{{ error }} <button @click="load">重试</button></p><template v-else-if="topic"><div class="topic-intro"><span># {{ topic.metadata.code }}</span><h2>{{ topic.metadata.title }}</h2><p>专题元信息 · {{ topic.metadata.count }} 篇文章 · {{ topic.metadata.earliestAt.slice(0, 10) }} 至 {{ topic.metadata.latestAt.slice(0, 10) }}</p></div><section class="timeline"><div v-for="group in topic.timeline" :key="group.date" class="timeline-group"><h3>{{ formatDate(group.date) }}<small>{{ group.date }}</small></h3><div class="article-list"><RouterLink v-for="item in group.articles" :key="item.id" :to="`/news/${item.id}`" class="article-row"><small>{{ item.time }} · {{ item.source }}</small><strong>{{ item.title }}</strong><p>{{ item.summary }}</p><b>›</b></RouterLink></div></div><EmptyState v-if="!topic.timeline.length" title="暂无专题资讯" message="当前数据源暂未返回文章。" icon="⌕" /></section></template></section></template>
<style scoped>.topic-detail{width:min(720px,100%);margin:0 auto;color:var(--text)}.sub-header{display:flex;align-items:center;gap:14px;padding:16px;border-bottom:1px solid var(--border);background:var(--card)}.sub-header>a{color:var(--primary);font-size:13px}.sub-header div{min-width:0}.sub-header p{color:var(--primary);font:9px 'JetBrains Mono',monospace;letter-spacing:.12em}.sub-header h1{overflow:hidden;margin-top:3px;font-size:19px;font-weight:600;text-overflow:ellipsis;white-space:nowrap}.topic-intro{padding:18px 16px;background:#f7f9fc;color:var(--muted);font-size:11px;line-height:1.7}.topic-intro span{color:var(--primary);font:11px 'JetBrains Mono',monospace}.topic-intro h2{margin-top:5px;color:var(--text);font-size:15px;font-weight:600}.topic-intro p{margin-top:7px}.timeline{padding:18px 16px;background:var(--card)}.timeline-group{position:relative;padding-left:20px;border-left:1px solid var(--border)}.timeline-group:before{content:'';position:absolute;left:-4px;top:3px;width:7px;height:7px;border-radius:50%;background:var(--primary)}.timeline-group h3{margin-bottom:5px;font-size:12px}.timeline-group h3 small{margin-left:8px;color:var(--muted);font:10px 'JetBrains Mono',monospace}.article-list{margin-bottom:18px}.article-row{display:block;position:relative;padding:13px 25px 13px 0;border-bottom:1px solid var(--border)}.article-row small{color:var(--muted);font:10px 'JetBrains Mono',monospace}.article-row strong{display:block;margin-top:6px;font-size:14px;font-weight:500}.article-row p{margin-top:5px;color:var(--muted);font-size:11px;line-height:1.5}.article-row b{position:absolute;right:2px;top:42%;color:#aab4c2;font-size:20px}.error{padding:28px 16px;color:var(--down);font-size:12px}.error button{border:0;background:transparent;color:var(--primary)}</style>
