<script setup lang="ts">
import { onMounted, ref } from 'vue'
import EmptyState from '@/components/EmptyState.vue'
import LoadingState from '@/components/LoadingState.vue'
import { getNewsTopics, type NewsTopic } from '@/services/news'
const topics = ref<NewsTopic[]>([]); const loading = ref(true); const error = ref('')
async function load() { try { topics.value = await getNewsTopics() } catch { error.value = '专题暂时无法加载。' } finally { loading.value = false } }
onMounted(load)
</script>
<template><section class="topics-page"><header class="sub-header"><RouterLink to="/news">‹ 资讯</RouterLink><div><p>NEWS TOPICS</p><h1>资讯专题</h1></div></header><LoadingState v-if="loading" label="正在加载专题" /><p v-else-if="error" class="error">{{ error }} <button @click="load">重试</button></p><section v-else class="topic-list"><RouterLink v-for="topic in topics" :key="topic.id" :to="`/news?topic=${encodeURIComponent(topic.id)}`" class="topic-card"><span class="topic-mark">#</span><div><h2>{{ topic.title }}</h2><p>基于公开资讯数据整理 · {{ topic.count }} 篇</p><small>更新于 {{ topic.latestAt.slice(0, 10) }}</small></div><b>›</b></RouterLink><EmptyState v-if="!topics.length" title="暂无专题" message="当前新闻数据暂未形成专题。" icon="#" /></section></section></template>
<style scoped>.topics-page{width:min(720px,100%);margin:0 auto;color:var(--text)}.sub-header{display:flex;align-items:center;gap:14px;padding:16px;border-bottom:1px solid var(--border);background:var(--card)}.sub-header>a{color:var(--primary);font-size:13px}.sub-header div{flex:1}.sub-header p{color:var(--primary);font:9px 'JetBrains Mono',monospace;letter-spacing:.12em}.sub-header h1{font-size:21px;margin-top:3px}.topic-list{padding:9px 16px;background:var(--card)}.topic-card{display:flex;align-items:center;gap:12px;padding:17px 0;border-bottom:1px solid var(--border)}.topic-mark{display:grid;width:38px;height:38px;place-items:center;border-radius:10px;background:#edf4ff;color:var(--primary);font-size:20px}.topic-card div{min-width:0;flex:1}.topic-card h2{font-size:14px;font-weight:500}.topic-card p,.topic-card small{display:block;margin-top:5px;color:var(--muted);font-size:10px}.topic-card b{color:#aab4c2;font-size:22px}.error{padding:28px 16px;color:var(--down);font-size:12px}.error button{border:0;background:transparent;color:var(--primary)}</style>
