Object.defineProperty(exports, "__esModule", { value: !0 }),
  (exports.default = void 0);
var r = {
  100: "获取语音分片信息失败",
  101: "语音分片过大",
  102: "参数不合法",
  103: "访问数据库失败",
  104: "AppID 服务未开通，请在控制台开通服务",
  105: "模板不存在",
  106: "模板停用",
  107: "鉴权失败",
  108: "拼接签名串失败",
  109: "l5获取 IP、port 失败",
  110: "后台识别服务器故障，请从 seq=0重传",
  111: "后台识别模块回包格式错误",
  112: "语音分片为空",
  113: "后台服务器识别超时",
  114: "引擎编号不合法",
  115: "时长计算时音频类型不合法",
  116: "无可使用的免费额度",
  117: "禁止访问",
  118: "请求限流",
  119: "账户欠费停止服务，请及时充值",
  120: "获取 rpcClient 错误",
  121: "后台识别服务器错误，请从seq=0重传",
  122: "后台识别服务器收到的包格式错误",
  123: "后台识别服务器音频解压失败，请从seq=0重传",
  124: "后台识别服务器识别失败，请从seq=0重传",
  125: "后台识别服务器识别失败，请重新尝试",
  126: "后台识别服务器音频分片等待超时，请从seq=0重传",
  127: "后台识别服务器音频分片重复",
  "FailedOperation.ServiceIsolate":
    "账号因为欠费停止服务，请在腾讯云账户充值。",
  "FailedOperation.UserHasNoFreeAmount": "账号本月免费额度已用完。",
  "FailedOperation.UserNotRegistered":
    "服务未开通，请在腾讯云官网语音识别控制台开通服务。",
  InternalError: "内部错误。",
  "InternalError.ErrorConfigure": "初始化配置失败。",
  "InternalError.ErrorCreateLog": "创建日志失败。",
  "InternalError.ErrorDownFile": "下载音频文件失败。",
  "InternalError.ErrorFailNewprequest": "新建数组失败。",
  "InternalError.ErrorFailWritetodb": "写入数据库失败。",
  "InternalError.ErrorFileCannotopen": "文件无法打开。",
  "InternalError.ErrorGetRoute": "获取路由失败。",
  "InternalError.ErrorMakeLogpath": "创建日志路径失败。",
  "InternalError.ErrorRecognize": "识别失败。",
  "InvalidParameter.ErrorContentlength": "请求数据长度无效。",
  "InvalidParameter.ErrorParamsMissing": "参数不全。",
  "InvalidParameter.ErrorParsequest": "解析请求数据失败。",
  InvalidParameterValue: "参数取值错误。",
  "InvalidParameterValue.ErrorInvalidAppid": "AppId无效。",
  "InvalidParameterValue.ErrorInvalidClientip": "ClientIp无效。",
  "InvalidParameterValue.ErrorInvalidEngservice": "EngSerViceType无效。",
  "InvalidParameterValue.ErrorInvalidProjectid": "ProjectId无效。",
  "InvalidParameterValue.ErrorInvalidRequestid": "RequestId无效。",
  "InvalidParameterValue.ErrorInvalidSourcetype": "SourceType无效。",
  "InvalidParameterValue.ErrorInvalidSubservicetype": "SubserviceType无效。",
  "InvalidParameterValue.ErrorInvalidUrl": "Url无效。",
  "InvalidParameterValue.ErrorInvalidUseraudiokey": "UsrAudioKey无效。",
  "InvalidParameterValue.ErrorInvalidVoiceFormat": "音频编码格式不支持。",
  "InvalidParameterValue.ErrorInvalidVoicedata": "音频数据无效。",
};
exports.default = r;
