var n = require("../../stock-crypto-modules-config/dist/index.js"),
  t = {
    DEFAULT: "",
    GUOSEN: n.dist.SIGN_KEY.GUOSEN,
    ZHONGXINJIANTOU: n.dist.SIGN_KEY.ZHONGXINJIANTOU,
    DAFENG: n.dist.SIGN_KEY.DAFENG,
  };
(exports.ALL_MODULE_TYPE = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "vote",
  "module",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
]),
  (exports.BANG_DAN_LIST = "10"),
  (exports.BROKER_GOLD_STOCK = "12"),
  (exports.COLUMN_KEY_MAP = {
    0: {
      grade_buy_count_d: "grade_buy_count_d5",
      zdf: "zdf_d5",
      zljlr: "zljlr_d5",
      grade_count_d: "grade_count_d5",
      north_ff_net_in_d: "north_ff_net_in_d5",
    },
    1: {
      grade_buy_count_d: "grade_buy_count_d20",
      zdf: "zdf_d20",
      zljlr: "zljlr_d20",
      grade_count_d: "grade_count_d20",
      north_ff_net_in_d: "north_ff_net_in_d20",
    },
    2: {
      grade_buy_count_d: "grade_buy_count_d60",
      zdf: "zdf_d60",
      zljlr: "zljlr_d60",
      grade_count_d: "grade_count_d60",
      north_ff_net_in_d: "north_ff_net_in_d60",
    },
    3: {
      grade_buy_count_d: "grade_buy_count_w52",
      zdf: "zdf_w52",
      zljlr: "zljlr_w52",
      grade_count_d: "grade_count_w52",
      north_ff_net_in_d: "north_ff_net_in_w52",
    },
    4: {
      grade_buy_count_d: "grade_buy_count_y",
      zdf: "zdf_y",
      zljlr: "zljlr_y",
      grade_count_d: "grade_count_y",
      north_ff_net_in_d: "north_ff_net_in_y",
    },
  }),
  (exports.ETF_CHANGE = "15"),
  (exports.ETF_LIST = "14"),
  (exports.FINANCE_CALENDAR = "18"),
  (exports.FUND_FLOW_NORTH_KLINE = "5"),
  (exports.FUND_FLOW_NORTH_MINS = "4"),
  (exports.FUND_FLOW_SOUTH_KLINE = "7"),
  (exports.FUND_FLOW_SOUTH_MINS = "6"),
  (exports.INDUSTRY_RANK = "3"),
  (exports.KEYENUM = t),
  (exports.KLINE_CHART = "2"),
  (exports.LONG_HU_BANG = "13"),
  (exports.MAIN_FUND = "16"),
  (exports.MARKET_OVERVIEW_HS = "8"),
  (exports.MINS_CHART = "1"),
  (exports.NATIONALDEBT = "11"),
  (exports.PLATE_TABLE = "9"),
  (exports.SALE_EMPTY = "17"),
  (exports.STORT_VALUE_MAP = {
    0: {
      northFundFlowNetInDay: "northFundFlowNetInDay5",
      gradeBuyCountDay: "gradeBuyCountDay5",
      gradeCountDay: "gradeCountDay5",
      priceRatio: "priceRatioD5",
      netMainIn: "netMainInD5",
    },
    1: {
      northFundFlowNetInDay: "northFundFlowNetInDay20",
      gradeBuyCountDay: "gradeBuyCountDay20",
      gradeCountDay: "gradeCountDay20",
      priceRatio: "priceRatioD20",
      netMainIn: "netMainInD20",
    },
    2: {
      northFundFlowNetInDay: "northFundFlowNetInDay60",
      gradeBuyCountDay: "gradeBuyCountDay60",
      gradeCountDay: "gradeCountDay60",
      priceRatio: "priceRatioD60",
      netMainIn: "netMainInD60",
    },
    3: {
      northFundFlowNetInDay: "northFundFlowNetInWeek52",
      gradeBuyCountDay: "gradeBuyCountWeek52",
      gradeCountDay: "gradeCountWeek52",
      priceRatio: "priceRatioW52",
      netMainIn: "netMainInW52",
    },
    4: {
      northFundFlowNetInDay: "northFundFlowNetInYear",
      gradeBuyCountDay: "gradeBuyCountYear",
      gradeCountDay: "gradeCountYear",
      priceRatio: "priceRatioY",
      netMainIn: "netMainInY",
    },
  }),
  (exports.WZQ_MARKETS = {
    0: "sz",
    1: "sh",
    2: "hk",
    3: "us",
    fu: "fu",
    bj: "bj",
  }),
  (exports.kLineSettings = {
    fq: 1,
    trendline: !1,
    supportPressureLine: !1,
    gap: !1,
    lastestPrice: !1,
    remindPrice: !1,
    ds: !1,
    zx: !1,
    minsIndicator: "volume",
    mainIndicator: "ma",
    indicatorCount: 1,
    firstIndicator: "volume",
    secondIndicator: "macd",
    thirdIndicator: "kdj",
    fourthIndicator: "rsi",
    yangKStyle: { id: "solid", name: "实心阳线" },
    auctionMode: "close",
    miMaTypes: [5, 10, 20, 0, 0, 0, 0, 0, 0, 0],
    maTypes: [5, 10, 20, 30, 0, 0, 0, 0, 0, 0],
    maTemp: [],
    emaTypes: [12, 50, 0, 0, 0, 0, 0, 0, 0, 0],
    emaTemp: [],
    volumeTypes: [5, 10, 20, 0, 0],
    volumeTemp: [],
    cjeTypes: [5, 10, 20, 0, 0],
    cjeTemp: [],
    macdParams: { short: 12, long: 26, m: 9 },
    dmiParams: { n: 14, m: 6 },
    cciParams: { n: 14 },
    wrParams: { n1: 10, n2: 6 },
    bollParams: { deviation: 20, width: 2 },
    kdjParams: { n1: 9, n2: 3, n3: 3 },
    rsiParams: { n1: 6, n2: 12, n3: 24 },
    chartRatio: 100,
    foldState: !0,
    macdPattern: !1,
    magicNine: !1,
    tradeSecret: !1,
    vlineCount: 0,
    hlineCount: 0,
    yAixsCount: 2,
    crossLabel: { hideYlabel: !0 },
    zjzf: !1,
  });
