(exports.OPEN_MESSAGE_PATH_PARAM = {
  ANIM: "anim",
  INFO_DETAIL: "infodetail",
  MY: "my",
}),
  (exports.OUTAPPID = { LCTAPP: "wxd3678b66f965df4a" }),
  (exports.USER_SUB_OPEN_STATUS = {
    NO_SUBSCRIBE_NO_OPEN: "NO_SUBSCRIBE_NO_OPEN",
    SUBSCRIBED_NO_OPEN: "SUBSCRIBED_NO_OPEN",
    NO_SUBSCRIBE_OPENED: "NO_SUBSCRIBE_OPENED",
    SUBSCRIBED_OPENED: "SUBSCRIBED_OPENED",
  });
