require("../../app.js"),
  (exports.queue = {
    applyMode: {
      common: [
        { name: "ApplyIndex" },
        { name: "ApplyBindMobile", stage: !0 },
        { name: "ApplyIdCard" },
        { name: "ApplyProfile" },
        { name: "ApplyFacecheck", stage: !0 },
        { name: "ApplyVideo" },
        { name: "ApplyBindCard" },
        { name: "ApplySetPwd" },
        { name: "ApplyRiskTest" },
        { name: "ApplySubmit", stage: !0 },
        { name: "ApplyAdvisory" },
        { name: "ApplyProgress" },
      ],
      wzq: [
        { name: "ApplyIndex" },
        { name: "ApplyBindCard", stage: !0 },
        { name: "ApplyIdCard" },
        { name: "ApplyProfile" },
        { name: "ApplyFacecheck", stage: !0 },
        { name: "ApplyVideo" },
        { name: "ApplySetPwd" },
        { name: "ApplyRiskTest" },
        { name: "ApplySubmit", stage: !0 },
        { name: "ApplyAdvisory" },
        { name: "ApplyProgress" },
      ],
    },
    recoverMode: {
      common: [
        { name: "ApplyIndex" },
        { name: "ApplyBindMobile", stage: !0 },
        { name: "ApplyIdCard" },
        { name: "ApplyProfile" },
        { name: "ApplyFacecheck", stage: !0 },
        { name: "ApplyVideo" },
        { name: "ApplyBindCard" },
        { name: "ApplySetPwd" },
        { name: "ApplyRiskTest" },
        { name: "ApplySubmit", stage: !0 },
        { name: "ApplyProgress" },
      ],
      wzq: [
        { name: "ApplyIndex" },
        { name: "ApplyBindMobile" },
        { name: "ApplyBindCard" },
        { name: "ApplyIdCard" },
        { name: "ApplyProfile" },
        { name: "ApplyFacecheck" },
        { name: "ApplyVideo" },
        { name: "ApplySetPwd" },
        { name: "ApplyRiskTest" },
        { name: "ApplySubmit" },
        { name: "ApplyProgress" },
      ],
    },
    abtMode: {
      common: [
        { name: "ApplyIndex" },
        { name: "ApplyBindMobile", stage: !0 },
        { name: "ApplyIdCard" },
        { name: "ApplyProfile" },
        { name: "ApplyFacecheck", stage: !0 },
        { name: "ApplyVideo" },
        { name: "ApplyBindCard" },
        { name: "ApplySetPwd" },
        { name: "ApplyRiskTest" },
        { name: "ApplySubmit", stage: !0 },
        { name: "ApplyAdvisory" },
        { name: "ApplyProgress" },
      ],
      wzq: [
        { name: "ApplyIndex" },
        { name: "ApplyIdCard", stage: !0 },
        { name: "ApplyBindCard" },
        { name: "ApplyProfile" },
        { name: "ApplyFacecheck", stage: !0 },
        { name: "ApplyVideo" },
        { name: "ApplySetPwd" },
        { name: "ApplyRiskTest" },
        { name: "ApplySubmit", stage: !0 },
        { name: "ApplyAdvisory" },
        { name: "ApplyProgress" },
      ],
    },
  });
